import { LensKnowledgePackSchema } from "./schema";

export const asakuraConnectionsPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "asakura-connections",
  version: "0.1.0",
  label: "朝倉の古代拠点・祭祀・邪馬台国候補",
  description: "朝倉の訪問地点を、祭神、神仏習合、弥生集落、邪馬台国朝倉説へ接続する。史跡の確認事項と所在地仮説は分離する。",
  status: "draft",
  releasedAt: "2026-09-14",
  sources: [
    { id: "asakura-hiratsuka-official", kind: "modern-reference", title: "平塚川添遺跡", publisher: "朝倉市", url: "https://www.city.asakura.lg.jp/soshiki/33/2137.html", retrievedAt: "2026-09-14", locator: "遺跡の時期・多重環濠・朝倉地域の拠点集落・出土品展示", reviewStatus: "reviewed" },
    { id: "asakura-minagi-official", kind: "modern-reference", title: "美奈宜神社（林田）", publisher: "朝倉市", url: "https://www.city.asakura.lg.jp/site/kanko/3007.html", retrievedAt: "2026-09-14", locator: "御祭神・由緒・所在地", reviewStatus: "reviewed" },
    { id: "chikuzen-onamuchi-official", kind: "modern-reference", title: "大己貴神社", publisher: "筑前町", url: "https://www.town.chikuzen.fukuoka.jp/S044/010/010/20180212172642.html", retrievedAt: "2026-09-14", locator: "大己貴神（大国主神）の祭祀・所在地", reviewStatus: "reviewed" },
    { id: "joshinin-official", kind: "modern-reference", title: "浄心院とは", publisher: "常住金剛山 浄心院", url: "https://joshinin.jp/about/", retrievedAt: "2026-09-14", locator: "仏と神を祀る神仏習合の寺院という説明", reviewStatus: "reviewed" },
    { id: "asakura-yamatai-candidate", kind: "modern-reference", title: "移住・定住 ～朝倉市をご紹介～", publisher: "朝倉市", url: "https://www.city.asakura.lg.jp/site/iju/2938.html", retrievedAt: "2026-09-14", locator: "朝倉周辺を邪馬台国候補地の一つとする説明", reviewStatus: "reviewed", note: "候補説の存在を確認する資料であり、所在地を確定する資料ではない。" },
  ],
  viewpoints: [
    { id: "asakura-kami-view", kind: "source", label: "朝倉の祭神", description: "各神社の公式・自治体解説に基づき、祀られる神と訪問地点を結ぶ。" },
    { id: "asakura-syncretism-view", kind: "source", label: "朝倉の神仏習合", description: "神と仏を併せ祀る具体的な場所から習合を見る。" },
    { id: "asakura-archaeology-view", kind: "source", label: "朝倉の弥生集落", description: "遺構・年代・展示先という確認可能な考古学的関係を見る。" },
    { id: "asakura-yamatai-view", kind: "hypothesis", label: "邪馬台国朝倉説", description: "朝倉を候補地の一つとする説を、遺跡の事実記述と分離して比較する。" },
  ],
  entities: [
    { id: "asakura-region", kind: "place", label: "朝倉地域", aliases: ["朝倉"], coordinates: { latitude: 33.414, longitude: 130.665 } },
    { id: "hiratsuka-kawazoe-site", kind: "place", label: "平塚川添遺跡", aliases: ["平塚川添遺跡公園"], coordinates: { latitude: 33.3958428, longitude: 130.6501853 } },
    { id: "amagi-history-museum", kind: "place", label: "甘木歴史資料館", aliases: [], coordinates: { latitude: 33.41423, longitude: 130.659904 } },
    { id: "minagi-hayashida", kind: "place", label: "美奈宜神社", aliases: ["美奈宜神社（林田）"], coordinates: { latitude: 33.3742878, longitude: 130.6736592 } },
    { id: "onamuchi-shrine", kind: "place", label: "大己貴神社", aliases: [], coordinates: { latitude: 33.4434996, longitude: 130.6540467 } },
    { id: "joshinin", kind: "place", label: "浄心院", aliases: [], coordinates: { latitude: 33.391648, longitude: 130.649947 } },
    { id: "susanoo-asakura", kind: "deity", label: "素戔嗚尊", aliases: ["須佐之男命", "スサノオ"] },
    { id: "onamuchi-deity", kind: "deity", label: "大己貴命", aliases: ["大己貴神", "大国主神", "大國主神"] },
    { id: "kotoshironushi", kind: "deity", label: "事代主命", aliases: [] },
    { id: "shinbutsu-shugo-asakura", kind: "tradition", label: "神仏習合", aliases: [] },
    { id: "third-century-settlement", kind: "concept", label: "2〜3世紀の拠点集落", aliases: ["邪馬台国時代の拠点集落"] },
    { id: "yamatai-asakura-hypothesis", kind: "concept", label: "邪馬台国朝倉説", aliases: ["朝倉＝邪馬台国"] },
  ],
  assertions: [
    { id: "asakura-001", subjectId: "onamuchi-deity", predicate: "enshrined_at", objectId: "onamuchi-shrine", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["asakura-kami-view"], sourceIds: ["chikuzen-onamuchi-official"], confidence: "high", reviewStatus: "reviewed" },
    { id: "asakura-002", subjectId: "susanoo-asakura", predicate: "enshrined_at", objectId: "minagi-hayashida", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["asakura-kami-view"], sourceIds: ["asakura-minagi-official"], confidence: "high", reviewStatus: "reviewed" },
    { id: "asakura-003", subjectId: "onamuchi-deity", predicate: "enshrined_at", objectId: "minagi-hayashida", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["asakura-kami-view"], sourceIds: ["asakura-minagi-official"], confidence: "high", reviewStatus: "reviewed" },
    { id: "asakura-004", subjectId: "kotoshironushi", predicate: "enshrined_at", objectId: "minagi-hayashida", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["asakura-kami-view"], sourceIds: ["asakura-minagi-official"], confidence: "high", reviewStatus: "reviewed" },
    { id: "asakura-005", subjectId: "joshinin", predicate: "associated_with", objectId: "shinbutsu-shugo-asakura", relationFamily: "syncretism", nature: "reviewed-reference", viewpointIds: ["asakura-syncretism-view"], sourceIds: ["joshinin-official"], confidence: "high", reviewStatus: "reviewed" },
    { id: "asakura-006", subjectId: "hiratsuka-kawazoe-site", predicate: "interpreted_as", objectId: "third-century-settlement", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["asakura-archaeology-view"], sourceIds: ["asakura-hiratsuka-official"], confidence: "high", reviewStatus: "reviewed" },
    { id: "asakura-007", subjectId: "hiratsuka-kawazoe-site", predicate: "located_in", objectId: "asakura-region", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["asakura-archaeology-view"], sourceIds: ["asakura-hiratsuka-official"], confidence: "high", reviewStatus: "reviewed" },
    { id: "asakura-008", subjectId: "amagi-history-museum", predicate: "exhibits_material_from", objectId: "hiratsuka-kawazoe-site", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["asakura-archaeology-view"], sourceIds: ["asakura-hiratsuka-official"], confidence: "high", reviewStatus: "reviewed" },
    { id: "asakura-009", subjectId: "asakura-region", predicate: "proposed_as", objectId: "yamatai-asakura-hypothesis", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["asakura-yamatai-view"], sourceIds: ["asakura-yamatai-candidate"], hypothesisGroupId: "yamatai-location-asakura", confidence: "disputed", reviewStatus: "reviewed", note: "自治体が紹介する候補説の存在。朝倉を邪馬台国所在地と確定しない。" },
    { id: "asakura-010", subjectId: "hiratsuka-kawazoe-site", predicate: "provides_context_for", objectId: "yamatai-asakura-hypothesis", relationFamily: "historical-context", nature: "interpretive-model", viewpointIds: ["asakura-yamatai-view", "asakura-archaeology-view"], sourceIds: ["asakura-hiratsuka-official", "asakura-yamatai-candidate"], confidence: "disputed", reviewStatus: "draft", note: "遺跡の年代的文脈と所在地仮説を結ぶ分析線。所在地の証明とは扱わない。" },
  ],
  presets: [
    { id: "asakura-kami-connections", label: "朝倉の祭神関係", lensType: "genealogy", description: "大己貴神社と美奈宜神社から、祀られる神々の重なりを見る。", rootEntityIds: ["onamuchi-shrine", "minagi-hayashida"], relationFamilies: ["enshrinement"], viewpointIds: ["asakura-kami-view"], expansionDepth: 2 },
    { id: "asakura-religious-places", label: "朝倉の祭祀と習合", lensType: "relationship", description: "神社の祭神と浄心院の神仏習合を、同一系譜にせず並べて見る。", rootEntityIds: ["onamuchi-shrine", "minagi-hayashida", "joshinin"], relationFamilies: ["enshrinement", "syncretism"], viewpointIds: ["asakura-kami-view", "asakura-syncretism-view"], expansionDepth: 2 },
    {
      id: "asakura-yamatai-context",
      label: "朝倉説と平塚川添遺跡",
      lensType: "route",
      description: "朝倉説という所在地仮説と、平塚川添遺跡の確認可能な考古学的文脈を分けて重ねる。",
      rootEntityIds: ["asakura-region", "hiratsuka-kawazoe-site"],
      relationFamilies: ["identification", "historical-context", "association"],
      viewpointIds: ["asakura-yamatai-view", "asakura-archaeology-view"],
      hypothesisGroupIds: ["yamatai-location-asakura"],
      expansionDepth: 3,
      mapConnections: [
        {
          id: "asakura-archaeology-corridor",
          label: "朝倉の拠点集落と出土遺物回廊",
          description: "平塚川添遺跡と甘木歴史資料館、周辺の古代祭祀拠点（大己貴神社・美奈宜神社）を結ぶ考古学・空間ネットワークです。",
          displayMode: "line",
          anchorEntityId: "hiratsuka-kawazoe-site",
          contextEntityIds: ["asakura-region", "third-century-settlement", "yamatai-asakura-hypothesis"],
          placeEntityIds: ["hiratsuka-kawazoe-site", "amagi-history-museum", "onamuchi-shrine", "minagi-hayashida"],
          pointFocusEntityIds: {
            "hiratsuka-kawazoe-site": "hiratsuka-kawazoe-site",
            "amagi-history-museum": "amagi-history-museum",
            "onamuchi-shrine": "onamuchi-shrine",
            "minagi-hayashida": "minagi-hayashida",
          },
          assertionIds: ["asakura-006", "asakura-007", "asakura-008", "asakura-010"],
          appearance: { color: "#d5a6ff", legendLabel: "朝倉拠点回廊" },
        },
      ],
    },
    { id: "asakura-social-structure", label: "朝倉の弥生集落構造", lensType: "relationship", description: "多重環濠を持つ拠点集落と出土資料の展示先から、2〜3世紀の地域社会を考える。", rootEntityIds: ["hiratsuka-kawazoe-site", "third-century-settlement"], relationFamilies: ["historical-context", "association"], viewpointIds: ["asakura-archaeology-view"], expansionDepth: 2 },
  ],
});
