import { LensKnowledgePackSchema } from "./schema";

export const hagiBakumatsuPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "hagi-bakumatsu-modernization",
  version: "0.1.0",
  label: "萩・幕末の人材形成と近代化",
  description:
    "藩校・私塾・人物のつながりと、海防を背景にした製鉄・造船の試行を分けて保持する基礎パック。",
  status: "draft",
  releasedAt: "2026-09-01",
  sources: [
    {
      id: "hagi-meirinkan-official",
      kind: "modern-reference",
      title: "旧萩藩校明倫館案内",
      publisher: "萩市",
      url: "https://www.city.hagi.lg.jp/site/meiringakusha/annaizu.html",
      retrievedAt: "2026-09-01",
      locator: "旧萩藩校明倫館",
      reviewStatus: "reviewed",
      note: "明倫館の創設・移転、吉田松陰らの教授歴を確認する公式解説。",
    },
    {
      id: "hagi-human-development",
      kind: "modern-reference",
      title: "萩のひとづくりが近代日本を動かした",
      publisher: "萩市",
      url: "https://www.city.hagi.lg.jp/uploaded/life/62430_583269_misc.pdf",
      retrievedAt: "2026-09-01",
      locator: "H 萩のひとづくりが近代日本を動かした",
      reviewStatus: "reviewed",
      note: "明倫館、松下村塾、高杉晋作らの人材形成を説明する地域文化財資料。",
    },
    {
      id: "hagi-shokasonjuku-official",
      kind: "modern-reference",
      title: "萩エリア～萩市の資産 松下村塾",
      publisher: "萩市",
      url: "https://www.city.hagi.lg.jp/site/sekaiisan/h6081.html",
      retrievedAt: "2026-09-01",
      locator: "松下村塾",
      reviewStatus: "reviewed",
      note: "吉田松陰による私塾と幕末期の人材育成を説明する公式解説。",
    },
    {
      id: "cultural-heritage-industrial-sites",
      kind: "modern-reference",
      title: "明治日本の産業革命遺産 各構成資産の概要",
      publisher: "文化庁 文化遺産オンライン",
      url: "https://bunka.nii.ac.jp/docs/special_content/sangyokakumei_isan_gaiyo.pdf",
      retrievedAt: "2026-09-01",
      locator: "萩反射炉・恵美須ヶ鼻造船所跡",
      reviewStatus: "reviewed",
      note: "萩藩による反射炉建設と洋式船建造の試行錯誤を説明する公的資料。",
    },
    {
      id: "unesco-meiji-industrial-revolution",
      kind: "modern-reference",
      title: "Sites of Japan’s Meiji Industrial Revolution",
      publisher: "UNESCO World Heritage Centre",
      url: "https://whc.unesco.org/en/list/1484/",
      retrievedAt: "2026-09-01",
      locator: "Brief synthesis / Hagi component sites",
      reviewStatus: "reviewed",
      note: "幕末の製鉄・造船の実験を、明治期の産業化へ至る初期段階として位置づける公式記載。",
    },
  ],
  viewpoints: [
    {
      id: "heritage-interpretation",
      kind: "source",
      label: "公的文化遺産解説",
      description: "萩市・文化庁・UNESCOの公開資料に基づく関係。",
    },
    {
      id: "travel-reconnection",
      kind: "analytical",
      label: "訪問からの再接続",
      description: "訪問地点から教育・人物・技術・政治背景を横断する投影。",
    },
  ],
  entities: [
    { id: "hagi-domain", kind: "polity", label: "萩藩（長州藩）", aliases: ["長州藩", "萩藩"] },
    { id: "meirinkan", kind: "place", label: "萩藩校明倫館", aliases: ["明倫館", "萩・明倫学舎"], coordinates: { latitude: 34.4095497, longitude: 131.3991098 } },
    { id: "yoshida-shoin", kind: "person", label: "吉田松陰", aliases: ["松陰"] },
    { id: "shokasonjuku", kind: "place", label: "松下村塾", aliases: [], coordinates: { latitude: 34.412172, longitude: 131.417347 } },
    { id: "takasugi-shinsaku", kind: "person", label: "高杉晋作", aliases: ["晋作"] },
    { id: "kido-takayoshi", kind: "person", label: "木戸孝允", aliases: ["桂小五郎"] },
    { id: "western-knowledge", kind: "concept", label: "西洋技術の知識", aliases: ["洋学"] },
    { id: "coastal-defense", kind: "concept", label: "海防", aliases: [] },
    { id: "hagi-reverberatory-furnace", kind: "place", label: "萩反射炉", aliases: ["反射炉"], coordinates: { latitude: 34.4282032, longitude: 131.4182792 } },
    { id: "ebisugahana-shipyard", kind: "place", label: "恵美須ヶ鼻造船所跡", aliases: ["恵美須ヶ鼻造船所"], coordinates: { latitude: 34.430493, longitude: 131.4121753 } },
    { id: "hagi-modernization", kind: "concept", label: "萩の近代化の試行", aliases: ["近代化"] },
  ],
  assertions: [
    { id: "bakumatsu-001", subjectId: "meirinkan", predicate: "included_instructor", objectId: "yoshida-shoin", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["heritage-interpretation", "travel-reconnection"], sourceIds: ["hagi-meirinkan-official"], confidence: "high", reviewStatus: "reviewed" },
    { id: "bakumatsu-002", subjectId: "meirinkan", predicate: "educated", objectId: "takasugi-shinsaku", relationFamily: "influence", nature: "reviewed-reference", viewpointIds: ["heritage-interpretation", "travel-reconnection"], sourceIds: ["hagi-human-development"], confidence: "high", reviewStatus: "reviewed" },
    { id: "bakumatsu-003", subjectId: "yoshida-shoin", predicate: "led", objectId: "shokasonjuku", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["heritage-interpretation"], sourceIds: ["hagi-shokasonjuku-official"], confidence: "high", reviewStatus: "reviewed" },
    { id: "bakumatsu-004", subjectId: "shokasonjuku", predicate: "influenced", objectId: "takasugi-shinsaku", relationFamily: "influence", nature: "reviewed-reference", viewpointIds: ["heritage-interpretation", "travel-reconnection"], sourceIds: ["hagi-human-development", "hagi-shokasonjuku-official"], confidence: "high", reviewStatus: "reviewed" },
    { id: "bakumatsu-005", subjectId: "coastal-defense", predicate: "motivated", objectId: "hagi-domain", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["heritage-interpretation"], sourceIds: ["cultural-heritage-industrial-sites", "unesco-meiji-industrial-revolution"], confidence: "high", reviewStatus: "reviewed" },
    { id: "bakumatsu-006", subjectId: "western-knowledge", predicate: "influenced", objectId: "hagi-reverberatory-furnace", relationFamily: "influence", nature: "reviewed-reference", viewpointIds: ["heritage-interpretation", "travel-reconnection"], sourceIds: ["cultural-heritage-industrial-sites"], confidence: "high", reviewStatus: "reviewed" },
    { id: "bakumatsu-007", subjectId: "hagi-domain", predicate: "attempted_construction_at", objectId: "hagi-reverberatory-furnace", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["heritage-interpretation"], sourceIds: ["cultural-heritage-industrial-sites"], confidence: "high", reviewStatus: "reviewed" },
    { id: "bakumatsu-008", subjectId: "kido-takayoshi", predicate: "proposed_shipbuilding_at", objectId: "ebisugahana-shipyard", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["heritage-interpretation"], sourceIds: ["cultural-heritage-industrial-sites"], confidence: "high", reviewStatus: "reviewed" },
    { id: "bakumatsu-009", subjectId: "western-knowledge", predicate: "influenced", objectId: "ebisugahana-shipyard", relationFamily: "influence", nature: "reviewed-reference", viewpointIds: ["heritage-interpretation", "travel-reconnection"], sourceIds: ["cultural-heritage-industrial-sites"], confidence: "high", reviewStatus: "reviewed" },
    { id: "bakumatsu-010", subjectId: "hagi-reverberatory-furnace", predicate: "represents_early_stage_of", objectId: "hagi-modernization", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["heritage-interpretation", "travel-reconnection"], sourceIds: ["unesco-meiji-industrial-revolution"], confidence: "high", reviewStatus: "reviewed" },
    { id: "bakumatsu-011", subjectId: "ebisugahana-shipyard", predicate: "represents_early_stage_of", objectId: "hagi-modernization", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["heritage-interpretation", "travel-reconnection"], sourceIds: ["unesco-meiji-industrial-revolution"], confidence: "high", reviewStatus: "reviewed" },
  ],
  presets: [
    {
      id: "bakumatsu-structure",
      label: "人材形成と近代化の二つの流れ",
      lensType: "relationship",
      description: "教育・人物の流れと、海防・西洋技術・産業化の試行を分けて表示する。",
      rootEntityIds: ["takasugi-shinsaku", "hagi-modernization"],
      relationFamilies: ["association", "influence", "historical-context"],
      viewpointIds: ["heritage-interpretation", "travel-reconnection"],
      expansionDepth: 5,
      mapConnections: [
        {
          id: "hagi-education-geography",
          label: "明倫館から松下村塾へ：幕末の人材形成",
          description: "明倫館と松下村塾を、吉田松陰の教授・主宰と高杉晋作の学びを介する二つの教育拠点として示します。単純な移動経路を示す線ではありません。",
          contextEntityIds: ["yoshida-shoin", "takasugi-shinsaku"],
          placeEntityIds: ["meirinkan", "shokasonjuku"],
          assertionIds: ["bakumatsu-001", "bakumatsu-002", "bakumatsu-003", "bakumatsu-004"],
          appearance: { color: "#d5b46d", dashArray: [6, 4], legendLabel: "幕末の人材形成" },
        },
        {
          id: "hagi-modernization-geography",
          label: "萩反射炉と恵美須ヶ鼻造船所跡：近代化の試行",
          description: "海防を背景に、萩藩が西洋技術を取り入れて製鉄と洋式船建造を試みた二つの産業遺産を結びます。訪問順を示す線ではありません。",
          contextEntityIds: ["western-knowledge", "hagi-domain", "kido-takayoshi", "hagi-modernization"],
          placeEntityIds: ["hagi-reverberatory-furnace", "ebisugahana-shipyard"],
          assertionIds: ["bakumatsu-006", "bakumatsu-007", "bakumatsu-008", "bakumatsu-009", "bakumatsu-010", "bakumatsu-011"],
          appearance: { color: "#ef8f72", dashArray: [7, 4], legendLabel: "幕末の近代化実験" },
        },
      ],
    },
  ],
});
