import { LensKnowledgePackSchema } from "./schema";

export const hyugaMythologyPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "hyuga-mythology-network",
  version: "0.1.0",
  label: "天孫降臨・日向神話と海幸山幸",
  description:
    "高天原から高千穂への天孫降臨、ニニギとコノハナサクヤヒメ、山幸彦（ホオリ）と豊玉姫の綿津見宮往還、ウガヤフキアエズ誕生から神武天皇へ至る日向神話空間ネットワーク。",
  status: "active",
  releasedAt: "2026-10-05",
  sources: [
    {
      id: "kojiki-tenson-hyuga",
      kind: "classical-text",
      title: "古事記",
      locator: "中巻「天孫降臨・海佐知山佐知・鵜葺草葺不合命」",
      note: "ニニギノミコトの降臨、コノハナサクヤヒメとの婚姻、火遠理命（山幸彦）の海神宮訪問、ウガヤフキアエズ命の誕生伝承。",
      reviewStatus: "reviewed",
    },
    {
      id: "nihon-shoki-tenson-hyuga",
      kind: "classical-text",
      title: "日本書紀",
      locator: "神代下「第九段 天孫降臨、第十段 海幸山幸」",
      note: "日向の襲の高千穂の峰への降臨、木花開耶姫の産屋の火中出産、海幸彦山幸彦の神話。",
      reviewStatus: "reviewed",
    },
    {
      id: "takachiho-official",
      kind: "modern-reference",
      title: "高千穂神社 公式由緒",
      publisher: "高千穂神社",
      url: "https://takachiho-kanko.info/sightseeing/detail.php?log=1336609995",
      retrievedAt: "2026-10-05",
      locator: "高千穂郷八十八社総社、瓊瓊杵尊・木花開耶姫命を主祭神とする由緒",
      reviewStatus: "reviewed",
    },
    {
      id: "udo-jingu-official",
      kind: "modern-reference",
      title: "鵜戸神宮 公式由緒",
      publisher: "鵜戸神宮",
      url: "https://www.udojingu.com/",
      retrievedAt: "2026-10-05",
      locator: "「由緒」日南海岸鵜戸崎の洞窟、主祭神・鵜葺草葺不合命の御誕生地、お乳岩",
      reviewStatus: "reviewed",
    },
    {
      id: "aoshima-official",
      kind: "modern-reference",
      title: "青島神社 公式由緒",
      publisher: "青島神社",
      url: "https://aoshima-jinja.jp/",
      retrievedAt: "2026-10-05",
      locator: "「由緒」山幸彦（彦火火出見命）・豊玉姫命・塩筒大神、鬼の洗濯板に囲まれた神域",
      reviewStatus: "reviewed",
    },
    {
      id: "kirishima-official",
      kind: "modern-reference",
      title: "霧島神宮 公式由緒",
      publisher: "霧島神宮",
      url: "https://kirishimajingu.or.jp/",
      retrievedAt: "2026-10-05",
      locator: "「由緒」高千穂峰山頂（脊門丘）から遷座の歴史、天孫瓊瓊杵尊を祀る大社",
      reviewStatus: "reviewed",
    },
    {
      id: "sazareishi-shrine-official",
      kind: "modern-reference",
      title: "細石神社 由緒（糸島）",
      publisher: "糸島市",
      url: "https://www.city.itoshima.lg.jp/",
      retrievedAt: "2026-10-05",
      locator: "木花之佐久夜毘売と石長比売を祀る古社伝承",
      reviewStatus: "reviewed",
    },
    {
      id: "miyazaki-jingu-official",
      kind: "modern-reference",
      title: "宮崎神宮 公式由緒",
      publisher: "宮崎神宮",
      url: "https://miyazakijingu.or.jp/",
      retrievedAt: "2026-10-05",
      locator: "「御由緒」神武天皇（神日本磐余彦尊）を祀る宮崎の古社",
      reviewStatus: "reviewed",
    },
  ],
  viewpoints: [
    {
      id: "tenson-lineage-view",
      kind: "source",
      label: "天孫三代・日向系譜",
      description: "ニニギ、ホオリ（山幸彦）、ウガヤフキアエズの天孫三代と神武天皇への直系系譜を見る。",
    },
    {
      id: "hyuga-sacred-landscape-view",
      kind: "analytical",
      label: "日向山岳・海岸聖地ネットワーク",
      description: "高千穂・霧島の山岳降臨地と、日南海岸（青島・鵜戸）の海洋神話空間の配置を見る。",
    },
  ],
  entities: [
    { id: "ninigi-no-mikoto", kind: "deity", label: "瓊瓊杵尊", aliases: ["ニニギ", "天津彦彦火瓊瓊杵尊"] },
    { id: "konohanasakuya-hime", kind: "deity", label: "木花之佐久夜毘売", aliases: ["コノハナサクヤヒメ", "木花開耶姫命"] },
    { id: "iwanaga-hime", kind: "deity", label: "石長比売", aliases: ["イワナガヒメ", "磐長姫命"] },
    { id: "hoori-no-mikoto", kind: "deity", label: "彦火火出見尊", aliases: ["山幸彦", "ホオリ", "火折尊"] },
    { id: "toyotama-hime", kind: "deity", label: "豊玉毘売命", aliases: ["トヨタマヒメ", "豊玉姫"] },
    { id: "ugayafukiaezu-no-mikoto", kind: "deity", label: "鵜葺草葺不合尊", aliases: ["ウガヤフキアエズ", "鸕鷀草葺不合命"] },
    { id: "tamayori-hime", kind: "deity", label: "玉依毘売命", aliases: ["タマヨリヒメ", "玉依姫"] },
    { id: "kamuyamato-iwarebiko", kind: "person", label: "神武天皇", aliases: ["神倭伊波礼毘古命", "イワレビコ"] },
    {
      id: "sazareishi-shrine",
      kind: "place",
      label: "細石神社",
      aliases: ["細石神社", "糸島 細石神社"],
      description: "福岡県糸島市三雲。コノハナサクヤヒメとイワナガヒメの姉妹神を祀る古社で、平原遺跡・三雲南小路遺跡の至近に鎮座。",
      coordinates: { latitude: 33.536993, longitude: 130.242402 },
    },
    {
      id: "takasu-shrine",
      kind: "place",
      label: "高祖神社",
      aliases: ["高祖神社", "糸島 高祖神社"],
      description: "福岡県糸島市高祖。高祖山山麓に位置し、天孫ニニギノミコトやヒコホホデミ尊を主祭神として祀る怡土郡の古大社。",
      coordinates: { latitude: 33.544758, longitude: 130.260386 },
    },
    {
      id: "takachiho-shrine",
      kind: "place",
      label: "高千穂神社",
      aliases: ["日向 高千穂神社", "高千穂郷総社", "高千穂神社"],
      description: "宮崎県西臼杵郡高千穂町大字三田井。天孫ニニギノミコトが降臨したとされる槵触の峰を控え、高千穂郷八十八社の総社として信仰される古社。",
      coordinates: { latitude: 32.7058, longitude: 131.3039 },
    },
    {
      id: "amanoyasu-kawara",
      kind: "place",
      label: "天岩戸神社・天安河原",
      aliases: ["天安河原", "天岩戸神社", "天岩戸神社・天安河原"],
      description: "宮崎県西臼杵郡高千穂町岩戸。天照大御神の岩戸隠れの舞台となった仰慕ヶ窟（ぎょうぼがいわや）と、八百万の神が集い神議りを行った河原。",
      coordinates: { latitude: 32.7336, longitude: 131.3533 },
    },
    {
      id: "kirishima-jingu",
      kind: "place",
      label: "霧島神宮",
      aliases: ["薩摩 霧島神宮", "高千穂峰 霧島神宮", "霧島神宮"],
      description: "鹿児島県霧島市霧島田口。天孫降臨の霊峰・高千穂峰を背後に控え、ニニギノミコトを主祭神として火山の噴火と共生してきた南九州屈指の大社。",
      coordinates: { latitude: 31.8581, longitude: 130.8694 },
    },
    {
      id: "aoshima-shrine",
      kind: "place",
      label: "青島神社",
      aliases: ["日向 青島神社", "鬼の洗濯板 青島", "青島神社"],
      description: "宮崎県宮崎市青島。日向灘に浮かぶ波状岩『鬼の洗濯板』に囲まれた島。海神宮（綿津見宮）から帰還した山幸彦（ホオリ）が上陸したとされる聖地。",
      coordinates: { latitude: 31.8053, longitude: 131.4747 },
    },
    {
      id: "udo-jingu",
      kind: "place",
      label: "鵜戸神宮",
      aliases: ["日南 鵜戸神宮", "鵜戸山", "鵜戸神宮"],
      description: "宮崎県日南市大字宮浦。日南海岸の太平洋を望む海食洞内に社殿が鎮座。豊玉姫がウガヤフキアエズ尊を出産した産殿伝承とお乳岩が残る。",
      coordinates: { latitude: 31.6508, longitude: 131.4672 },
    },
    {
      id: "miyazaki-jingu",
      kind: "place",
      label: "宮崎神宮",
      aliases: ["日向 宮崎神宮", "神武天皇宮崎宮", "宮崎神宮"],
      description: "宮崎県宮崎市神宮。神武天皇（イワレビコ）が東征前に都とした宮崎宮の伝承地に鎮座。大淀川流域の日向平野における政治・祭祀の拠点。",
      coordinates: { latitude: 31.9367, longitude: 131.4244 },
    },
  ],
  assertions: [
    {
      id: "hyuga-001",
      subjectId: "ninigi-no-mikoto",
      predicate: "parent_of",
      objectId: "hoori-no-mikoto",
      relationFamily: "genealogy",
      nature: "source-statement",
      viewpointIds: ["tenson-lineage-view"],
      sourceIds: ["kojiki-tenson-hyuga", "nihon-shoki-tenson-hyuga"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "hyuga-002",
      subjectId: "konohanasakuya-hime",
      predicate: "parent_of",
      objectId: "hoori-no-mikoto",
      relationFamily: "genealogy",
      nature: "source-statement",
      viewpointIds: ["tenson-lineage-view"],
      sourceIds: ["kojiki-tenson-hyuga", "nihon-shoki-tenson-hyuga"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "hyuga-003",
      subjectId: "hoori-no-mikoto",
      predicate: "parent_of",
      objectId: "ugayafukiaezu-no-mikoto",
      relationFamily: "genealogy",
      nature: "source-statement",
      viewpointIds: ["tenson-lineage-view"],
      sourceIds: ["kojiki-tenson-hyuga", "nihon-shoki-tenson-hyuga"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "hyuga-004",
      subjectId: "toyotama-hime",
      predicate: "parent_of",
      objectId: "ugayafukiaezu-no-mikoto",
      relationFamily: "genealogy",
      nature: "source-statement",
      viewpointIds: ["tenson-lineage-view"],
      sourceIds: ["kojiki-tenson-hyuga", "nihon-shoki-tenson-hyuga"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "hyuga-005",
      subjectId: "ugayafukiaezu-no-mikoto",
      predicate: "parent_of",
      objectId: "kamuyamato-iwarebiko",
      relationFamily: "genealogy",
      nature: "source-statement",
      viewpointIds: ["tenson-lineage-view"],
      sourceIds: ["kojiki-tenson-hyuga", "nihon-shoki-tenson-hyuga"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "hyuga-006",
      subjectId: "ninigi-no-mikoto",
      predicate: "enshrined_at",
      objectId: "takachiho-shrine",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["hyuga-sacred-landscape-view"],
      sourceIds: ["takachiho-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "hyuga-007",
      subjectId: "ninigi-no-mikoto",
      predicate: "enshrined_at",
      objectId: "kirishima-jingu",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["hyuga-sacred-landscape-view"],
      sourceIds: ["kirishima-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "hyuga-008",
      subjectId: "konohanasakuya-hime",
      predicate: "enshrined_at",
      objectId: "sazareishi-shrine",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["hyuga-sacred-landscape-view"],
      sourceIds: ["sazareishi-shrine-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "hyuga-009",
      subjectId: "hoori-no-mikoto",
      predicate: "enshrined_at",
      objectId: "aoshima-shrine",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["hyuga-sacred-landscape-view"],
      sourceIds: ["aoshima-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "hyuga-010",
      subjectId: "ugayafukiaezu-no-mikoto",
      predicate: "enshrined_at",
      objectId: "udo-jingu",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["hyuga-sacred-landscape-view"],
      sourceIds: ["udo-jingu-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "hyuga-011",
      subjectId: "kamuyamato-iwarebiko",
      predicate: "enshrined_at",
      objectId: "miyazaki-jingu",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["hyuga-sacred-landscape-view"],
      sourceIds: ["miyazaki-jingu-official", "takachiho-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "hyuga-012",
      subjectId: "hoori-no-mikoto",
      predicate: "enshrined_at",
      objectId: "takasu-shrine",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["hyuga-sacred-landscape-view"],
      sourceIds: ["sazareishi-shrine-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
  ],
  presets: [
    {
      id: "hyuga-mythology-preset",
      label: "天孫降臨・日向神話と海幸山幸",
      lensType: "relationship",
      description:
        "高千穂・霧島の天孫降臨軸と、青島・鵜戸神宮の日南海岸に広がる海幸山幸神話回廊。糸島の細石神社・高祖神社から南九州の神話空間を読み直す。",
      rootEntityIds: ["sazareishi-shrine", "takasu-shrine", "takachiho-shrine"],
      relationFamilies: ["genealogy", "enshrinement", "association"],
      viewpointIds: ["tenson-lineage-view", "hyuga-sacred-landscape-view"],
      expansionDepth: 3,
      mapConnections: [
        {
          id: "tenson-korin-mountain-axis",
          label: "天孫降臨と山岳降臨ライン",
          description:
            "高千穂・天安河原から霧島神宮、そして糸島の細石神社（コノハナサクヤヒメ・イワナガヒメ伝承）を繋ぐ天孫降臨神話の空間軸。",
          displayMode: "line",
          contextEntityIds: ["ninigi-no-mikoto", "konohanasakuya-hime"],
          placeEntityIds: ["takachiho-shrine", "amanoyasu-kawara", "kirishima-jingu", "sazareishi-shrine"],
          pointFocusEntityIds: {
            "takachiho-shrine": "takachiho-shrine",
            "amanoyasu-kawara": "amanoyasu-kawara",
            "kirishima-jingu": "kirishima-jingu",
            "sazareishi-shrine": "sazareishi-shrine",
          },
          assertionIds: ["hyuga-006", "hyuga-007", "hyuga-008"],
          appearance: { color: "#e5a93c", legendLabel: "天孫降臨軸" },
          explorationQuestions: {
            "takachiho-shrine": {
              question: "山深い高千穂峡の地形と槵触の峰は、なぜ古代の神話編纂者たちに天孫降臨の舞台として選ばれたのか？",
              reason: "ニニギノミコトが日向の高千穂の久士布流多気（くしふるのたけ）に降臨したとされる伝承の中心地で、高千穂郷八十八社の総社。",
            },
            "amanoyasu-kawara": {
              question: "岩戸川の渓谷奥深くに位置する天安河原の洞窟祭祀は、縄文・弥生の自然崇拝と記紀神話の劇的な物語をどう結びつけるか？",
              reason: "天照大御神のお隠れに際し八百万の神が集い神議り（かむはかり）を行ったとされる大洞窟。無数の積石が祈りの空間を形成。",
            },
            "kirishima-jingu": {
              question: "日向の高千穂（臼杵）と薩摩大隅の霧島高千穂峰という二つの降臨地伝承は、古代の地域豪族（隼人族等）とヤマト王権の交渉をどう反映しているか？",
              reason: "天孫降臨のもう一つの有力伝承地である霧島連峰・高千穂峰を背後に控え、火山の噴火と再建を繰り返してきた南九州屈指の大社。",
            },
          },
        },
        {
          id: "hyuga-coast-umisachi-yamasachi",
          label: "日向海岸・海幸山幸回廊",
          description:
            "青島・鵜戸神宮の日南海岸から宮崎神宮、そして高祖神社を結ぶ、山幸彦（ホオリ）と豊玉姫の神話・誕生回廊。",
          displayMode: "line",
          contextEntityIds: ["hoori-no-mikoto", "toyotama-hime", "ugayafukiaezu-no-mikoto", "kamuyamato-iwarebiko"],
          placeEntityIds: ["aoshima-shrine", "udo-jingu", "miyazaki-jingu", "takasu-shrine"],
          pointFocusEntityIds: {
            "aoshima-shrine": "aoshima-shrine",
            "udo-jingu": "udo-jingu",
            "miyazaki-jingu": "miyazaki-jingu",
            "takasu-shrine": "takasu-shrine",
          },
          assertionIds: ["hyuga-009", "hyuga-010", "hyuga-011", "hyuga-012"],
          appearance: { color: "#e88062", dashArray: [6, 6], legendLabel: "海幸山幸回廊" },
          explorationQuestions: {
            "aoshima-shrine": {
              question: "日向灘の黒潮の直撃を受ける青島は、海幸山幸神話に見られる南方海洋文化の記憶をどのように現在に伝えているか？",
              reason: "海神宮（綿津見宮）から帰還した山幸彦が上陸したとされる聖地で、鬼の洗濯板と呼ばれる波状岩と亜熱帯植物に囲まれた島。",
            },
            "udo-jingu": {
              question: "波が打ち寄せる海食洞の中に社殿を構える特異な立地は、古代の海洋出産儀礼や海人族の信仰空間とどう共鳴しているか？",
              reason: "日南海岸の絶壁洞窟内に本殿が鎮座。豊玉姫がウガヤフキアエズ命を出産した産殿伝承とお乳岩が今に伝わる。",
            },
            "miyazaki-jingu": {
              question: "大淀川流域の平野部に位置する宮崎神宮は、山岳の高千穂や海岸の鵜戸から瀬戸内航路へ向かう日向の統合拠点をどう示しているか？",
              reason: "神武天皇が東征に出航する前、日向の地で政務を執った宮崎宮の旧跡に鎮座する大社。",
            },
          },
        },
      ],
    },
  ],
});
