import { LensKnowledgePackSchema } from "./schema";

export const ishinFiguresPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "ishin-figures-network",
  version: "0.4.0",
  label: "維新志士の人物・藩・交渉ネットワーク",
  description: "萩の訪問を起点に、長州・薩摩・土佐の人物が交渉・書簡・同盟・教育を介して接続した関係を保持する。",
  status: "draft",
  releasedAt: "2026-09-01",
  sources: [
    { id: "ndl-ryoma-portrait", kind: "modern-reference", title: "坂本竜馬｜近代日本人の肖像", publisher: "国立国会図書館", url: "https://www.ndl.go.jp/portrait/datas/89", retrievedAt: "2026-09-01", locator: "解説", reviewStatus: "reviewed", note: "薩長連合締結への努力と、西郷隆盛・木戸孝允の盟約への立会いを確認する。" },
    { id: "ryoma-alliance-endorsement", kind: "modern-reference", title: "坂本龍馬書簡〈薩長同盟裏書〉", publisher: "高知県立坂本龍馬記念館", url: "https://ryoma-kinenkan.jp/document/", retrievedAt: "2026-09-01", locator: "慶応2年2月5日 木戸孝允宛", reviewStatus: "reviewed", note: "木戸が記した盟約六ヶ条と龍馬の裏書、龍馬の調整役を説明する所蔵品解説。" },
    { id: "ryoma-chofu-exhibition", kind: "modern-reference", title: "企画展 龍馬と長府藩展", publisher: "高知県立坂本龍馬記念館", url: "https://ryoma-kinenkan.jp/exhibition/2024/04/post-22.html", retrievedAt: "2026-09-01", locator: "龍馬の活動拠点、下関", reviewStatus: "reviewed", note: "下関を拠点に木戸孝允・高杉晋作らと連絡した関係を、書簡を中心に紹介する公式展示解説。" },
    { id: "ndl-restoration-people", kind: "modern-reference", title: "維新期の人々｜あの人の直筆", publisher: "国立国会図書館", url: "https://www.ndl.go.jp/jikihitsu/part2/s1_2/", retrievedAt: "2026-09-01", locator: "木戸孝允ほか", reviewStatus: "reviewed", note: "維新期の人物と薩長同盟後の政治活動を、直筆資料と人物解説から確認する。" },
    { id: "hagi-human-development-ishin", kind: "modern-reference", title: "萩のひとづくりが近代日本を動かした", publisher: "萩市", url: "https://www.city.hagi.lg.jp/uploaded/life/62430_583269_misc.pdf", retrievedAt: "2026-09-01", locator: "萩藩校明倫館から松下村塾まで", reviewStatus: "reviewed", note: "明倫館・松下村塾と木戸孝允・高杉晋作らの人材形成を説明する地域文化財資料。" },
    { id: "hagi-takasugi-birthplace", kind: "modern-reference", title: "高杉晋作誕生地", publisher: "萩市観光協会", url: "https://www.hagishi.com/search/detail.php?d=100001", retrievedAt: "2026-09-02", locator: "基本情報・長州藩部隊 奇兵隊 結成", reviewStatus: "reviewed", note: "萩市南古萩町23の誕生地と、明倫館・松下村塾で学んだ経歴を確認。座標は公式ページの地図リンク。" },
    { id: "shimonoseki-takasugi-grave", kind: "modern-reference", title: "高杉晋作｜下関市公式観光サイト", publisher: "下関市観光政策課", url: "https://shimonoseki.travel/shimonosekistory/takasugi/", retrievedAt: "2026-09-02", locator: "東行庵・略年表", reviewStatus: "reviewed", note: "高杉晋作の墓が下関・吉田の東行庵裏山にあることを確認。" },
    { id: "yamaguchi-kouzanji", kind: "modern-reference", title: "功山寺｜公式 山口県観光/旅行サイト", publisher: "山口県観光連盟", url: "https://yamaguchi-tourism.jp/spot/detail_10468.html", retrievedAt: "2026-09-13", locator: "功山寺書院 七卿潜居の間・基本情報", reviewStatus: "reviewed", note: "高杉晋作が功山寺で挙兵し、潜居中の公卿と会談したこと、および下関市長府川端の所在地を確認。座標はOpenStreetMap候補を使用。" },
  ],
  viewpoints: [
    { id: "documented-relations", kind: "source", label: "公的資料で確認できる関係", description: "書簡・所蔵品解説・公的人物解説で確認できる接触と所属。" },
    { id: "travel-expansion", kind: "analytical", label: "萩訪問から広がる人物網", description: "訪問済み地点・人物を起点に、未訪問の人物と地域へ接続する投影。" },
  ],
  entities: [
    { id: "kido-takayoshi", kind: "person", label: "木戸孝允", aliases: ["桂小五郎"] },
    { id: "takasugi-shinsaku", kind: "person", label: "高杉晋作", aliases: ["晋作"] },
    { id: "yoshida-shoin", kind: "person", label: "吉田松陰", aliases: ["松陰"] },
    { id: "sakamoto-ryoma", kind: "person", label: "坂本龍馬", aliases: ["坂本竜馬", "龍馬"] },
    { id: "saigo-takamori", kind: "person", label: "西郷隆盛", aliases: ["西郷吉之助"] },
    { id: "choshu-domain", kind: "polity", label: "長州藩", aliases: ["萩藩"] },
    { id: "satsuma-domain", kind: "polity", label: "薩摩藩", aliases: [] },
    { id: "tosa-domain", kind: "polity", label: "土佐藩", aliases: [] },
    { id: "satcho-alliance", kind: "event", label: "薩長同盟", aliases: ["薩長連合"] },
    { id: "meirinkan", kind: "place", label: "萩藩校明倫館", aliases: ["明倫館"], coordinates: { latitude: 34.4087, longitude: 131.3995 } },
    { id: "shokasonjuku", kind: "place", label: "松下村塾", aliases: [], coordinates: { latitude: 34.417, longitude: 131.4165 } },
    { id: "shimonoseki", kind: "place", label: "下関", aliases: ["長府"] },
    { id: "takasugi-birthplace", kind: "place", label: "高杉晋作誕生地", aliases: ["晋作誕生地"], coordinates: { latitude: 34.411689, longitude: 131.393019 } },
    { id: "takasugi-grave", kind: "place", label: "東行庵・高杉晋作墓", aliases: ["高杉晋作の墓", "東行庵", "東行記念館"], coordinates: { latitude: 34.085844, longitude: 131.071011 } },
    { id: "kouzanji-chofu", kind: "place", label: "功山寺", aliases: ["長府功山寺"], coordinates: { latitude: 33.9960624, longitude: 130.9819937 } },
    { id: "ito-hirobumi", kind: "person", label: "伊藤博文", aliases: ["伊藤俊輔"] },
    { id: "sakurayama-jinja", kind: "place", label: "桜山神社", aliases: ["桜山招魂社"], coordinates: { latitude: 33.955, longitude: 130.925 } },
    { id: "kido-house", kind: "place", label: "木戸孝允旧宅", aliases: [], coordinates: { latitude: 34.4139, longitude: 131.3917 } },
    { id: "ito-house", kind: "place", label: "伊藤博文旧宅", aliases: [], coordinates: { latitude: 34.4172, longitude: 131.4175 } },
    { id: "mitajiri-ochaya", kind: "place", label: "三田尻御茶屋", aliases: [], coordinates: { latitude: 34.0433, longitude: 131.5764 } },
    { id: "chinryutei", kind: "place", label: "枕流亭", aliases: [], coordinates: { latitude: 34.1758, longitude: 131.4722 } },
  ],
  assertions: [
    { id: "ishin-001", subjectId: "kido-takayoshi", predicate: "represented", objectId: "choshu-domain", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["ndl-restoration-people"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-002", subjectId: "saigo-takamori", predicate: "represented", objectId: "satsuma-domain", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["documented-relations"], sourceIds: ["ndl-ryoma-portrait", "ryoma-alliance-endorsement"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-003", subjectId: "sakamoto-ryoma", predicate: "originated_from", objectId: "tosa-domain", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["documented-relations"], sourceIds: ["ndl-ryoma-portrait"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-004", subjectId: "kido-takayoshi", predicate: "participated_in", objectId: "satcho-alliance", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["ndl-ryoma-portrait", "ryoma-alliance-endorsement"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-005", subjectId: "saigo-takamori", predicate: "participated_in", objectId: "satcho-alliance", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["documented-relations"], sourceIds: ["ndl-ryoma-portrait", "ryoma-alliance-endorsement"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-006", subjectId: "sakamoto-ryoma", predicate: "mediated_and_attested", objectId: "satcho-alliance", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["ryoma-alliance-endorsement"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-007", subjectId: "sakamoto-ryoma", predicate: "communicated_with", objectId: "kido-takayoshi", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["ryoma-chofu-exhibition", "ryoma-alliance-endorsement"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-008", subjectId: "sakamoto-ryoma", predicate: "communicated_with", objectId: "takasugi-shinsaku", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["ryoma-chofu-exhibition"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-009", subjectId: "sakamoto-ryoma", predicate: "used_base_at", objectId: "shimonoseki", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["ryoma-chofu-exhibition"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-010", subjectId: "takasugi-shinsaku", predicate: "belonged_to", objectId: "choshu-domain", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["hagi-human-development-ishin"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-011", subjectId: "meirinkan", predicate: "educated", objectId: "kido-takayoshi", relationFamily: "influence", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["hagi-human-development-ishin"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-012", subjectId: "meirinkan", predicate: "educated", objectId: "takasugi-shinsaku", relationFamily: "influence", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["hagi-human-development-ishin"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-013", subjectId: "yoshida-shoin", predicate: "led", objectId: "shokasonjuku", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["documented-relations"], sourceIds: ["hagi-human-development-ishin"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-014", subjectId: "shokasonjuku", predicate: "influenced", objectId: "takasugi-shinsaku", relationFamily: "influence", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["hagi-human-development-ishin"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-015", subjectId: "takasugi-shinsaku", predicate: "born_at", objectId: "takasugi-birthplace", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["hagi-takasugi-birthplace"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-016", subjectId: "takasugi-shinsaku", predicate: "buried_at", objectId: "takasugi-grave", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["shimonoseki-takasugi-grave"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-017", subjectId: "takasugi-shinsaku", predicate: "launched_uprising_at", objectId: "kouzanji-chofu", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["yamaguchi-kouzanji"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-018", subjectId: "meirinkan", predicate: "educated", objectId: "ito-hirobumi", relationFamily: "influence", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["hagi-human-development-ishin"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-019", subjectId: "shokasonjuku", predicate: "influenced", objectId: "ito-hirobumi", relationFamily: "influence", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["hagi-human-development-ishin"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-020", subjectId: "takasugi-shinsaku", predicate: "associated_with", objectId: "sakurayama-jinja", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["shimonoseki-takasugi-grave"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-021", subjectId: "kido-takayoshi", predicate: "associated_with", objectId: "kido-house", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["hagi-human-development-ishin"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-022", subjectId: "ito-hirobumi", predicate: "associated_with", objectId: "ito-house", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["hagi-human-development-ishin"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-023", subjectId: "kido-takayoshi", predicate: "associated_with", objectId: "mitajiri-ochaya", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["hagi-human-development-ishin"], confidence: "high", reviewStatus: "reviewed" },
    { id: "ishin-024", subjectId: "kido-takayoshi", predicate: "associated_with", objectId: "chinryutei", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["documented-relations", "travel-expansion"], sourceIds: ["ndl-restoration-people"], confidence: "high", reviewStatus: "reviewed" },
  ],
  presets: [
    {
      id: "ishin-network",
      label: "萩から薩長同盟へ広がる人物網",
      lensType: "relationship",
      description: "桂小五郎を起点に、藩の所属・志士間の連絡・薩長同盟への関与を介して坂本龍馬と西郷隆盛へ広がる。",
      rootEntityIds: ["kido-takayoshi"],
      relationFamilies: ["association", "influence", "historical-context"],
      viewpointIds: ["documented-relations", "travel-expansion"],
      expansionDepth: 6,
      visibleEntityKinds: ["person", "polity", "event", "group"],
      mapConnections: [{
        id: "takasugi-life-geography",
        label: "高杉晋作：萩の誕生地・功山寺の挙兵・下関の墓所",
        description: "萩の誕生地、藩論転換の契機となる挙兵を行った長府功山寺、下関・吉田の墓所を、高杉晋作の生涯と政治行動の地理として接続する。",
        anchorEntityId: "takasugi-shinsaku",
        placeEntityIds: ["takasugi-birthplace", "takasugi-grave", "kouzanji-chofu"],
        assertionIds: ["ishin-015", "ishin-016", "ishin-017"],
      }],
    },
    {
      id: "shoka-sonjuku-action-preset",
      label: "松下村塾門下生と尊攘志士の行動軌跡",
      lensType: "relationship",
      description: "吉田松陰の教育拠点（萩松下村塾）から、高杉晋作の功山寺挙兵・東行庵、桜山神社、木戸・伊藤らの政治拠点へと広がる空間的行動網",
      rootEntityIds: ["shokasonjuku", "yoshida-shoin", "takasugi-shinsaku", "kido-takayoshi", "ito-hirobumi"],
      relationFamilies: ["association", "influence", "historical-context"],
      viewpointIds: ["documented-relations", "travel-expansion"],
      expansionDepth: 4,
      mapConnections: [{
        id: "shoka-sonjuku-action-corridor",
        label: "松下村塾志士の活動拠点回廊",
        description: "萩（松下村塾・誕生地・旧宅）から、下関（功山寺・桜山神社・東行庵）、山口・防府（枕流亭・三田尻）へと展開した志士たちの行動ネットワーク。",
        anchorEntityId: "shokasonjuku",
        contextEntityIds: ["yoshida-shoin", "takasugi-shinsaku", "kido-takayoshi", "ito-hirobumi"],
        placeEntityIds: ["shokasonjuku", "meirinkan", "takasugi-birthplace", "takasugi-grave", "kouzanji-chofu", "sakurayama-jinja", "kido-house", "ito-house", "mitajiri-ochaya", "chinryutei"],
        assertionIds: ["ishin-013", "ishin-015", "ishin-016", "ishin-017", "ishin-018", "ishin-020", "ishin-021", "ishin-022", "ishin-023", "ishin-024"],
      }],
    },
  ],
});
