import { LensKnowledgePackSchema } from "./schema";

export const izumoKunitsukamiPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "izumo-kunitsukami-network",
  version: "0.1.0",
  label: "出雲神話・大国主と国津神ネットワーク",
  description:
    "大己貴命（オオクニヌシ）・少彦名命の国作り、出雲国譲りと大和三輪山の大物主鎮座、そして朝倉・宮島など九州・西日本各地に広がる大己貴伝承の神話空間。",
  status: "active",
  releasedAt: "2026-10-05",
  sources: [
    {
      id: "kojiki-kunitsukami-izumo",
      kind: "classical-text",
      title: "古事記",
      locator: "上巻「大国主神の国作り・稲羽の素菟・出雲の国譲り」",
      note: "大己貴神の国作り、少彦名神との協同、建御雷神との国譲り交渉、事代主神の承諾と美保の青柴垣。",
      reviewStatus: "reviewed",
    },
    {
      id: "nihon-shoki-kunitsukami-izumo",
      kind: "classical-text",
      title: "日本書紀",
      locator: "神代下「第八段 大国主神の幽政と大物主神の三輪山鎮座」",
      note: "国譲りと引き換えに大国主神が要求した天日隅宮（出雲大社）の造営、自らの和魂・幸魂としての大物主神の三輪山鎮座伝承。",
      reviewStatus: "reviewed",
    },
    {
      id: "izumo-taisha-official",
      kind: "modern-reference",
      title: "出雲大社 公式由緒",
      publisher: "出雲大社",
      url: "https://izumooyashiro.jp/",
      retrievedAt: "2026-10-05",
      locator: "「由緒」大国主大神、杵築大社、国譲り神話と幽冥主宰の御神徳",
      reviewStatus: "reviewed",
    },
    {
      id: "miho-shrine-official",
      kind: "modern-reference",
      title: "美保神社 公式由緒",
      publisher: "美保神社",
      url: "http://mihojinja.or.jp/",
      retrievedAt: "2026-10-05",
      locator: "「由緒」事代主神（えびす総本社）・三穂津姫命、青柴垣神事",
      reviewStatus: "reviewed",
    },
    {
      id: "oomiwa-shrine-official",
      kind: "modern-reference",
      title: "大神神社 公式由緒",
      publisher: "大神神社",
      url: "https://oomiwa.or.jp/",
      retrievedAt: "2026-10-05",
      locator: "「由緒」日本最古の神社、三輪山をご神体とし大物主大神（大国主の和魂）を祀る",
      reviewStatus: "reviewed",
    },
    {
      id: "chikuzen-onamuchi-origin-izumo",
      kind: "modern-reference",
      title: "大己貴神社 由緒（朝倉）",
      publisher: "筑前町",
      url: "https://www.town.chikuzen.fukuoka.jp/",
      retrievedAt: "2026-10-05",
      locator: "大国主命を祀る日本最古級の神社伝承、三輪の地名",
      reviewStatus: "reviewed",
    },
    {
      id: "minagi-shrine-origin-izumo",
      kind: "modern-reference",
      title: "美奈宜神社 由緒（朝倉）",
      publisher: "朝倉市",
      url: "https://www.city.asakura.lg.jp/",
      retrievedAt: "2026-10-05",
      locator: "大己貴命・事代主命・素戔嗚尊を祀る由緒",
      reviewStatus: "reviewed",
    },
    {
      id: "itsukushima-official-izumo",
      kind: "modern-reference",
      title: "厳島神社 公式由緒",
      publisher: "厳島神社",
      url: "https://www.itsukushimajinja.jp/",
      retrievedAt: "2026-10-05",
      locator: "宗像三女神を祀る瀬戸内海随一の大社と大聖院の神仏習合",
      reviewStatus: "reviewed",
    },
  ],
  viewpoints: [
    {
      id: "izumo-kuniyuzuri-view",
      kind: "source",
      label: "出雲国譲りと幽政",
      description: "オオクニヌシ・コトシロヌシの国譲りと、出雲大社（天日隅宮）の造営伝承を見る。",
    },
    {
      id: "kunitsukami-dispersion-view",
      kind: "analytical",
      label: "大己貴信仰の西日本展開",
      description: "朝倉の大己貴神社、宮島、大和三輪山の大神神社へと連なる国津神ネットワークの地理的配置を見る。",
    },
  ],
  entities: [
    { id: "ookuninushi", kind: "deity", label: "大国主大神", aliases: ["オオクニヌシ", "大己貴命", "大名持", "大穴牟遅神"] },
    { id: "kotoshironushi", kind: "deity", label: "事代主神", aliases: ["コトシロヌシ", "恵比寿神", "八重事代主命"] },
    { id: "oomononushi", kind: "deity", label: "大物主大神", aliases: ["オオモノヌシ", "三輪明神", "大国主の和魂"] },
    { id: "sukunanikona", kind: "deity", label: "少彦名命", aliases: ["スクナビコナ", "常世神"] },
    {
      id: "onamuchi-shrine",
      kind: "place",
      label: "大己貴神社",
      aliases: ["大己貴神社", "朝倉 大己貴神社", "大己貴神社（三輪）"],
      description: "福岡県朝倉郡筑前町弥永。日本最古の大己貴神社と称され、神功皇后が三韓征伐に際し大己貴神を祀って戦勝を祈願したとされる古社。",
      coordinates: { latitude: 33.4434996, longitude: 130.6540467 },
    },
    {
      id: "minagi-hayashida",
      kind: "place",
      label: "美奈宜神社",
      aliases: ["美奈宜神社", "朝倉 美奈宜神社", "美奈宜神社（林田）"],
      description: "福岡県朝倉市林田。大己貴命・事代主命・素戔嗚尊を祀る延喜式内名神大社。神功皇后ゆかりの古社。",
      coordinates: { latitude: 33.3742878, longitude: 130.6736592 },
    },
    {
      id: "itsukushima-shrine",
      kind: "place",
      label: "厳島神社",
      aliases: ["厳島神社", "安芸 厳島神社", "宮島 厳島神社"],
      description: "広島県廿日市市宮島町。安芸国一宮。海上に浮かぶ大鳥居と寝殿造社殿で世界遺産に登録。瀬戸内海交通の要衝で宗像三女神を祀る。",
      coordinates: { latitude: 34.2959, longitude: 132.3197 },
    },
    {
      id: "izumo-taisha",
      kind: "place",
      label: "出雲大社",
      aliases: ["出雲大社", "杵築大社", "出雲大社（島根）"],
      description: "島根県出雲市大社町杵築東。国譲り神話において大国主大神が『幽（かくり）の世界』を司るために造営された天日隅宮の起源を持つ、出雲国一宮。",
      coordinates: { latitude: 35.4014, longitude: 132.6856 },
    },
    {
      id: "inasa-no-hama",
      kind: "place",
      label: "稲佐の浜",
      aliases: ["稲佐の浜", "出雲 稲佐の浜", "国譲り 稲佐の浜"],
      description: "島根県出雲市大社町修理免。建御雷神と大国主神が国譲りの談判を行った神話の舞台。旧暦10月の神在月には全国の八百万の神を迎える神迎神事の浜。",
      coordinates: { latitude: 35.3975, longitude: 132.6739 },
    },
    {
      id: "miho-shrine",
      kind: "place",
      label: "美保神社",
      aliases: ["美保神社", "美保関 美保神社", "えびす総本社 美保神社"],
      description: "島根県松江市美保関町美保関。大国主神の第一の御子神・事代主神と三穂津姫命を祀り、全国のえびす神社の総本社。国譲りの和協と海上交通の守護神。",
      coordinates: { latitude: 35.5606, longitude: 133.2842 },
    },
    {
      id: "oomiwa-shrine",
      kind: "place",
      label: "大神神社",
      aliases: ["大神神社", "大和三輪山 大神神社", "三輪明神"],
      description: "奈良県桜井市三輪。本殿を持たず三輪山をご神体とする日本最古の神社。大国主神自らの和魂である大物主大神を祀り、大和の国家守護神として君臨。",
      coordinates: { latitude: 34.5306, longitude: 135.8525 },
    },
    {
      id: "kamosu-shrine",
      kind: "place",
      label: "神魂神社",
      aliases: ["神魂神社", "出雲 神魂神社", "大庭 神魂神社"],
      description: "島根県松江市大庭町。天穂日命が降臨して創祀したと伝わり、現存日本最古の大社造本殿（国宝）を有する古社。出雲国造の私祭の場。",
      coordinates: { latitude: 35.4269, longitude: 133.0847 },
    },
  ],
  assertions: [
    {
      id: "izumo-001",
      subjectId: "ookuninushi",
      predicate: "parent_of",
      objectId: "kotoshironushi",
      relationFamily: "genealogy",
      nature: "source-statement",
      viewpointIds: ["izumo-kuniyuzuri-view"],
      sourceIds: ["kojiki-kunitsukami-izumo"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "izumo-002",
      subjectId: "ookuninushi",
      predicate: "enshrined_at",
      objectId: "izumo-taisha",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["izumo-kuniyuzuri-view"],
      sourceIds: ["izumo-taisha-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "izumo-003",
      subjectId: "ookuninushi",
      predicate: "associated_with",
      objectId: "inasa-no-hama",
      relationFamily: "association",
      nature: "source-statement",
      viewpointIds: ["izumo-kuniyuzuri-view"],
      sourceIds: ["kojiki-kunitsukami-izumo"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "izumo-004",
      subjectId: "kotoshironushi",
      predicate: "enshrined_at",
      objectId: "miho-shrine",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["izumo-kuniyuzuri-view"],
      sourceIds: ["miho-shrine-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "izumo-005",
      subjectId: "oomononushi",
      predicate: "enshrined_at",
      objectId: "oomiwa-shrine",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["kunitsukami-dispersion-view"],
      sourceIds: ["oomiwa-shrine-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "izumo-006",
      subjectId: "ookuninushi",
      predicate: "enshrined_at",
      objectId: "onamuchi-shrine",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["kunitsukami-dispersion-view"],
      sourceIds: ["chikuzen-onamuchi-origin-izumo"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "izumo-007",
      subjectId: "kotoshironushi",
      predicate: "enshrined_at",
      objectId: "minagi-hayashida",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["kunitsukami-dispersion-view"],
      sourceIds: ["minagi-shrine-origin-izumo"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "izumo-008",
      subjectId: "ookuninushi",
      predicate: "associated_with",
      objectId: "kamosu-shrine",
      relationFamily: "association",
      nature: "reviewed-reference",
      viewpointIds: ["izumo-kuniyuzuri-view"],
      sourceIds: ["izumo-taisha-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "izumo-009",
      subjectId: "ookuninushi",
      predicate: "associated_with",
      objectId: "itsukushima-shrine",
      relationFamily: "association",
      nature: "reviewed-reference",
      viewpointIds: ["kunitsukami-dispersion-view"],
      sourceIds: ["itsukushima-official-izumo"],
      confidence: "medium",
      reviewStatus: "reviewed",
    },
  ],
  presets: [
    {
      id: "izumo-kunitsukami-preset",
      label: "出雲国譲りと大国主系譜",
      lensType: "relationship",
      description:
        "出雲大社・稲佐の浜・美保神社の国譲り神話軸と、朝倉・宮島・大和三輪山を結ぶ大己貴命（オオクニヌシ）信仰の西日本伝播ネットワーク。",
      rootEntityIds: ["onamuchi-shrine", "minagi-hayashida", "izumo-taisha"],
      relationFamilies: ["genealogy", "enshrinement", "association"],
      viewpointIds: ["izumo-kuniyuzuri-view", "kunitsukami-dispersion-view"],
      expansionDepth: 3,
      mapConnections: [
        {
          id: "izumo-core-kuniyuzuri-line",
          label: "出雲大社・国譲り神話軸",
          description:
            "出雲大社、国譲りの舞台・稲佐の浜、事代主神の美保神社、現存最古の大社造・神魂神社を結ぶ出雲本国の信仰中心軸。",
          displayMode: "line",
          contextEntityIds: ["ookuninushi", "kotoshironushi"],
          placeEntityIds: ["izumo-taisha", "inasa-no-hama", "miho-shrine", "kamosu-shrine"],
          pointFocusEntityIds: {
            "izumo-taisha": "izumo-taisha",
            "inasa-no-hama": "inasa-no-hama",
            "miho-shrine": "miho-shrine",
            "kamosu-shrine": "kamosu-shrine",
          },
          assertionIds: ["izumo-002", "izumo-003", "izumo-004", "izumo-008"],
          appearance: { color: "#9b72cf", legendLabel: "出雲国譲り軸" },
          explorationQuestions: {
            "izumo-taisha": {
              question: "なぜ出雲の大国主大神は『目に見えぬ幽（かくり）の世界』を司る神とされ、天津神（伊勢）と二分される権威を持ったのか？",
              reason: "国譲り神話において大国主神が自らの住まいとして要求した壮大な神殿（天日隅宮）を起源とし、全国の神々が集う国津神の総本山。",
            },
            "inasa-no-hama": {
              question: "日本海に面する稲佐の浜の砂浜は、大陸・朝鮮半島からの使者や航海者たちを迎える玄関口としての記憶をどう宿しているか？",
              reason: "建御雷神（タケミカヅチ）が剣の切先にあぐらをかいて大国主に国譲りを迫った神話の舞台。旧暦10月には全国の神々を迎える神迎神事の場。",
            },
            "miho-shrine": {
              question: "島根半島の東端・美保関に位置する美保神社は、北前船や古代日本海・瀬戸内海交通の守護神としてどのように大社と対をなすか？",
              reason: "大国主の第一の御子神・事代主神（恵比寿神の総本宮）を祀る。国譲りに同意したあと海に青柴垣を作って隠れた神話地。",
            },
            "kamosu-shrine": {
              question: "出雲大社の国造家（千家・北島）が古く私祭を行った神魂神社は、大社造の建築原型と古代出雲の祭祀権の変遷をどう伝えているか？",
              reason: "天穂日命（出雲国造の祖）が降臨したと伝わり、現存日本最古の大社造本殿（国宝・室町時代再建）を有する古社。",
            },
          },
        },
        {
          id: "kunitsukami-western-network",
          label: "大己貴（オオクニヌシ）西日本伝播回廊",
          description:
            "朝倉の大己貴神社・美奈宜神社から、安芸・厳島神社、大和・大神神社、そして出雲大社を結ぶ、国津神信仰の広域ネットワーク。",
          displayMode: "line",
          contextEntityIds: ["ookuninushi", "oomononushi", "kotoshironushi"],
          placeEntityIds: ["onamuchi-shrine", "minagi-hayashida", "itsukushima-shrine", "oomiwa-shrine", "izumo-taisha"],
          pointFocusEntityIds: {
            "onamuchi-shrine": "onamuchi-shrine",
            "minagi-hayashida": "minagi-hayashida",
            "itsukushima-shrine": "itsukushima-shrine",
            "oomiwa-shrine": "oomiwa-shrine",
            "izumo-taisha": "izumo-taisha",
          },
          assertionIds: ["izumo-002", "izumo-005", "izumo-006", "izumo-007", "izumo-009"],
          appearance: { color: "#c2884a", dashArray: [6, 6], legendLabel: "大己貴信仰回廊" },
          explorationQuestions: {
            "oomiwa-shrine": {
              question: "大和盆地の東南を扼する三輪山の大物主信仰は、出雲の神が大和王権の最高守護神として国家祭祀に組み込まれた歴史をどう語るか？",
              reason: "本殿を設けず三輪山をご神体とする日本最古の神社の一つで、大国主神の『幸魂・奇魂（和魂）』である大物主大神を祀る。",
            },
          },
        },
      ],
    },
  ],
});
