import { LensKnowledgePackSchema } from "./schema";

export const jinguKogoLegendPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "jingu-kogo-legend-network",
  version: "0.1.0",
  label: "神功皇后伝承と古代筑紫・八幡信仰回廊",
  description:
    "仲哀天皇の橿日宮崩御と沙庭神託、住吉三神・宗像三女神の加護による海原渡航、応神天皇（八幡大神）の御降誕（宇美）と、香椎・筥崎・朝倉・関門・宇佐を結ぶ古代王権祭祀回廊。",
  status: "active",
  releasedAt: "2026-10-05",
  sources: [
    {
      id: "kojiki-chuai-jingu",
      kind: "classical-text",
      title: "古事記",
      locator: "中巻「仲哀天皇・神功皇后」",
      note: "筑紫の橿日宮における神託、熊襲親征、住吉三神の教示による海原渡航と宇美での応神天皇御降誕の記述。",
      reviewStatus: "reviewed",
    },
    {
      id: "nihon-shoki-jingu",
      kind: "classical-text",
      title: "日本書紀",
      locator: "巻第九「気長足姫尊 神功皇后」",
      note: "仲哀天皇の橿日宮崩御、香椎における沙庭の託宣、松浦での鮎釣り占い、津神・海神の祭祀、朝倉山田邑での軍旅平定。",
      reviewStatus: "reviewed",
    },
    {
      id: "kashii-gu-official",
      kind: "modern-reference",
      title: "香椎宮 由緒",
      publisher: "香椎宮",
      url: "https://kashiigu.com/",
      retrievedAt: "2026-10-05",
      locator: "「由緒」橿日宮の故地、仲哀天皇・神功皇后を祀る官幣大社・勅祭社、不老水伝承",
      reviewStatus: "reviewed",
    },
    {
      id: "umi-hachimangu-official",
      kind: "modern-reference",
      title: "宇美八幡宮 由緒",
      publisher: "宇美八幡宮",
      url: "https://www.umi-hachimangu.or.jp/",
      retrievedAt: "2026-10-05",
      locator: "「由緒」神功皇后が応神天皇を出産した聖地、安産信仰、湯蓋の森・衣掛の森",
      reviewStatus: "reviewed",
    },
    {
      id: "hakozaki-gu-official",
      kind: "modern-reference",
      title: "筥崎宮 由緒",
      publisher: "筥崎宮",
      url: "https://www.hakozakigu.or.jp/",
      retrievedAt: "2026-10-05",
      locator: "「由緒」筑前国一之宮、日本三大八幡宮、応神天皇の胞衣を納めた筥松",
      reviewStatus: "reviewed",
    },
    {
      id: "usa-jingu-official",
      kind: "modern-reference",
      title: "宇佐神宮 公式解説",
      publisher: "宇佐神宮",
      url: "http://www.usajinguu.com/",
      retrievedAt: "2026-10-05",
      locator: "「御祭神」一之御殿（八幡大神）・二之御殿（比売大神）・三之御殿（神功皇后）",
      reviewStatus: "reviewed",
    },
    {
      id: "iminomiya-official",
      kind: "modern-reference",
      title: "忌宮神社 由緒",
      publisher: "忌宮神社",
      url: "http://www.iminomiya-jinjya.or.jp/",
      retrievedAt: "2026-10-05",
      locator: "「御由緒」長門豊浦宮跡、仲哀天皇・神功皇后滞在と鬼石・数番踊り伝承",
      reviewStatus: "reviewed",
    },
    {
      id: "nagato-sumiyoshi-official",
      kind: "modern-reference",
      title: "長門国住吉神社 由緒",
      publisher: "長門国住吉神社",
      url: "https://www.yamaguchi-tourism.com/spot/detail_1231.html",
      retrievedAt: "2026-10-05",
      locator: "「由緒」神功皇后の神託により住吉三神の荒魂を祀る長門国一宮・国宝本殿",
      reviewStatus: "reviewed",
    },
  ],
  viewpoints: [
    {
      id: "jingu-oracle-lineage-view",
      kind: "source",
      label: "神功皇后の神託と八幡系譜",
      description: "仲哀天皇・神功皇后・武内宿禰の王権中枢と、住吉三神・宗像三女神の神託、応神天皇（八幡大神）降誕の系譜を見る。",
    },
    {
      id: "jingu-chikushi-spatial-view",
      kind: "analytical",
      label: "古代筑紫・玄界灘の西征伝承拠点",
      description: "香椎宮（橿日宮）の沙庭、宇美の産殿、筥崎宮・宮地嶽・朝倉（大己貴神社）・長門豊浦宮を結ぶ空間配置を見る。",
    },
  ],
  entities: [
    {
      id: "jingu-kogo",
      kind: "person",
      label: "神功皇后",
      aliases: ["息長帯比売命", "気長足姫尊", "神功皇太后"],
      description: "仲哀天皇の皇后。天皇崩御後に自ら神託を受け、住吉大神や海人族の加護を得て海原を渡り、帰国後に応神天皇を出産。古代日本の軍事・祭祀を主導した巫女的大王。",
    },
    {
      id: "chuai-tenno",
      kind: "person",
      label: "仲哀天皇",
      aliases: ["足仲彦天皇", "帯中日子天皇"],
      description: "第14代天皇。日本武尊の皇子。熊襲征討のため筑紫・橿日宮に行幸するも神託に従わず急逝したとされる。",
    },
    {
      id: "ojin-tenno",
      kind: "deity",
      label: "応神天皇（八幡大神）",
      aliases: ["誉田別命", "八幡大神", "品陀和気命", "応神天皇"],
      description: "第15代天皇。神功皇后の筑紫帰還時に宇美で誕生。『胎中天皇』とも称され、後に武神・国家鎮護神たる八幡大神として宇佐・筥崎に祀られる。",
    },
    {
      id: "takenouchi-no-sukune",
      kind: "person",
      label: "武内宿禰",
      aliases: ["建内宿禰", "宿禰"],
      description: "大和王権の重臣。成務・仲哀・神功・応神・仁徳の五代に仕えた伝説的忠臣。橿日宮での沙庭の審神者を務め、神功皇后の遠征・政務を補佐。",
    },
    {
      id: "sumiyoshi-three-kami",
      kind: "group",
      label: "住吉三神",
      aliases: ["底筒男命", "中筒男命", "表筒男命", "墨江三前大神"],
      description: "イザナギの禊から生まれた航海守護神。神功皇后に渡海の神託を与え、荒魂・和魂として遠征を先導。長門・住吉・博多に祀られる。",
    },
    {
      id: "munakata-triad",
      kind: "group",
      label: "宗像三女神",
      aliases: ["田心姫神", "湍津姫神", "市杵島姫神", "道主貴"],
      description: "玄界灘の国家祭祀神。三韓渡航の海上交通路を掌握する守護神として神功皇后軍を支えた。",
    },
    {
      id: "azumi-isora",
      kind: "deity",
      label: "阿曇磯良",
      aliases: ["磯良神", "安曇磯良", "磯良丸"],
      description: "志賀島の海人族・阿曇氏の始祖的神格。神功皇后の招きに応じ、海底から潮盈珠・潮乾珠をもたらして渡海軍の舵取りを務めた伝説を持つ。",
    },
    {
      id: "kashii-gu",
      kind: "place",
      label: "香椎宮",
      aliases: ["香椎宮", "橿日宮", "福岡 香椎宮"],
      description: "福岡県福岡市東区香椎。仲哀天皇の行宮・橿日宮の故地。神功皇后が沙庭にて神託を受け、三韓征伐を決断した古代王権の最重要祭祀拠点。不老水が遺る。",
      coordinates: { latitude: 33.6601, longitude: 130.4578 },
    },
    {
      id: "umi-hachimangu",
      kind: "place",
      label: "宇美八幡宮",
      aliases: ["宇美八幡宮", "宇美 八幡宮", "糟屋 宇美八幡宮"],
      description: "福岡県糟屋郡宇美町宇美。神功皇后が三韓渡航からの帰途、応神天皇を出産した聖地『宇美』に鎮座する安産信仰の総本社。国の天然記念物『湯蓋の森』『衣掛の森』のクスノキ巨樹が聳える。",
      coordinates: { latitude: 33.5684, longitude: 130.5108 },
    },
    {
      id: "hakozaki-gu",
      kind: "place",
      label: "筥崎宮",
      aliases: ["筥崎宮", "博多 筥崎宮", "筑前国一之宮 筥崎宮"],
      description: "福岡県福岡市東区箱崎。筑前国一之宮・日本三大八幡宮。応神天皇誕生時の胞衣を納めた筥を埋めた『筥松』に由来。蒙古襲来の戦跡としても著名。",
      coordinates: { latitude: 33.6150, longitude: 130.4225 },
    },
    {
      id: "miyajidake-shrine",
      kind: "place",
      label: "宮地嶽神社",
      aliases: ["宮地嶽神社", "福津 宮地嶽神社", "宮地嶽古墳"],
      description: "福岡県福津市宮司元町。息長帯比売命（神功皇后）を主祭神とし、勝村大神・勝頼大神を祀る。渡航祈願の伝承と玄界灘に沈む『光の道』、日本最大級の横穴式石室が共存。",
      coordinates: { latitude: 33.7808, longitude: 130.4853 },
    },
    {
      id: "onamuchi-shrine",
      kind: "place",
      label: "大己貴神社",
      aliases: ["大己貴神社", "朝倉 大己貴神社", "大己貴神社（三輪）"],
      description: "福岡県朝倉郡筑前町弥永。日本最古の大己貴神社と称され、神功皇后が新羅征討に際し大己貴神を祀って戦勝を祈願したとされる古社。",
      coordinates: { latitude: 33.4434996, longitude: 130.6540467 },
    },
    {
      id: "iminomiya-shrine",
      kind: "place",
      label: "忌宮神社",
      aliases: ["忌宮神社", "長府 忌宮神社", "豊浦宮"],
      description: "山口県下関市長府宮の内町。仲哀天皇と神功皇后が滞在した長門豊浦宮の故地。熊襲平定と海原渡航の根拠地であり、境内に『数番踊り』発祥の鬼石が残る。",
      coordinates: { latitude: 33.9961, longitude: 130.9856 },
    },
    {
      id: "sumiyoshi-shrine-nagato",
      kind: "place",
      label: "長門国住吉神社",
      aliases: ["長門国住吉神社", "下関 住吉神社", "長門住吉神社"],
      description: "山口県下関市一の宮住吉。長門国一宮・日本三大住吉。神功皇后が住吉三神の荒魂を祀り、海上交通の鎮護とした古社。国宝本殿（九間社流造）を擁する。",
      coordinates: { latitude: 33.9983, longitude: 130.9525 },
    },
    {
      id: "usa-jingu",
      kind: "place",
      label: "宇佐神宮",
      aliases: ["宇佐神宮", "豊前国一之宮 宇佐神宮", "八幡総本宮 宇佐神宮"],
      description: "大分県宇佐市南宇佐。全国四万余の八幡宮の総本宮。一之御殿に八幡大神（応神天皇）、二之御殿に比売大神、三之御殿に神功皇后を祀る。",
      coordinates: { latitude: 33.5268, longitude: 131.3751 },
    },
    {
      id: "munakata-hetsumiya",
      kind: "place",
      label: "宗像大社 辺津宮",
      aliases: ["宗像大社 辺津宮", "宗像大社", "辺津宮"],
      description: "福岡県宗像市田島。宗像三女神の市杵島姫神を祀る本土の主宮。神功皇后の渡海に際しても航海守護神として加護を与えた玄界灘の最高神域。",
      coordinates: { latitude: 33.831206, longitude: 130.514392 },
    },
  ],
  assertions: [
    {
      id: "jingu-001",
      subjectId: "chuai-tenno",
      predicate: "married_to",
      objectId: "jingu-kogo",
      relationFamily: "genealogy",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-oracle-lineage-view"],
      sourceIds: ["kojiki-chuai-jingu", "nihon-shoki-jingu"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-002",
      subjectId: "jingu-kogo",
      predicate: "gives_birth_to",
      objectId: "ojin-tenno",
      relationFamily: "genealogy",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-oracle-lineage-view"],
      sourceIds: ["kojiki-chuai-jingu", "nihon-shoki-jingu"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-003",
      subjectId: "takenouchi-no-sukune",
      predicate: "associated_with",
      objectId: "jingu-kogo",
      relationFamily: "association",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-oracle-lineage-view"],
      sourceIds: ["kojiki-chuai-jingu", "nihon-shoki-jingu"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-004",
      subjectId: "sumiyoshi-three-kami",
      predicate: "associated_with",
      objectId: "jingu-kogo",
      relationFamily: "association",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-oracle-lineage-view"],
      sourceIds: ["kojiki-chuai-jingu", "nihon-shoki-jingu"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-005",
      subjectId: "munakata-triad",
      predicate: "associated_with",
      objectId: "jingu-kogo",
      relationFamily: "association",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-oracle-lineage-view"],
      sourceIds: ["kojiki-chuai-jingu", "nihon-shoki-jingu"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-006",
      subjectId: "azumi-isora",
      predicate: "associated_with",
      objectId: "jingu-kogo",
      relationFamily: "association",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-oracle-lineage-view"],
      sourceIds: ["nihon-shoki-jingu"],
      confidence: "medium",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-007",
      subjectId: "jingu-kogo",
      predicate: "enshrined_at",
      objectId: "kashii-gu",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-chikushi-spatial-view"],
      sourceIds: ["kashii-gu-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-008",
      subjectId: "ojin-tenno",
      predicate: "enshrined_at",
      objectId: "umi-hachimangu",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-chikushi-spatial-view"],
      sourceIds: ["umi-hachimangu-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-009",
      subjectId: "ojin-tenno",
      predicate: "enshrined_at",
      objectId: "hakozaki-gu",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-chikushi-spatial-view"],
      sourceIds: ["hakozaki-gu-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-010",
      subjectId: "jingu-kogo",
      predicate: "enshrined_at",
      objectId: "miyajidake-shrine",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-chikushi-spatial-view"],
      sourceIds: ["kojiki-chuai-jingu"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-011",
      subjectId: "jingu-kogo",
      predicate: "associated_with",
      objectId: "onamuchi-shrine",
      relationFamily: "ritual",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-chikushi-spatial-view"],
      sourceIds: ["nihon-shoki-jingu"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-012",
      subjectId: "chuai-tenno",
      predicate: "enshrined_at",
      objectId: "iminomiya-shrine",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-chikushi-spatial-view"],
      sourceIds: ["iminomiya-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-013",
      subjectId: "sumiyoshi-three-kami",
      predicate: "enshrined_at",
      objectId: "sumiyoshi-shrine-nagato",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-chikushi-spatial-view"],
      sourceIds: ["nagato-sumiyoshi-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-014",
      subjectId: "ojin-tenno",
      predicate: "enshrined_at",
      objectId: "usa-jingu",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-oracle-lineage-view"],
      sourceIds: ["usa-jingu-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-015",
      subjectId: "jingu-kogo",
      predicate: "enshrined_at",
      objectId: "usa-jingu",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-oracle-lineage-view"],
      sourceIds: ["usa-jingu-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "jingu-016",
      subjectId: "munakata-triad",
      predicate: "enshrined_at",
      objectId: "munakata-hetsumiya",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["jingu-chikushi-spatial-view"],
      sourceIds: ["kojiki-chuai-jingu"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
  ],
  presets: [
    {
      id: "jingu-kogo-legend-preset",
      label: "神功皇后伝承と古代筑紫・八幡起源",
      lensType: "relationship",
      description:
        "橿日宮（香椎宮）での沙庭神託、宇美での応神天皇御降誕、筥崎宮・宮地嶽・朝倉（大己貴神社）を結ぶ、神功皇后の西征・安産・八幡信仰ネットワーク。",
      rootEntityIds: ["jingu-kogo", "kashii-gu", "umi-hachimangu", "hakozaki-gu", "usa-jingu"],
      relationFamilies: ["genealogy", "enshrinement", "association", "ritual"],
      viewpointIds: ["jingu-oracle-lineage-view", "jingu-chikushi-spatial-view"],
      expansionDepth: 3,
      mapConnections: [
        {
          id: "jingu-chikushi-birth-corridor",
          label: "神功皇后・筑紫八幡誕生回廊",
          description:
            "橿日宮（香椎宮）での沙庭神託から、応神天皇御降誕地・宇美八幡宮、胞衣を納めた筥崎宮、渡海祈願の宮地嶽神社、戦勝祈願の大己貴神社を結ぶ筑紫の聖地回廊。",
          displayMode: "line",
          contextEntityIds: ["jingu-kogo", "ojin-tenno", "takenouchi-no-sukune"],
          placeEntityIds: ["kashii-gu", "umi-hachimangu", "hakozaki-gu", "miyajidake-shrine", "onamuchi-shrine"],
          pointFocusEntityIds: {
            "kashii-gu": "kashii-gu",
            "umi-hachimangu": "umi-hachimangu",
            "hakozaki-gu": "hakozaki-gu",
            "miyajidake-shrine": "miyajidake-shrine",
            "onamuchi-shrine": "onamuchi-shrine",
          },
          assertionIds: ["jingu-007", "jingu-008", "jingu-009", "jingu-010", "jingu-011"],
          appearance: { color: "#e88c30", legendLabel: "神功皇后・筑紫回廊" },
          explorationQuestions: {
            "kashii-gu": {
              question: "仲哀天皇の橿日宮（香椎宮）において、神託への反発と天皇崩御、そして神功皇后による沙庭の託宣はどのような古代祭祀の転換点となったか？",
              reason: "仲哀天皇崩御の地であり、神功皇后が自ら審神者・武内宿禰とともに神託を受け、三韓渡航を決意した古代王権の最重要祭祀拠点。",
            },
            "umi-hachimangu": {
              question: "三韓征伐の帰途、神功皇后が応神天皇（八幡大神）を出産した伝承地『宇美』は、なぜ後世に安産・子安信仰の総本社として尊崇されたか？",
              reason: "『産み』が地名由来となった応神天皇御降誕地。境内には国の天然記念物『湯蓋の森』『衣掛の森』などの巨大クスノキ群が神話を今に伝える。",
            },
            "hakozaki-gu": {
              question: "博多湾奥に鎮座する筥崎宮は、応神天皇の胞衣伝承（筥松）と元寇（蒙古襲来）国家鎮護の歴史をどのように重ね合わせてきたか？",
              reason: "筑前国一之宮・日本三大八幡宮。応神天皇誕生時の胞衣を納めた筥を埋めた地に創建され、『敵国降伏』の扁額を掲げる武神・国家鎮護の大社。",
            },
            "miyajidake-shrine": {
              question: "玄界灘の夕陽に向かって真っ直ぐ伸びる『光の道』と国宝巨石古墳を持つ宮地嶽神社は、神功皇后の渡海祈願とどう結びついているか？",
              reason: "息長帯比売命（神功皇后）を主祭神とし、渡海に先立ち宮地岳山頂より祈願した伝承を持つ。日本最大級の横穴式石室古墳を有する古代聖地。",
            },
          },
        },
        {
          id: "jingu-kanmon-usa-route",
          label: "長門豊浦宮・関門・宇佐八幡連絡軸",
          description:
            "仲哀天皇・神功皇后が7年間滞在した長門豊浦宮（忌宮神社）、住吉荒魂を鎮座させた長門住吉神社、そして八幡大神総本宮・宇佐神宮を結ぶ西海道・山陽道結節軸。",
          displayMode: "line",
          contextEntityIds: ["chuai-tenno", "jingu-kogo", "sumiyoshi-three-kami", "ojin-tenno"],
          placeEntityIds: ["iminomiya-shrine", "sumiyoshi-shrine-nagato", "kashii-gu", "usa-jingu"],
          pointFocusEntityIds: {
            "iminomiya-shrine": "iminomiya-shrine",
            "sumiyoshi-shrine-nagato": "sumiyoshi-shrine-nagato",
            "kashii-gu": "kashii-gu",
            "usa-jingu": "usa-jingu",
          },
          assertionIds: ["jingu-012", "jingu-013", "jingu-007", "jingu-014", "jingu-015"],
          appearance: { color: "#d95d39", dashArray: [6, 6], legendLabel: "豊浦・関門・宇佐軸" },
          explorationQuestions: {
            "iminomiya-shrine": {
              question: "関門海峡を扼する長府の豊浦宮（忌宮神社）において、仲哀天皇と神功皇后が熊襲親征と海原渡航の準備に7年間を費やした戦略的理由は何か？",
              reason: "仲哀天皇・神功皇后が滞在した仮宮・豊浦宮の跡地。境内の鬼石や数番踊りなど、異民族・敵対勢力調伏の古代伝承を色濃く残す。",
            },
            "sumiyoshi-shrine-nagato": {
              question: "三韓征伐の凱旋にあたり、神功皇后が住吉三神の荒魂を長門に、和魂を摂津住吉に分祀した祭祀空間の意図はどこにあるか？",
              reason: "長門国一之宮・日本三大住吉。神功皇后の神託により住吉三神の荒魂を祀り、関門海峡の海上交通と国家鎮護を担った古社。国宝本殿を誇る。",
            },
          },
        },
      ],
    },
  ],
});
