import { LensKnowledgePackSchema } from "./schema";

export const marineDeitiesPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "marine-deities-network",
  version: "0.1.0",
  label: "海洋神話・海人族三系統ネットワーク",
  description:
    "イザナギの禊（橘の小門）から生まれた海洋神三系統（宗像三女神・綿津見三神・住吉三神）と、玄界灘・博多湾・瀬戸内海を掌握した古代海人族（宗像氏・阿曇氏・津守氏）の祭祀ネットワーク。",
  status: "active",
  releasedAt: "2026-10-05",
  sources: [
    {
      id: "kojiki-misogi",
      kind: "classical-text",
      title: "古事記",
      locator: "上巻「竺紫の日向の小門の阿波岐原の禊」",
      note: "イザナギの黄泉返り後の禊ぎによって、底津綿津見・中津綿津見・上津綿津見、底筒男・中筒男・表筒男、および天照・月読・須佐之男の三貴子が誕生した記述。",
      reviewStatus: "reviewed",
    },
    {
      id: "nihon-shoki-misogi",
      kind: "classical-text",
      title: "日本書紀",
      locator: "神代上「橘之小門之祓」",
      note: "橘の小門での禊と海神・航海守護神の生成記述。",
      reviewStatus: "reviewed",
    },
    {
      id: "shikaumi-official",
      kind: "modern-reference",
      title: "志賀海神社 由緒",
      publisher: "志賀海神社",
      url: "https://www.shikaumi-jinja.jp/",
      retrievedAt: "2026-10-05",
      locator: "「御由緒」海神の総本社、阿曇氏の祖神、綿津見三神の祭祀",
      reviewStatus: "reviewed",
    },
    {
      id: "sumiyoshi-fukuoka-official",
      kind: "modern-reference",
      title: "筑前国一宮 住吉神社 由緒",
      publisher: "住吉神社",
      url: "https://www.nihondaiichisumiyoshi.jp/",
      retrievedAt: "2026-10-05",
      locator: "「由緒」全国2,129社ある住吉神社の始源、底筒男命・中筒男命・表筒男命",
      reviewStatus: "reviewed",
    },
    {
      id: "miyajidake-official",
      kind: "modern-reference",
      title: "宮地嶽神社 由緒",
      publisher: "宮地嶽神社",
      url: "https://www.miyajidake.or.jp/",
      retrievedAt: "2026-10-05",
      locator: "「由緒」息長帯比売命（神功皇后）・勝村大神・勝頼大神、宮地嶽巨石古墳",
      reviewStatus: "reviewed",
    },
    {
      id: "munakata-taisha-official-marine",
      kind: "modern-reference",
      title: "宗像大社 公式解説",
      publisher: "宗像大社",
      url: "https://munakata-taisha.or.jp/",
      retrievedAt: "2026-10-05",
      locator: "三宮（辺津宮・中津宮・沖津宮）と国家祭祀の歴史",
      reviewStatus: "reviewed",
    },
  ],
  viewpoints: [
    {
      id: "marine-lineages-view",
      kind: "source",
      label: "記紀神話の海洋神系譜",
      description: "イザナギの禊から生まれた綿津見三神・住吉三神・宗像三女神の神話的生成を見る。",
    },
    {
      id: "sea-clans-spatial-view",
      kind: "analytical",
      label: "古代海人族の空間拠点",
      description: "阿曇氏の志賀島、津守氏の博多住吉、宗像氏の玄界灘三宮という古代航路掌握氏族の配置を見る。",
    },
  ],
  entities: [
    { id: "izanagi", kind: "deity", label: "伊弉諾尊", aliases: ["イザナギ", "伊邪那岐命"] },
    { id: "watatsumi-three-kami", kind: "group", label: "綿津見三神", aliases: ["底津綿津見神", "中津綿津見神", "上津綿津見神", "海神"] },
    { id: "sumiyoshi-three-kami", kind: "group", label: "住吉三神", aliases: ["底筒男命", "中筒男命", "表筒男命", "墨江三前大神"] },
    { id: "munakata-triad", kind: "group", label: "宗像三女神", aliases: ["田心姫神", "湍津姫神", "市杵島姫神", "道主貴"] },
    { id: "azumi-clan", kind: "group", label: "阿曇氏", aliases: ["安曇族", "海人族阿曇氏"] },
    { id: "munakata-clan", kind: "group", label: "宗像氏", aliases: ["胸形氏"] },
    { id: "jingu-kogo", kind: "person", label: "神功皇后", aliases: ["息長帯比売命"] },
    {
      id: "munakata-hetsumiya",
      kind: "place",
      label: "宗像大社 辺津宮",
      aliases: ["宗像大社", "辺津宮", "宗像大社 辺津宮"],
      description: "福岡県宗像市田島。宗像三女神の市杵島姫神を祀る本土の主宮。国宝8万点を収蔵する神宝館を併設。",
      coordinates: { latitude: 33.831206, longitude: 130.514392 },
    },
    {
      id: "shikaumi-shrine",
      kind: "place",
      label: "志賀海神社",
      aliases: ["志賀島 志賀海神社", "阿曇氏総本宮", "志賀海神社"],
      description: "福岡県福岡市東区志賀島。全国の綿津見神社の総本宮で海嶽の守護神。海人族・阿曇氏が代々祭祀を司り金印の出土地・志賀島に鎮座。",
      coordinates: { latitude: 33.6692, longitude: 130.3128 },
    },
    {
      id: "sumiyoshi-shrine-chikuzen",
      kind: "place",
      label: "筑前国一宮 住吉神社",
      aliases: ["博多 住吉神社", "住吉神社", "筑前国一宮 住吉神社"],
      description: "福岡県福岡市博多区住吉。全国約2,100社ある住吉神社の始源・日本第一住吉宮。博多湾奥の冷泉津に位置し古来の航海守護神を祀る。",
      coordinates: { latitude: 33.5861, longitude: 130.4142 },
    },
    {
      id: "miyajidake-shrine",
      kind: "place",
      label: "宮地嶽神社",
      aliases: ["福津 宮地嶽神社", "宮地嶽古墳", "宮地嶽神社"],
      description: "福岡県福津市宮司元町。玄界灘へ真っ直ぐ伸びる参道『光の道』と、日本最大級の横穴式石室（国宝巨石古墳）を有する古社。",
      coordinates: { latitude: 33.7808, longitude: 130.4853 },
    },
    {
      id: "munakata-nakatsumiya",
      kind: "place",
      label: "宗像大社 中津宮",
      aliases: ["大島 中津宮", "中津宮", "宗像大社 中津宮"],
      description: "福岡県宗像市大島。玄界灘の大島に鎮座し湍津姫神を祀る。沖ノ島を望む沖津宮遥拝所を擁する中継聖地。",
      coordinates: { latitude: 33.8967, longitude: 130.4285 },
    },
    {
      id: "munakata-okitsumiya",
      kind: "place",
      label: "宗像大社 沖津宮",
      aliases: ["沖ノ島 沖津宮", "沖津宮", "宗像大社 沖津宮"],
      description: "福岡県宗像市沖ノ島。玄界灘の絶海に浮かび田心姫神を祀る。島全体が神域で女人禁制が守られ国宝8万点が出土した『海の正倉院』。",
      coordinates: { latitude: 34.2447, longitude: 130.1039 },
    },
    {
      id: "sakurainoura-futamigaura",
      kind: "place",
      label: "櫻井二見浦",
      aliases: ["糸島 櫻井二見浦", "櫻井神社 夫婦岩", "櫻井二見浦"],
      description: "福岡県糸島市志摩桜井。玄界灘の美しい岩礁景観に夫婦岩が浮かび、伊弉諾尊・伊弉冉尊の神窟伝承を持つ西の夕陽聖地。",
      coordinates: { latitude: 33.6425, longitude: 130.1983 },
    },
  ],
  assertions: [
    {
      id: "marine-001",
      subjectId: "izanagi",
      predicate: "gives_birth_to",
      objectId: "watatsumi-three-kami",
      relationFamily: "genealogy",
      nature: "source-statement",
      viewpointIds: ["marine-lineages-view"],
      sourceIds: ["kojiki-misogi", "nihon-shoki-misogi"],
      confidence: "high",
      reviewStatus: "reviewed",
      note: "橘の小門での禊ぎにおける綿津見三神の誕生記述。",
    },
    {
      id: "marine-002",
      subjectId: "izanagi",
      predicate: "gives_birth_to",
      objectId: "sumiyoshi-three-kami",
      relationFamily: "genealogy",
      nature: "source-statement",
      viewpointIds: ["marine-lineages-view"],
      sourceIds: ["kojiki-misogi", "nihon-shoki-misogi"],
      confidence: "high",
      reviewStatus: "reviewed",
      note: "橘の小門での禊ぎにおける住吉三神の誕生記述。",
    },
    {
      id: "marine-003",
      subjectId: "watatsumi-three-kami",
      predicate: "enshrined_at",
      objectId: "shikaumi-shrine",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["sea-clans-spatial-view"],
      sourceIds: ["shikaumi-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "marine-004",
      subjectId: "azumi-clan",
      predicate: "associated_with",
      objectId: "shikaumi-shrine",
      relationFamily: "association",
      nature: "reviewed-reference",
      viewpointIds: ["sea-clans-spatial-view"],
      sourceIds: ["shikaumi-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "marine-005",
      subjectId: "sumiyoshi-three-kami",
      predicate: "enshrined_at",
      objectId: "sumiyoshi-shrine-chikuzen",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["sea-clans-spatial-view"],
      sourceIds: ["sumiyoshi-fukuoka-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "marine-006",
      subjectId: "munakata-triad",
      predicate: "enshrined_at",
      objectId: "munakata-hetsumiya",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["sea-clans-spatial-view"],
      sourceIds: ["munakata-taisha-official-marine"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "marine-007",
      subjectId: "munakata-triad",
      predicate: "enshrined_at",
      objectId: "munakata-nakatsumiya",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["sea-clans-spatial-view"],
      sourceIds: ["munakata-taisha-official-marine"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "marine-008",
      subjectId: "munakata-triad",
      predicate: "enshrined_at",
      objectId: "munakata-okitsumiya",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["sea-clans-spatial-view"],
      sourceIds: ["munakata-taisha-official-marine"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "marine-009",
      subjectId: "jingu-kogo",
      predicate: "enshrined_at",
      objectId: "miyajidake-shrine",
      relationFamily: "enshrinement",
      nature: "reviewed-reference",
      viewpointIds: ["sea-clans-spatial-view"],
      sourceIds: ["miyajidake-official"],
      confidence: "high",
      reviewStatus: "reviewed",
    },
    {
      id: "marine-010",
      subjectId: "izanagi",
      predicate: "associated_with",
      objectId: "sakurainoura-futamigaura",
      relationFamily: "association",
      nature: "reviewed-reference",
      viewpointIds: ["sea-clans-spatial-view"],
      sourceIds: ["kojiki-misogi"],
      confidence: "medium",
      reviewStatus: "reviewed",
    },
  ],
  presets: [
    {
      id: "marine-deities-preset",
      label: "海洋神話と海人族三系統",
      lensType: "relationship",
      description:
        "宗像三女神（宗像氏）・綿津見三神（阿曇氏）・住吉三神（津守氏）の祭祀軸と、玄界灘から博多湾・糸島に至る海人族の航路掌握ネットワーク。",
      rootEntityIds: ["munakata-hetsumiya", "shikaumi-shrine", "sumiyoshi-shrine-chikuzen"],
      relationFamilies: ["genealogy", "enshrinement", "association"],
      viewpointIds: ["marine-lineages-view", "sea-clans-spatial-view"],
      expansionDepth: 3,
      mapConnections: [
        {
          id: "marine-three-lineages-axis",
          label: "玄界灘・博多湾海人族祭祀ライン",
          description:
            "宗像大社（宗像三女神）・志賀海神社（阿曇氏・綿津見三神）・住吉神社（住吉三神）・宮地嶽神社を結ぶ、古代玄界灘の三大海洋神祭祀ネットワーク。",
          displayMode: "line",
          contextEntityIds: ["watatsumi-three-kami", "sumiyoshi-three-kami", "munakata-triad", "azumi-clan", "jingu-kogo"],
          placeEntityIds: ["munakata-hetsumiya", "shikaumi-shrine", "sumiyoshi-shrine-chikuzen", "miyajidake-shrine"],
          pointFocusEntityIds: {
            "munakata-hetsumiya": "munakata-hetsumiya",
            "shikaumi-shrine": "shikaumi-shrine",
            "sumiyoshi-shrine-chikuzen": "sumiyoshi-shrine-chikuzen",
            "miyajidake-shrine": "miyajidake-shrine",
          },
          assertionIds: ["marine-003", "marine-004", "marine-005", "marine-006", "marine-009"],
          appearance: { color: "#5bb2d6", legendLabel: "海人族三系統" },
          explorationQuestions: {
            "shikaumi-shrine": {
              question: "志賀島の海人祭祀（綿津見三神）は、宗像氏の沖ノ島国家祭祀とどのような役割分担と協調関係にあったか？",
              reason: "海人族・阿曇氏の総本宮であり、古代博多湾・志賀島から玄界灘・ヤマト王権の海上交通路を支えた最重要拠点。",
            },
            "sumiyoshi-shrine-chikuzen": {
              question: "博多湾奥の冷泉津・那の津の航海守護神として鎮座した住吉神社は、遣唐使や対外航路とどう連動したか？",
              reason: "全国約2,000社の住吉神社の始源とされる日本最古の住吉宮で、イザナギの禊から生まれた底筒男・中筒男・表筒男命を祀る。",
            },
            "miyajidake-shrine": {
              question: "宗像地域と博多湾の中間に位置する宮地嶽神社は、神功皇后の西征伝承とどのような地政学的関係を持つか？",
              reason: "玄界灘に沈む夕陽が参道の直線上に並ぶ『光の道』と、日本最大級の巨石石室を持つ宮地嶽古墳が共存する古代聖地。",
            },
          },
        },
        {
          id: "munakata-three-palaces-line",
          label: "宗像三宮・玄界灘神域軸",
          description:
            "本土の辺津宮から玄界灘中継地の大島・中津宮、絶海の孤島・沖ノ島の沖津宮、糸島の二見浦を結ぶ、国家祭祀の直列軸。",
          displayMode: "line",
          contextEntityIds: ["munakata-triad", "munakata-clan", "izanagi"],
          placeEntityIds: ["munakata-hetsumiya", "munakata-nakatsumiya", "munakata-okitsumiya", "sakurainoura-futamigaura"],
          pointFocusEntityIds: {
            "munakata-hetsumiya": "munakata-hetsumiya",
            "munakata-nakatsumiya": "munakata-nakatsumiya",
            "munakata-okitsumiya": "munakata-okitsumiya",
            "sakurainoura-futamigaura": "sakurainoura-futamigaura",
          },
          assertionIds: ["marine-006", "marine-007", "marine-008", "marine-010"],
          appearance: { color: "#68c7bd", dashArray: [6, 6], legendLabel: "宗像神域軸" },
          explorationQuestions: {
            "munakata-nakatsumiya": {
              question: "大島の中津宮は、本土の辺津宮と絶海の沖津宮を中継する実務的・祭祀的結節点としてどう機能したか？",
              reason: "玄界灘に浮かぶ大島に鎮座し湍津姫神を祀る宗像三宮の第二宮。沖ノ島を望む沖津宮遥拝所も併設。",
            },
            "munakata-okitsumiya": {
              question: "遣唐使航路の安全を祈るヤマト王権の国家祭祀において、沖ノ島はなぜ『海の正倉院』と呼ばれるほどの奉納を受けたのか？",
              reason: "島全体が御神体であり、女人禁制が守られた絶海の孤島。4〜9世紀にわたる国宝8万点の古代祭祀遺物が手つかずで出土。",
            },
            "sakurainoura-futamigaura": {
              question: "玄界灘の夕陽を正面に拝する二見浦の磐座信仰は、古代海人たちの死生観や常世国（とこよのくに）信仰とどう繋がっていたか？",
              reason: "伊都国の北西海岸に位置し、伊弉諾尊・伊弉冉尊の神窟伝承を持つ夫婦岩と櫻井神社の聖地景観。",
            },
          },
        },
      ],
    },
  ],
});
