import { LensKnowledgePackSchema } from "./schema";

export const miyajimaMisenSacredLandscapePack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "miyajima-misen-sacred-landscape",
  version: "0.2.0",
  label: "厳島・弥山の祭祀景観",
  description: "島・海・山岳・社寺・現在の登山経路を、確認できる外部資料の範囲で分けて読む。旅行記の観察や古代からの連続性はこのPackで確定しない。",
  status: "draft",
  releasedAt: "2026-09-23",
  sources: [
    {
      id: "miyajima-unesco-ou-v",
      kind: "modern-reference",
      title: "Itsukushima Shinto Shrine",
      publisher: "UNESCO World Heritage Centre",
      url: "https://whc.unesco.org/en/list/776",
      retrievedAt: "2026-09-23",
      locator: "Brief synthesis and criteria (ii), (iv): shrine, sea, Mount Misen, and the forested setting",
      reviewStatus: "reviewed",
    },
    {
      id: "itsukushima-shrine-history",
      kind: "modern-reference",
      title: "御由緒",
      publisher: "嚴島神社",
      url: "https://www.itsukushimajinja.jp/jp/history.html",
      retrievedAt: "2026-09-23",
      locator: "御祭神・御鎮座伝承・海水が差し引きする鎮座地の説明",
      reviewStatus: "reviewed",
      note: "鎮座年と神勅は神社公式の由緒として確認する。独立した同時代史料による歴史的確定とは扱わない。",
    },
    {
      id: "daishoin-about",
      kind: "modern-reference",
      title: "大聖院とは",
      publisher: "宮島弥山 大本山 大聖院",
      url: "https://daisho-in.com/about_daishoin.html",
      retrievedAt: "2026-09-23",
      locator: "真言宗御室派・弥山・三鬼大権現・十一面観世音菩薩の説明",
      reviewStatus: "reviewed",
      note: "空海による806年開基等は寺院公式の由緒として確認し、同時代史料による確定とは分ける。",
    },
    {
      id: "hatsukaichi-misen-map",
      kind: "modern-reference",
      title: "Miyajima Mt.Misen Hiking Map",
      publisher: "廿日市市",
      publishedAt: "2026-03-25",
      url: "https://www.city.hatsukaichi.hiroshima.jp/site/kanko/108984.html",
      retrievedAt: "2026-09-23",
      locator: "紅葉谷・大聖院・大元の三登山コースと弥山山頂周辺",
      reviewStatus: "reviewed",
    },
    {
      id: "itsukushima-auxiliary-shrines",
      kind: "modern-reference",
      title: "境外摂末社",
      publisher: "嚴島神社",
      url: "https://www.itsukushimajinja.jp/jp-sp/setumatusya.html",
      retrievedAt: "2026-09-24",
      locator: "御山神社・滝宮神社・粟島神社・三翁神社の摂末社区分、御祭神、由緒、社殿",
      reviewStatus: "reviewed",
      note: "神社公式が示す現在の摂末社関係と由緒として用いる。鎮座年月不詳の社について、創建年代や古代からの祭祀連続性は確定しない。",
    },
  ],
  viewpoints: [
    {
      id: "miyajima-landscape-setting",
      kind: "source",
      label: "海・島・山と社殿",
      description: "海を前景、弥山を背景とする厳島神社の配置を、文化遺産資料から読む。",
    },
    {
      id: "miyajima-present-enshrinement",
      kind: "source",
      label: "現在の祭祀と施設",
      description: "現在の公式資料が示す祭神・尊格と社寺の関係を見る。古代の神格へ自動的に遡及しない。",
    },
    {
      id: "miyajima-current-access",
      kind: "source",
      label: "現在の登山経路",
      description: "大元コースと大聖院コースを現在の公的案内に基づいて比較する。実際に歩いた経路や歴史的参詣路とは分ける。",
    },
    {
      id: "miyajima-political-patronage",
      kind: "source",
      label: "政治的庇護と社殿構成",
      description: "平清盛による12世紀の造営と、海・山を背景とする社殿構成の関係を見る。",
    },
    {
      id: "miyajima-shrine-history",
      kind: "source",
      label: "摂末社の史的変遷",
      description: "公式由緒に記された参詣・勧請・旧鎮守・移転を、現在の祭神や古代からの連続性とは別の史的出来事として読む。",
    },
  ],
  entities: [
    { id: "miyajima-island", kind: "place", label: "宮島（厳島）", aliases: ["宮島", "厳島", "厳島島"] },
    { id: "mt-misen", kind: "place", label: "弥山", aliases: ["弥山山頂", "宮島弥山"], coordinates: { latitude: 34.2794, longitude: 132.3197 } },
    { id: "itsukushima-shrine", kind: "place", label: "嚴島神社", aliases: ["厳島神社"], coordinates: { latitude: 34.2965274, longitude: 132.3190065 } },
    { id: "omoto-shrine-miyajima", kind: "place", label: "大元神社", aliases: ["宮島の大元神社", "大元公園"], coordinates: { latitude: 34.2952, longitude: 132.3135 } },
    { id: "miyama-shrine-miyajima", kind: "place", label: "御山神社", aliases: ["弥山御山神社"], coordinates: { latitude: 34.27767, longitude: 132.31853 } },
    { id: "takimiya-shrine-miyajima", kind: "place", label: "滝宮神社", aliases: ["隈岡宮"], coordinates: { latitude: 34.2900151, longitude: 132.3194663 } },
    { id: "awashima-shrine-miyajima", kind: "place", label: "粟島神社", aliases: ["粟島さん"], coordinates: { latitude: 34.2934427, longitude: 132.3191408 } },
    { id: "sano-shrine-miyajima", kind: "place", label: "三翁神社", aliases: ["山王社"], coordinates: { latitude: 34.2964235, longitude: 132.3210688 } },
    { id: "daishoin-miyajima", kind: "place", label: "大聖院", aliases: ["宮島弥山 大聖院"], coordinates: { latitude: 34.2940, longitude: 132.3168 } },
    { id: "ichikishimahime", kind: "deity", label: "市杵島姫命", aliases: ["市杵島姫神"] },
    { id: "tagorihime", kind: "deity", label: "田心姫命", aliases: ["田心姫神"] },
    { id: "tagitsuhime", kind: "deity", label: "湍津姫命", aliases: ["湍津姫神"] },
    { id: "sankidaigongen", kind: "deity", label: "三鬼大権現", aliases: ["三鬼さん"] },
    { id: "susanoo-miyajima", kind: "deity", label: "素盞鳴命", aliases: ["素戔嗚尊", "須佐之男命", "スサノオ"] },
    { id: "sukunahikona-miyajima", kind: "deity", label: "少彦名神", aliases: ["少彦名命"] },
    { id: "onamuchi-miyajima", kind: "deity", label: "大己貴命", aliases: ["大己貴神", "大国主神"] },
    { id: "taira-no-kiyomori", kind: "person", label: "平清盛", aliases: ["清盛"] },
    { id: "miyajima-shingon-tradition", kind: "tradition", label: "弥山の真言密教伝統", aliases: ["弥山信仰", "真言密教"] },
    { id: "sea-shrine-mountain-setting", kind: "concept", label: "海・社殿・山の景観構成", aliases: ["海―島―山", "海・島・山"] },
    { id: "twelfth-century-shrine-composition", kind: "concept", label: "12世紀の社殿構成", aliases: ["平安時代の社殿構成"] },
    { id: "takakura-visit-takimiya-1180", kind: "event", label: "高倉上皇の滝宮神社参詣（1180年）", aliases: ["治承4年の滝宮神社参詣"] },
    { id: "awashima-relocation-after-meiji", kind: "event", label: "粟島神社の現在地への移転（明治維新後）", aliases: ["粟島神社移転"] },
    { id: "hie-sanno-enshrinement-miyajima", kind: "event", label: "平清盛による日吉山王の勧請", aliases: ["三翁神社の山王勧請"] },
    { id: "retired-emperor-takakura", kind: "person", label: "高倉上皇", aliases: ["高倉院"] },
    { id: "tosenbo-miyajima", kind: "place", label: "東泉坊", aliases: ["大聖院旧社僧 東泉坊"], description: "嚴島神社公式由緒が粟島神社の旧鎮守先として記す、大聖院の旧社僧。所在地・存続期間はこのPackでは確定しない。" },
    { id: "hie-sanno-tradition", kind: "tradition", label: "日吉山王信仰", aliases: ["日吉山王", "山王信仰"] },
  ],
  assertions: [
    { id: "miyajima-001", subjectId: "miyajima-island", predicate: "contains", objectId: "mt-misen", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["miyajima-landscape-setting"], sourceIds: ["miyajima-unesco-ou-v"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-002", subjectId: "itsukushima-shrine", predicate: "forms_landscape_with", objectId: "mt-misen", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["miyajima-landscape-setting"], sourceIds: ["miyajima-unesco-ou-v"], confidence: "high", reviewStatus: "reviewed", note: "社殿・海・山が一体となる景観構成を示す。信仰対象の歴史的同一性や連続性は主張しない。" },
    { id: "miyajima-003", subjectId: "itsukushima-shrine", predicate: "exemplifies", objectId: "sea-shrine-mountain-setting", relationFamily: "conceptual-comparison", nature: "interpretive-model", viewpointIds: ["miyajima-landscape-setting"], sourceIds: ["miyajima-unesco-ou-v"], confidence: "medium", reviewStatus: "draft", note: "UNESCOの景観記述をResoWorldの比較概念へ投影した分析線。" },
    { id: "miyajima-004", subjectId: "ichikishimahime", predicate: "enshrined_at", objectId: "itsukushima-shrine", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-shrine-history"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-005", subjectId: "tagorihime", predicate: "enshrined_at", objectId: "itsukushima-shrine", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-shrine-history"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-006", subjectId: "tagitsuhime", predicate: "enshrined_at", objectId: "itsukushima-shrine", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-shrine-history"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-007", subjectId: "daishoin-miyajima", predicate: "maintains", objectId: "miyajima-shingon-tradition", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["daishoin-about"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-008", subjectId: "sankidaigongen", predicate: "enshrined_at", objectId: "daishoin-miyajima", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["daishoin-about"], confidence: "high", reviewStatus: "reviewed", note: "大聖院公式が弥山の守護神として祀ると説明する現在の関係。御山神社旧地との歴史的変遷は未確認のため接続しない。" },
    { id: "miyajima-009", subjectId: "omoto-shrine-miyajima", predicate: "current_route_to", objectId: "mt-misen", relationFamily: "route", nature: "reviewed-reference", viewpointIds: ["miyajima-current-access"], sourceIds: ["hatsukaichi-misen-map"], sequence: 1, confidence: "high", reviewStatus: "reviewed", note: "現在案内される大元コース。歴史的・祭祀的経路またはユーザーの実歩行記録とは同一視しない。" },
    { id: "miyajima-010", subjectId: "daishoin-miyajima", predicate: "current_route_to", objectId: "mt-misen", relationFamily: "route", nature: "reviewed-reference", viewpointIds: ["miyajima-current-access"], sourceIds: ["hatsukaichi-misen-map"], sequence: 1, confidence: "high", reviewStatus: "reviewed", note: "現在案内される大聖院コース。歴史的・祭祀的経路またはユーザーの実歩行記録とは同一視しない。" },
    { id: "miyajima-011", subjectId: "taira-no-kiyomori", predicate: "patronized", objectId: "itsukushima-shrine", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-political-patronage"], sourceIds: ["miyajima-unesco-ou-v"], confidence: "high", reviewStatus: "reviewed", note: "UNESCOが現在の景観構成を12世紀の平清盛による造営と関連づける範囲に限定する。" },
    { id: "miyajima-012", subjectId: "itsukushima-shrine", predicate: "preserves_composition_from", objectId: "twelfth-century-shrine-composition", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-political-patronage"], sourceIds: ["miyajima-unesco-ou-v"], confidence: "high", reviewStatus: "reviewed", note: "現存建物の全てが12世紀建立であるとはせず、再建を通じて保存された様式・構成を指す。" },
    { id: "miyajima-013", subjectId: "miyama-shrine-miyajima", predicate: "auxiliary_shrine_of", objectId: "itsukushima-shrine", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-auxiliary-shrines"], confidence: "high", reviewStatus: "reviewed", note: "嚴島神社公式が境外摂社・奥宮として示す現在の制度的関係。" },
    { id: "miyajima-014", subjectId: "takimiya-shrine-miyajima", predicate: "auxiliary_shrine_of", objectId: "itsukushima-shrine", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-auxiliary-shrines"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-015", subjectId: "awashima-shrine-miyajima", predicate: "auxiliary_shrine_of", objectId: "itsukushima-shrine", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-auxiliary-shrines"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-016", subjectId: "sano-shrine-miyajima", predicate: "auxiliary_shrine_of", objectId: "itsukushima-shrine", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-auxiliary-shrines"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-017", subjectId: "ichikishimahime", predicate: "enshrined_at", objectId: "miyama-shrine-miyajima", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-auxiliary-shrines"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-018", subjectId: "tagorihime", predicate: "enshrined_at", objectId: "miyama-shrine-miyajima", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-auxiliary-shrines"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-019", subjectId: "tagitsuhime", predicate: "enshrined_at", objectId: "miyama-shrine-miyajima", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-auxiliary-shrines"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-020", subjectId: "tagitsuhime", predicate: "enshrined_at", objectId: "takimiya-shrine-miyajima", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-auxiliary-shrines"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-021", subjectId: "susanoo-miyajima", predicate: "enshrined_at", objectId: "takimiya-shrine-miyajima", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-auxiliary-shrines"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-022", subjectId: "sukunahikona-miyajima", predicate: "enshrined_at", objectId: "awashima-shrine-miyajima", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-auxiliary-shrines"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-023", subjectId: "onamuchi-miyajima", predicate: "enshrined_at", objectId: "sano-shrine-miyajima", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-auxiliary-shrines"], confidence: "high", reviewStatus: "reviewed", note: "三翁神社の多数の祭神のうち、旅行記で観察された大己貴命との接点を投影する。" },
    { id: "miyajima-024", subjectId: "retired-emperor-takakura", predicate: "participated_in", objectId: "takakura-visit-takimiya-1180", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-shrine-history"], sourceIds: ["itsukushima-auxiliary-shrines"], sequence: 2, historicalTime: { kind: "calendar", label: "治承4年", startYear: 1180, approximate: false }, evidenceBasis: "reported-historical-record", confidence: "high", reviewStatus: "reviewed", note: "嚴島神社公式が『高倉上皇御幸記にある』として紹介する1180年の参詣記録。史料本文の独立検証は今後の課題とする。" },
    { id: "miyajima-025", subjectId: "takakura-visit-takimiya-1180", predicate: "occurred_at", objectId: "takimiya-shrine-miyajima", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-shrine-history"], sourceIds: ["itsukushima-auxiliary-shrines"], sequence: 2, historicalTime: { kind: "calendar", label: "治承4年", startYear: 1180, approximate: false }, evidenceBasis: "reported-historical-record", confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-026", subjectId: "awashima-shrine-miyajima", predicate: "served_as_tutelary_shrine_of", objectId: "tosenbo-miyajima", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-shrine-history"], sourceIds: ["itsukushima-auxiliary-shrines"], sequence: 3, historicalTime: { kind: "named", label: "明治維新以前", precision: "broad-range" }, evidenceBasis: "institutional-tradition", confidence: "high", reviewStatus: "reviewed", note: "公式由緒が記す移転前の関係。現在の制度的帰属とは分離する。" },
    { id: "miyajima-027", subjectId: "awashima-relocation-after-meiji", predicate: "relocated", objectId: "awashima-shrine-miyajima", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-shrine-history"], sourceIds: ["itsukushima-auxiliary-shrines"], sequence: 4, historicalTime: { kind: "named", label: "明治維新後", precision: "broad-range" }, evidenceBasis: "institutional-tradition", confidence: "medium", reviewStatus: "reviewed", note: "公式由緒は『明治維新後』とのみ記すため、特定の移転年は付与しない。" },
    { id: "miyajima-028", subjectId: "taira-no-kiyomori", predicate: "initiated", objectId: "hie-sanno-enshrinement-miyajima", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-shrine-history"], sourceIds: ["itsukushima-auxiliary-shrines"], sequence: 1, historicalTime: { kind: "named", label: "平清盛在世期", precision: "broad-period" }, evidenceBasis: "institutional-tradition", confidence: "high", reviewStatus: "reviewed", note: "公式由緒が平清盛による近江の日吉山王勧請として示す範囲。実施年は確定しない。" },
    { id: "miyajima-029", subjectId: "hie-sanno-enshrinement-miyajima", predicate: "established_at", objectId: "sano-shrine-miyajima", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-shrine-history"], sourceIds: ["itsukushima-auxiliary-shrines"], sequence: 1, historicalTime: { kind: "named", label: "平清盛在世期", precision: "broad-period" }, evidenceBasis: "institutional-tradition", confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-030", subjectId: "hie-sanno-enshrinement-miyajima", predicate: "introduced", objectId: "hie-sanno-tradition", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-shrine-history"], sourceIds: ["itsukushima-auxiliary-shrines"], sequence: 1, historicalTime: { kind: "named", label: "平清盛在世期", precision: "broad-period" }, evidenceBasis: "institutional-tradition", confidence: "high", reviewStatus: "reviewed", note: "三翁神社が『山王社』と呼ばれた由緒を出来事として保持する。現在の社名・祭神との同一視はしない。" },
  ],
  presets: [
    {
      id: "miyajima-sacred-relations",
      label: "厳島・弥山の神域と現在祭祀",
      lensType: "relationship",
      description: "海・社殿・弥山の景観構成と、現在の公式資料で確認できる祭神・尊格を並べる。古代からの連続した神格変遷はまだ描かない。",
      rootEntityIds: ["miyajima-island", "mt-misen", "itsukushima-shrine", "miyama-shrine-miyajima", "takimiya-shrine-miyajima", "awashima-shrine-miyajima", "sano-shrine-miyajima", "daishoin-miyajima"],
      relationFamilies: ["association", "conceptual-comparison", "enshrinement", "historical-context"],
      viewpointIds: ["miyajima-landscape-setting", "miyajima-present-enshrinement"],
      expansionDepth: 3,
      mapConnections: [
        {
          id: "miyajima-auxiliary-shrines",
          label: "嚴島神社と島内摂末社",
          description: "現在の嚴島神社公式が示す摂末社関係を地点として重ねる。創建年代や古代祭祀の連続性を示す線ではない。",
          displayMode: "points",
          anchorEntityId: "itsukushima-shrine",
          contextEntityIds: ["miyajima-island", "mt-misen"],
          placeEntityIds: ["itsukushima-shrine", "miyama-shrine-miyajima", "takimiya-shrine-miyajima", "awashima-shrine-miyajima", "sano-shrine-miyajima"],
          pointFocusEntityIds: {
            "itsukushima-shrine": "itsukushima-shrine",
            "miyama-shrine-miyajima": "miyama-shrine-miyajima",
            "takimiya-shrine-miyajima": "takimiya-shrine-miyajima",
            "awashima-shrine-miyajima": "awashima-shrine-miyajima",
            "sano-shrine-miyajima": "sano-shrine-miyajima",
          },
          assertionIds: ["miyajima-013", "miyajima-014", "miyajima-015", "miyajima-016"],
          appearance: { color: "#d2a85b", legendLabel: "現在の摂末社" },
        },
      ],
    },
    {
      id: "miyajima-current-paths",
      label: "大元・大聖院から弥山への現在経路",
      lensType: "route",
      description: "現在の大元コースと大聖院コースを比較する。旅行記の実歩行Path、歴史的参詣路、祭祀的経路は別の根拠として扱う。",
      rootEntityIds: ["miyajima-island", "mt-misen", "omoto-shrine-miyajima", "daishoin-miyajima"],
      relationFamilies: ["route", "association"],
      viewpointIds: ["miyajima-current-access", "miyajima-landscape-setting"],
      expansionDepth: 2,
      mapConnections: [
        {
          id: "omoto-misen-route",
          label: "大元コース（弥山登山道）",
          description: "大元神社・大元公園から弥山山頂へ至る登山道です。自然林と巨石群を抜ける現在の公的案内経路です。",
          displayMode: "line",
          anchorEntityId: "omoto-shrine-miyajima",
          contextEntityIds: ["miyajima-island"],
          placeEntityIds: ["omoto-shrine-miyajima", "mt-misen"],
          pointFocusEntityIds: {
            "omoto-shrine-miyajima": "omoto-shrine-miyajima",
            "mt-misen": "mt-misen",
          },
          assertionIds: ["miyajima-009"],
          appearance: { color: "#54b2a9", legendLabel: "大元コース" },
        },
        {
          id: "daishoin-misen-route",
          label: "大聖院コース（弥山登山道）",
          description: "真言密教の霊場・大聖院から石段を経て弥山山頂・御山神社へ至る歴史的参詣路・登山道です。",
          displayMode: "line",
          anchorEntityId: "daishoin-miyajima",
          contextEntityIds: ["miyajima-island"],
          placeEntityIds: ["daishoin-miyajima", "mt-misen"],
          pointFocusEntityIds: {
            "daishoin-miyajima": "daishoin-miyajima",
            "mt-misen": "mt-misen",
          },
          assertionIds: ["miyajima-010"],
          appearance: { color: "#c89b5f", legendLabel: "大聖院コース" },
        },
      ],
    },
    {
      id: "miyajima-patronage-and-space",
      label: "平清盛と厳島神社の社殿構成",
      lensType: "relationship",
      description: "平清盛による造営と、再建を経て保持された12世紀の社殿構成を、島の古層祭祀や現在祭神とは分けて見る。",
      rootEntityIds: ["miyajima-island", "itsukushima-shrine", "taira-no-kiyomori"],
      relationFamilies: ["historical-context", "association"],
      viewpointIds: ["miyajima-political-patronage", "miyajima-landscape-setting"],
      expansionDepth: 2,
    },
    {
      id: "miyajima-shrine-history",
      label: "宮島摂末社の史的変遷",
      lensType: "timeline",
      description: "1180年の滝宮神社参詣、三翁神社の日吉山王勧請、粟島神社の旧鎮守関係と明治維新後の移転を、現在祭祀から分けて見る。",
      rootEntityIds: ["takimiya-shrine-miyajima", "awashima-shrine-miyajima", "sano-shrine-miyajima"],
      relationFamilies: ["historical-context"],
      viewpointIds: ["miyajima-shrine-history"],
      expansionDepth: 3,
    },
  ],
});
