import { LensKnowledgePackSchema } from "./schema";

export const miyajimaMisenSacredLandscapePack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "miyajima-misen-sacred-landscape",
  version: "0.1.0",
  label: "厳島・弥山の祭祀景観",
  description: "島・海・山岳・社寺・現在の登山経路を、確認できる外部資料の範囲で分けて読む。旅行記の観察や古代からの連続性はこのPackで確定しない。",
  status: "draft",
  releasedAt: "2026-09-23",
  sources: [
    {
      id: "miyajima-unesco-ou-v",
      kind: "modern-reference",
      title: "Itsukushima Shinto Shrine",
      publisher: "UNESCO World Heritage Centre",
      url: "https://whc.unesco.org/en/list/776",
      retrievedAt: "2026-09-23",
      locator: "Brief synthesis and criteria (ii), (iv): shrine, sea, Mount Misen, and the forested setting",
      reviewStatus: "reviewed",
    },
    {
      id: "itsukushima-shrine-history",
      kind: "modern-reference",
      title: "御由緒",
      publisher: "嚴島神社",
      url: "https://www.itsukushimajinja.jp/jp/history.html",
      retrievedAt: "2026-09-23",
      locator: "御祭神・御鎮座伝承・海水が差し引きする鎮座地の説明",
      reviewStatus: "reviewed",
      note: "鎮座年と神勅は神社公式の由緒として確認する。独立した同時代史料による歴史的確定とは扱わない。",
    },
    {
      id: "daishoin-about",
      kind: "modern-reference",
      title: "大聖院とは",
      publisher: "宮島弥山 大本山 大聖院",
      url: "https://daisho-in.com/about_daishoin.html",
      retrievedAt: "2026-09-23",
      locator: "真言宗御室派・弥山・三鬼大権現・十一面観世音菩薩の説明",
      reviewStatus: "reviewed",
      note: "空海による806年開基等は寺院公式の由緒として確認し、同時代史料による確定とは分ける。",
    },
    {
      id: "hatsukaichi-misen-map",
      kind: "modern-reference",
      title: "Miyajima Mt.Misen Hiking Map",
      publisher: "廿日市市",
      publishedAt: "2026-03-25",
      url: "https://www.city.hatsukaichi.hiroshima.jp/site/kanko/108984.html",
      retrievedAt: "2026-09-23",
      locator: "紅葉谷・大聖院・大元の三登山コースと弥山山頂周辺",
      reviewStatus: "reviewed",
    },
  ],
  viewpoints: [
    {
      id: "miyajima-landscape-setting",
      kind: "source",
      label: "海・島・山と社殿",
      description: "海を前景、弥山を背景とする厳島神社の配置を、文化遺産資料から読む。",
    },
    {
      id: "miyajima-present-enshrinement",
      kind: "source",
      label: "現在の祭祀と施設",
      description: "現在の公式資料が示す祭神・尊格と社寺の関係を見る。古代の神格へ自動的に遡及しない。",
    },
    {
      id: "miyajima-current-access",
      kind: "source",
      label: "現在の登山経路",
      description: "大元コースと大聖院コースを現在の公的案内に基づいて比較する。実際に歩いた経路や歴史的参詣路とは分ける。",
    },
    {
      id: "miyajima-political-patronage",
      kind: "source",
      label: "政治的庇護と社殿構成",
      description: "平清盛による12世紀の造営と、海・山を背景とする社殿構成の関係を見る。",
    },
  ],
  entities: [
    { id: "miyajima-island", kind: "place", label: "宮島（厳島）", aliases: ["宮島", "厳島", "厳島島"] },
    { id: "mt-misen", kind: "place", label: "弥山", aliases: ["弥山山頂", "宮島弥山"] },
    { id: "itsukushima-shrine", kind: "place", label: "嚴島神社", aliases: ["厳島神社"] },
    { id: "omoto-shrine-miyajima", kind: "place", label: "大元神社", aliases: ["宮島の大元神社", "大元公園"] },
    { id: "daishoin-miyajima", kind: "place", label: "大聖院", aliases: ["宮島弥山 大聖院"] },
    { id: "ichikishimahime", kind: "deity", label: "市杵島姫命", aliases: ["市杵島姫神"] },
    { id: "tagorihime", kind: "deity", label: "田心姫命", aliases: ["田心姫神"] },
    { id: "tagitsuhime", kind: "deity", label: "湍津姫命", aliases: ["湍津姫神"] },
    { id: "sankidaigongen", kind: "deity", label: "三鬼大権現", aliases: ["三鬼さん"] },
    { id: "taira-no-kiyomori", kind: "person", label: "平清盛", aliases: ["清盛"] },
    { id: "miyajima-shingon-tradition", kind: "tradition", label: "弥山の真言密教伝統", aliases: ["弥山信仰", "真言密教"] },
    { id: "sea-shrine-mountain-setting", kind: "concept", label: "海・社殿・山の景観構成", aliases: ["海―島―山", "海・島・山"] },
    { id: "twelfth-century-shrine-composition", kind: "concept", label: "12世紀の社殿構成", aliases: ["平安時代の社殿構成"] },
  ],
  assertions: [
    { id: "miyajima-001", subjectId: "miyajima-island", predicate: "contains", objectId: "mt-misen", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["miyajima-landscape-setting"], sourceIds: ["miyajima-unesco-ou-v"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-002", subjectId: "itsukushima-shrine", predicate: "forms_landscape_with", objectId: "mt-misen", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["miyajima-landscape-setting"], sourceIds: ["miyajima-unesco-ou-v"], confidence: "high", reviewStatus: "reviewed", note: "社殿・海・山が一体となる景観構成を示す。信仰対象の歴史的同一性や連続性は主張しない。" },
    { id: "miyajima-003", subjectId: "itsukushima-shrine", predicate: "exemplifies", objectId: "sea-shrine-mountain-setting", relationFamily: "conceptual-comparison", nature: "interpretive-model", viewpointIds: ["miyajima-landscape-setting"], sourceIds: ["miyajima-unesco-ou-v"], confidence: "medium", reviewStatus: "draft", note: "UNESCOの景観記述をResoWorldの比較概念へ投影した分析線。" },
    { id: "miyajima-004", subjectId: "ichikishimahime", predicate: "enshrined_at", objectId: "itsukushima-shrine", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-shrine-history"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-005", subjectId: "tagorihime", predicate: "enshrined_at", objectId: "itsukushima-shrine", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-shrine-history"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-006", subjectId: "tagitsuhime", predicate: "enshrined_at", objectId: "itsukushima-shrine", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["itsukushima-shrine-history"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-007", subjectId: "daishoin-miyajima", predicate: "maintains", objectId: "miyajima-shingon-tradition", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["daishoin-about"], confidence: "high", reviewStatus: "reviewed" },
    { id: "miyajima-008", subjectId: "sankidaigongen", predicate: "enshrined_at", objectId: "daishoin-miyajima", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["miyajima-present-enshrinement"], sourceIds: ["daishoin-about"], confidence: "high", reviewStatus: "reviewed", note: "大聖院公式が弥山の守護神として祀ると説明する現在の関係。御山神社旧地との歴史的変遷は未確認のため接続しない。" },
    { id: "miyajima-009", subjectId: "omoto-shrine-miyajima", predicate: "current_route_to", objectId: "mt-misen", relationFamily: "route", nature: "reviewed-reference", viewpointIds: ["miyajima-current-access"], sourceIds: ["hatsukaichi-misen-map"], sequence: 1, confidence: "high", reviewStatus: "reviewed", note: "現在案内される大元コース。歴史的・祭祀的経路またはユーザーの実歩行記録とは同一視しない。" },
    { id: "miyajima-010", subjectId: "daishoin-miyajima", predicate: "current_route_to", objectId: "mt-misen", relationFamily: "route", nature: "reviewed-reference", viewpointIds: ["miyajima-current-access"], sourceIds: ["hatsukaichi-misen-map"], sequence: 1, confidence: "high", reviewStatus: "reviewed", note: "現在案内される大聖院コース。歴史的・祭祀的経路またはユーザーの実歩行記録とは同一視しない。" },
    { id: "miyajima-011", subjectId: "taira-no-kiyomori", predicate: "patronized", objectId: "itsukushima-shrine", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-political-patronage"], sourceIds: ["miyajima-unesco-ou-v"], confidence: "high", reviewStatus: "reviewed", note: "UNESCOが現在の景観構成を12世紀の平清盛による造営と関連づける範囲に限定する。" },
    { id: "miyajima-012", subjectId: "itsukushima-shrine", predicate: "preserves_composition_from", objectId: "twelfth-century-shrine-composition", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["miyajima-political-patronage"], sourceIds: ["miyajima-unesco-ou-v"], confidence: "high", reviewStatus: "reviewed", note: "現存建物の全てが12世紀建立であるとはせず、再建を通じて保存された様式・構成を指す。" },
  ],
  presets: [
    {
      id: "miyajima-sacred-relations",
      label: "厳島・弥山の神域と現在祭祀",
      lensType: "relationship",
      description: "海・社殿・弥山の景観構成と、現在の公式資料で確認できる祭神・尊格を並べる。古代からの連続した神格変遷はまだ描かない。",
      rootEntityIds: ["miyajima-island", "mt-misen", "itsukushima-shrine", "daishoin-miyajima"],
      relationFamilies: ["association", "conceptual-comparison", "enshrinement", "historical-context"],
      viewpointIds: ["miyajima-landscape-setting", "miyajima-present-enshrinement"],
      expansionDepth: 3,
    },
    {
      id: "miyajima-current-paths",
      label: "大元・大聖院から弥山への現在経路",
      lensType: "route",
      description: "現在の大元コースと大聖院コースを比較する。旅行記の実歩行Path、歴史的参詣路、祭祀的経路は別の根拠として扱う。",
      rootEntityIds: ["miyajima-island", "mt-misen", "omoto-shrine-miyajima", "daishoin-miyajima"],
      relationFamilies: ["route", "association"],
      viewpointIds: ["miyajima-current-access", "miyajima-landscape-setting"],
      expansionDepth: 2,
    },
    {
      id: "miyajima-patronage-and-space",
      label: "平清盛と厳島神社の社殿構成",
      lensType: "relationship",
      description: "平清盛による造営と、再建を経て保持された12世紀の社殿構成を、島の古層祭祀や現在祭神とは分けて見る。",
      rootEntityIds: ["miyajima-island", "itsukushima-shrine", "taira-no-kiyomori"],
      relationFamilies: ["historical-context", "association"],
      viewpointIds: ["miyajima-political-patronage", "miyajima-landscape-setting"],
      expansionDepth: 2,
    },
  ],
});
