import { LensKnowledgePackSchema } from "./schema";

export const munakataOkinoshimaSacredLandscapePack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "munakata-okinoshima-sacred-landscape",
  version: "0.1.0",
  label: "宗像・沖ノ島の祭祀景観",
  description: "沖ノ島祭祀の考古学的期間、国家祭祀終焉に関する神社由緒、現在の三宮と遥拝所を、典拠の性質を分けて読む。",
  status: "draft",
  releasedAt: "2026-09-24",
  sources: [
    {
      id: "munakata-archives-okinoshima-ritual-site",
      kind: "modern-reference",
      title: "沖ノ島祭祀遺跡",
      publisher: "『神宿る島』宗像・沖ノ島と関連遺産群保存活用協議会",
      url: "https://www.munakata-archives.asia/frmSearchBunkazaiDetail.aspx?id=30&langid=",
      retrievedAt: "2026-09-24",
      locator: "4世紀から9世紀末の航海安全に関わる古代祭祀遺跡という説明",
      reviewStatus: "reviewed",
    },
    {
      id: "munakata-archives-clan-and-ritual",
      kind: "modern-reference",
      title: "宗像氏と沖ノ島祭祀",
      publisher: "『神宿る島』宗像・沖ノ島と関連遺産群保存活用協議会",
      url: "https://www.munakata-archives.asia/frmSearchBunkazaiDetail.aspx?id=161",
      retrievedAt: "2026-09-24",
      locator: "4世紀後半の祭祀開始、宗像氏、ヤマト王権の対外交流、新原・奴山古墳群",
      reviewStatus: "reviewed",
    },
    {
      id: "munakata-taisha-origin-okinoshima",
      kind: "modern-reference",
      title: "宗像大社 由緒",
      publisher: "宗像大社",
      url: "https://munakata-taisha.or.jp/yuisyo.html",
      retrievedAt: "2026-09-24",
      locator: "三宮と祭神、沖ノ島出土品、勅使差遣、894年以後の国家祭祀",
      reviewStatus: "reviewed",
      note: "三宮の現在祭祀と神社公式の由緒として用いる。由緒が示す因果関係を考古学的確定事項へ拡張しない。",
    },
    {
      id: "munakata-taisha-nakatsumiya",
      kind: "modern-reference",
      title: "宗像大社 中津宮",
      publisher: "宗像大社",
      url: "https://munakata-taisha.or.jp/about_nakatsu.html",
      retrievedAt: "2026-09-24",
      locator: "中津宮祭神と沖津宮遥拝所の所在地・昭和8年再建",
      reviewStatus: "reviewed",
    },
  ],
  viewpoints: [
    { id: "munakata-archaeological-ritual", kind: "source", label: "沖ノ島祭祀の考古学的範囲", description: "祭祀遺跡と出土品から確認できる時期・場所・対外交流の文脈を見る。" },
    { id: "munakata-institutional-history", kind: "source", label: "宗像大社の制度的由緒", description: "神社公式が説明する国家祭祀の終焉と現在の祭祀施設を、考古学的事実と分けて見る。" },
  ],
  entities: [
    { id: "okinoshima", kind: "place", label: "沖ノ島", aliases: ["宗像沖ノ島"] },
    { id: "okinoshima-ritual-site", kind: "place", label: "沖ノ島祭祀遺跡", aliases: [] },
    { id: "munakata-okitsumiya", kind: "place", label: "沖津宮", aliases: ["宗像大社沖津宮"] },
    { id: "munakata-nakatsumiya", kind: "place", label: "中津宮", aliases: ["宗像大社中津宮"] },
    { id: "munakata-hetsumiya", kind: "place", label: "辺津宮", aliases: ["宗像大社辺津宮", "宗像大社"] },
    { id: "okitsumiya-yohai", kind: "place", label: "沖津宮遥拝所", aliases: [] },
    { id: "oshima-munakata", kind: "place", label: "大島", aliases: ["筑前大島"] },
    { id: "munakata-clan", kind: "group", label: "宗像氏", aliases: ["胸形氏"] },
    { id: "yamato-polity", kind: "polity", label: "ヤマト王権", aliases: ["大和朝廷"] },
    { id: "tagorihime-munakata", kind: "deity", label: "田心姫神", aliases: ["田心姫命"] },
    { id: "tagitsuhime-munakata", kind: "deity", label: "湍津姫神", aliases: ["湍津姫命"] },
    { id: "ichikishimahime-munakata", kind: "deity", label: "市杵島姫神", aliases: ["市杵島姫命"] },
    { id: "okinoshima-ritual-period", kind: "event", label: "沖ノ島における古代祭祀（4～9世紀末）", aliases: ["沖ノ島祭祀"] },
    { id: "munakata-state-ritual-end-894", kind: "event", label: "大規模な国家祭祀の終焉（894年）", aliases: ["遣唐使廃止後の祭祀再編"] },
    { id: "okitsumiya-yohai-rebuild-1933", kind: "event", label: "沖津宮遥拝所の再建（1933年）", aliases: ["昭和8年の沖津宮遥拝所再建"] },
  ],
  assertions: [
    { id: "munakata-okinoshima-001", subjectId: "okinoshima-ritual-period", predicate: "occurred_at", objectId: "okinoshima-ritual-site", relationFamily: "ritual", nature: "reviewed-reference", viewpointIds: ["munakata-archaeological-ritual"], sourceIds: ["munakata-archives-okinoshima-ritual-site"], sequence: 1, historicalTime: { kind: "calendar", label: "4世紀～9世紀末", startYear: 300, endYear: 899, approximate: true }, evidenceBasis: "modern-documentation", confidence: "high", reviewStatus: "reviewed", note: "保存活用協議会の文化財解説が示す考古学的期間。毎年継続した祭祀回数や頻度までは示さない。" },
    { id: "munakata-okinoshima-002", subjectId: "munakata-clan", predicate: "participated_in", objectId: "okinoshima-ritual-period", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["munakata-archaeological-ritual"], sourceIds: ["munakata-archives-clan-and-ritual"], sequence: 1, historicalTime: { kind: "calendar", label: "4世紀後半以降", startYear: 350, endYear: 899, approximate: true }, evidenceBasis: "modern-documentation", confidence: "high", reviewStatus: "reviewed" },
    { id: "munakata-okinoshima-003", subjectId: "yamato-polity", predicate: "cooperated_with", objectId: "munakata-clan", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["munakata-archaeological-ritual"], sourceIds: ["munakata-archives-clan-and-ritual"], sequence: 1, historicalTime: { kind: "calendar", label: "古墳時代を中心とする対外交流期", startYear: 350, endYear: 599, approximate: true }, evidenceBasis: "modern-documentation", confidence: "high", reviewStatus: "reviewed", note: "保存活用協議会の解説に基づく。両者の政治関係全体を単純化する線ではない。" },
    { id: "munakata-okinoshima-004", subjectId: "munakata-state-ritual-end-894", predicate: "changed", objectId: "okinoshima-ritual-period", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["munakata-institutional-history"], sourceIds: ["munakata-taisha-origin-okinoshima"], sequence: 2, historicalTime: { kind: "calendar", label: "寛平6年", startYear: 894, approximate: false }, evidenceBasis: "institutional-tradition", confidence: "medium", reviewStatus: "reviewed", note: "宗像大社公式が遣唐使廃止により大規模な国家祭祀が終焉したと説明する由緒。考古学資料だけから同年の断絶を確定しない。" },
    { id: "munakata-okinoshima-005", subjectId: "okitsumiya-yohai-rebuild-1933", predicate: "rebuilt", objectId: "okitsumiya-yohai", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["munakata-institutional-history"], sourceIds: ["munakata-taisha-nakatsumiya"], sequence: 3, historicalTime: { kind: "calendar", label: "昭和8年", startYear: 1933, approximate: false }, evidenceBasis: "modern-documentation", confidence: "high", reviewStatus: "reviewed" },
    { id: "munakata-okinoshima-006", subjectId: "tagorihime-munakata", predicate: "enshrined_at", objectId: "munakata-okitsumiya", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["munakata-institutional-history"], sourceIds: ["munakata-taisha-origin-okinoshima"], evidenceBasis: "modern-documentation", confidence: "high", reviewStatus: "reviewed" },
    { id: "munakata-okinoshima-007", subjectId: "tagitsuhime-munakata", predicate: "enshrined_at", objectId: "munakata-nakatsumiya", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["munakata-institutional-history"], sourceIds: ["munakata-taisha-origin-okinoshima", "munakata-taisha-nakatsumiya"], evidenceBasis: "modern-documentation", confidence: "high", reviewStatus: "reviewed" },
    { id: "munakata-okinoshima-008", subjectId: "ichikishimahime-munakata", predicate: "enshrined_at", objectId: "munakata-hetsumiya", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["munakata-institutional-history"], sourceIds: ["munakata-taisha-origin-okinoshima"], evidenceBasis: "modern-documentation", confidence: "high", reviewStatus: "reviewed" },
    { id: "munakata-okinoshima-009", subjectId: "okitsumiya-yohai", predicate: "located_on", objectId: "oshima-munakata", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["munakata-institutional-history"], sourceIds: ["munakata-taisha-nakatsumiya"], evidenceBasis: "modern-documentation", confidence: "high", reviewStatus: "reviewed" },
  ],
  presets: [
    {
      id: "munakata-okinoshima-history",
      label: "宗像・沖ノ島の祭祀変遷",
      lensType: "timeline",
      description: "考古学的に確認される4～9世紀末の沖ノ島祭祀、894年の終焉に関する神社由緒、1933年の遥拝所再建を典拠別に並べる。",
      rootEntityIds: ["okinoshima-ritual-period", "munakata-state-ritual-end-894", "okitsumiya-yohai-rebuild-1933"],
      relationFamilies: ["ritual", "historical-context"],
      viewpointIds: ["munakata-archaeological-ritual", "munakata-institutional-history"],
      expansionDepth: 3,
    },
    {
      id: "munakata-three-shrines",
      label: "宗像三宮と現在祭祀",
      lensType: "relationship",
      description: "沖津宮・中津宮・辺津宮の現在祭神と、大島の沖津宮遥拝所を古代祭祀の連続性とは分けて見る。",
      rootEntityIds: ["munakata-okitsumiya", "munakata-nakatsumiya", "munakata-hetsumiya", "okitsumiya-yohai"],
      relationFamilies: ["enshrinement", "association"],
      viewpointIds: ["munakata-institutional-history"],
      expansionDepth: 2,
    },
  ],
});
