import { LensKnowledgePackSchema } from "./schema";

const userExampleSource = {
  id: "user-example-2026-08-31",
  kind: "user-input" as const,
  title: "知識パック構造を検討した会話上の例",
  note: "LENSの初期表示案。外部資料による検証前のため、確定知識として扱わない。",
};

export const japaneseMythologyPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "japanese-mythology",
  version: "0.1.0",
  label: "日本神話・神統譜",
  description:
    "皇統神話の主経路、周辺の神々、祭祀地、古事記・日本書紀の記述差を分離して保持する初期パック。",
  status: "draft",
  releasedAt: "2026-08-31",
  sources: [
    userExampleSource,
    {
      id: "kojiki",
      kind: "classical-text",
      title: "古事記",
      note: "巻・該当箇所・底本は今後のレビューで追加する。",
    },
    {
      id: "nihon-shoki",
      kind: "classical-text",
      title: "日本書紀",
      note: "本文と一書（異伝）を同一視せず、今後個別のAssertionへ分解する。",
    },
  ],
  viewpoints: [
    {
      id: "kojiki-view",
      kind: "source",
      label: "古事記の記述",
      description: "古事記に基づく神話上の関係。",
    },
    {
      id: "nihon-shoki-view",
      kind: "source",
      label: "日本書紀の記述",
      description: "日本書紀本文・一書に基づく関係。詳細な異伝分離は次版で行う。",
    },
    {
      id: "imperial-myth-view",
      kind: "analytical",
      label: "皇統神話の主経路",
      description: "神代から神武天皇へ至る系譜を再認識するための投影。",
    },
    {
      id: "munakata-view",
      kind: "analytical",
      label: "宗像三女神との接続",
      description: "誓約・祭祀地・史料を宗像訪問からたどる投影。",
    },
  ],
  entities: [
    { id: "izanagi", kind: "deity", label: "イザナギ", aliases: ["伊邪那岐命"] },
    { id: "izanami", kind: "deity", label: "イザナミ", aliases: ["伊邪那美命"] },
    { id: "misogi", kind: "event", label: "禊", aliases: [] },
    { id: "amaterasu", kind: "deity", label: "天照大御神", aliases: ["アマテラス"] },
    { id: "tsukuyomi", kind: "deity", label: "月読命", aliases: ["ツクヨミ"] },
    { id: "susanoo", kind: "deity", label: "須佐之男命", aliases: ["スサノオ"] },
    { id: "ukei", kind: "event", label: "誓約（うけい）", aliases: [] },
    { id: "munakata-triad", kind: "group", label: "宗像三女神", aliases: [] },
    { id: "oshihomimi", kind: "deity", label: "天忍穂耳尊", aliases: [] },
    { id: "ninigi", kind: "deity", label: "瓊瓊杵尊", aliases: ["ニニギ"] },
    { id: "tenson-korin", kind: "event", label: "天孫降臨", aliases: [] },
    { id: "konohanasakuya", kind: "deity", label: "木花之佐久夜毘売", aliases: ["コノハナサクヤヒメ"] },
    { id: "hikohohodemi", kind: "deity", label: "彦火火出見尊", aliases: ["山幸彦"] },
    { id: "toyotamahime", kind: "deity", label: "豊玉毘売命", aliases: ["トヨタマヒメ"] },
    { id: "ugayafukiaezu", kind: "deity", label: "鵜葺草葺不合尊", aliases: [] },
    { id: "tamayorihime", kind: "deity", label: "玉依毘売命", aliases: ["タマヨリヒメ"] },
    { id: "jimmu", kind: "person", label: "神武天皇", aliases: ["神倭伊波礼毘古命"] },
    { id: "imperial-line", kind: "group", label: "歴代天皇の継承", aliases: [] },
    { id: "tenmu", kind: "person", label: "天武天皇", aliases: [] },
    { id: "munakata-taisha", kind: "place", label: "宗像大社", aliases: [] },
    { id: "kojiki-text", kind: "text", label: "古事記", aliases: [] },
    { id: "nihon-shoki-text", kind: "text", label: "日本書紀", aliases: [] },
  ],
  assertions: [
    { id: "myth-000", subjectId: "izanagi", predicate: "paired_with", objectId: "izanami", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["kojiki-view", "nihon-shoki-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-001", subjectId: "izanagi", predicate: "performs", objectId: "misogi", relationFamily: "association", nature: "source-statement", viewpointIds: ["kojiki-view"], sourceIds: ["kojiki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-002", subjectId: "misogi", predicate: "gives_birth_to", objectId: "amaterasu", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["kojiki-view"], sourceIds: ["kojiki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-003", subjectId: "misogi", predicate: "gives_birth_to", objectId: "tsukuyomi", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["kojiki-view"], sourceIds: ["kojiki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-004", subjectId: "misogi", predicate: "gives_birth_to", objectId: "susanoo", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["kojiki-view"], sourceIds: ["kojiki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-005", subjectId: "amaterasu", predicate: "participates_in", objectId: "ukei", relationFamily: "association", nature: "source-statement", viewpointIds: ["kojiki-view", "nihon-shoki-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-006", subjectId: "susanoo", predicate: "participates_in", objectId: "ukei", relationFamily: "association", nature: "source-statement", viewpointIds: ["kojiki-view", "nihon-shoki-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-007", subjectId: "ukei", predicate: "gives_birth_to", objectId: "munakata-triad", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["munakata-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft", note: "各神の親子表現・生成物・所持者は史料差を分けて追加する。" },
    { id: "myth-008", subjectId: "amaterasu", predicate: "parent_of", objectId: "oshihomimi", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-009", subjectId: "oshihomimi", predicate: "parent_of", objectId: "ninigi", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-010", subjectId: "ninigi", predicate: "participates_in", objectId: "tenson-korin", relationFamily: "association", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-011", subjectId: "ninigi", predicate: "parent_of", objectId: "hikohohodemi", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft", note: "母神コノハナサクヤヒメとの関係も別Assertionで保持する。" },
    { id: "myth-012", subjectId: "konohanasakuya", predicate: "parent_of", objectId: "hikohohodemi", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-013", subjectId: "hikohohodemi", predicate: "parent_of", objectId: "ugayafukiaezu", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-014", subjectId: "toyotamahime", predicate: "parent_of", objectId: "ugayafukiaezu", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-015", subjectId: "ugayafukiaezu", predicate: "parent_of", objectId: "jimmu", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-016", subjectId: "tamayorihime", predicate: "parent_of", objectId: "jimmu", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-017", subjectId: "jimmu", predicate: "anchors", objectId: "imperial-line", relationFamily: "succession", nature: "interpretive-model", viewpointIds: ["imperial-myth-view"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "神話的系譜と歴史上の皇位継承を同じ線にしないための境界ノード。" },
    { id: "myth-018", subjectId: "tenmu", predicate: "member_of", objectId: "imperial-line", relationFamily: "succession", nature: "user-model", viewpointIds: ["imperial-myth-view"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-019", subjectId: "munakata-triad", predicate: "enshrined_at", objectId: "munakata-taisha", relationFamily: "enshrinement", nature: "user-model", viewpointIds: ["munakata-view"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-020", subjectId: "munakata-triad", predicate: "attested_in", objectId: "kojiki-text", relationFamily: "textual-attestation", nature: "source-statement", viewpointIds: ["kojiki-view"], sourceIds: ["kojiki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-021", subjectId: "munakata-triad", predicate: "attested_in", objectId: "nihon-shoki-text", relationFamily: "textual-attestation", nature: "source-statement", viewpointIds: ["nihon-shoki-view"], sourceIds: ["nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
  ],
  presets: [
    { id: "imperial-mainline", label: "皇統神話の主経路", lensType: "genealogy", description: "アマテラスから神武天皇までを主線とし、配偶神・出来事・史料差を周辺展開する。", rootEntityIds: ["amaterasu"], relationFamilies: ["genealogy", "succession", "association"], viewpointIds: ["imperial-myth-view"], expansionDepth: 3 },
    { id: "munakata-connections", label: "宗像三女神の周辺", lensType: "genealogy", description: "誓約、アマテラス、スサノオ、祭祀地、史料を宗像訪問から再認識する。", rootEntityIds: ["munakata-triad", "munakata-taisha"], relationFamilies: ["genealogy", "association", "enshrinement", "textual-attestation"], viewpointIds: ["munakata-view"], expansionDepth: 2 },
  ],
});

export const wajindenRoutesPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "wajinden-routes",
  version: "0.1.0",
  label: "魏志倭人伝の行程と比定説",
  description: "原文上の国の順序と、現代地名への比定、邪馬台国九州説・畿内説を別の関係として保持する。",
  status: "draft",
  releasedAt: "2026-08-31",
  sources: [
    userExampleSource,
    { id: "gishi-wajinden", kind: "classical-text", title: "三国志 魏書 東夷伝 倭人条", note: "底本・該当箇所・原文引用は今後のレビューで追加する。" },
  ],
  viewpoints: [
    { id: "wajinden-text-order", kind: "source", label: "倭人条の記述順", description: "原文に現れる国・行程記述の順序。現代地名への比定とは分離する。" },
    { id: "common-identifications", kind: "hypothesis", label: "主要な現代地名比定", description: "対海国・一大国・末盧国などの代表的比定候補。すべて検証対象として保持する。" },
    { id: "northern-kyushu-hypothesis", kind: "hypothesis", label: "邪馬台国九州説", description: "邪馬台国を北部九州を中心とする地域へ比定する説群。単一説として固定しない。" },
    { id: "kinai-hypothesis", kind: "hypothesis", label: "邪馬台国畿内説", description: "邪馬台国を奈良盆地周辺へ比定する説群。行程解釈の違いを保持する。" },
  ],
  entities: [
    { id: "guya-korea", kind: "polity", label: "狗邪韓国", aliases: [] },
    { id: "tsushima-state", kind: "polity", label: "対海国", aliases: ["対馬国"] },
    { id: "iki-state", kind: "polity", label: "一大国", aliases: ["一支国"] },
    { id: "matsuro-state", kind: "polity", label: "末盧国", aliases: [] },
    { id: "ito-state", kind: "polity", label: "伊都国", aliases: [] },
    { id: "na-state", kind: "polity", label: "奴国", aliases: [] },
    { id: "fumi-state", kind: "polity", label: "不弥国", aliases: [] },
    { id: "yamatai-state", kind: "polity", label: "邪馬台国", aliases: ["邪馬壹国"] },
    { id: "tsushima", kind: "place", label: "対馬", aliases: [] },
    { id: "iki", kind: "place", label: "壱岐", aliases: [] },
    { id: "karatsu", kind: "place", label: "唐津周辺", aliases: [] },
    { id: "itoshima", kind: "place", label: "糸島周辺", aliases: [] },
    { id: "hakata-plain", kind: "place", label: "福岡・博多平野周辺", aliases: [] },
    { id: "umi", kind: "place", label: "宇美周辺", aliases: [] },
    { id: "iizuka", kind: "place", label: "飯塚周辺", aliases: [] },
    { id: "northern-kyushu", kind: "place", label: "北部九州の候補地域", aliases: [] },
    { id: "nara-basin", kind: "place", label: "奈良盆地周辺", aliases: [] },
  ],
  assertions: [
    { id: "route-001", subjectId: "guya-korea", predicate: "followed_by", objectId: "tsushima-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 1, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-002", subjectId: "tsushima-state", predicate: "followed_by", objectId: "iki-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 2, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-003", subjectId: "iki-state", predicate: "followed_by", objectId: "matsuro-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 3, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-004", subjectId: "matsuro-state", predicate: "followed_by", objectId: "ito-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 4, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-005", subjectId: "ito-state", predicate: "followed_by", objectId: "na-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 5, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-006", subjectId: "na-state", predicate: "followed_by", objectId: "fumi-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 6, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-007", subjectId: "tsushima-state", predicate: "identified_with", objectId: "tsushima", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "tsushima-identification", confidence: "high", reviewStatus: "draft" },
    { id: "route-008", subjectId: "iki-state", predicate: "identified_with", objectId: "iki", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "iki-identification", confidence: "high", reviewStatus: "draft" },
    { id: "route-009", subjectId: "matsuro-state", predicate: "identified_with", objectId: "karatsu", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "matsuro-identification", confidence: "high", reviewStatus: "draft" },
    { id: "route-010", subjectId: "ito-state", predicate: "identified_with", objectId: "itoshima", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "ito-identification", confidence: "high", reviewStatus: "draft" },
    { id: "route-011", subjectId: "na-state", predicate: "identified_with", objectId: "hakata-plain", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "na-identification", confidence: "medium", reviewStatus: "draft" },
    { id: "route-012", subjectId: "fumi-state", predicate: "identified_with", objectId: "umi", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "fumi-identification", confidence: "disputed", reviewStatus: "draft" },
    { id: "route-013", subjectId: "fumi-state", predicate: "identified_with", objectId: "iizuka", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "fumi-identification", confidence: "disputed", reviewStatus: "draft" },
    { id: "route-014", subjectId: "yamatai-state", predicate: "identified_with", objectId: "northern-kyushu", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["northern-kyushu-hypothesis"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "yamatai-location", confidence: "disputed", reviewStatus: "draft" },
    { id: "route-015", subjectId: "yamatai-state", predicate: "identified_with", objectId: "nara-basin", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["kinai-hypothesis"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "yamatai-location", confidence: "disputed", reviewStatus: "draft" },
    { id: "route-016", subjectId: "fumi-state", predicate: "route_model_continues_to", objectId: "northern-kyushu", relationFamily: "route", nature: "interpretive-model", viewpointIds: ["northern-kyushu-hypothesis"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "yamatai-route", confidence: "disputed", reviewStatus: "draft" },
    { id: "route-017", subjectId: "fumi-state", predicate: "route_model_continues_to", objectId: "nara-basin", relationFamily: "route", nature: "interpretive-model", viewpointIds: ["kinai-hypothesis"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "yamatai-route", confidence: "disputed", reviewStatus: "draft" },
  ],
  presets: [
    { id: "wajinden-source-route", label: "倭人条の記述順", lensType: "route", description: "現代比定を混ぜず、原文上の国の順序を表示する。", rootEntityIds: ["guya-korea"], relationFamilies: ["route"], viewpointIds: ["wajinden-text-order"], expansionDepth: 8 },
    { id: "yamatai-hypotheses", label: "九州説と畿内説", lensType: "route", description: "同じ史料経路に競合する比定説を重ね、共通部分と分岐を表示する。", rootEntityIds: ["fumi-state", "yamatai-state"], relationFamilies: ["route", "identification"], viewpointIds: ["northern-kyushu-hypothesis", "kinai-hypothesis"], hypothesisGroupIds: ["yamatai-location", "yamatai-route"], expansionDepth: 2 },
  ],
});

export const religionRelationsPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "religion-relations",
  version: "0.1.0",
  label: "宗教の歴史関係・習合・概念比較",
  description: "宗教を単一の進化系統樹にせず、歴史的接触、習合、分析上の分類、概念比較を別の関係として保持する。",
  status: "draft",
  releasedAt: "2026-08-31",
  sources: [userExampleSource],
  viewpoints: [
    { id: "historical-relations", kind: "analytical", label: "歴史関係", description: "成立環境、伝播、接触、影響を時間的な関係として見る。" },
    { id: "syncretic-relations", kind: "analytical", label: "習合関係", description: "異なる伝統が併存・再解釈・混合した関係を見る。" },
    { id: "conceptual-comparison", kind: "analytical", label: "概念比較", description: "神、宇宙原理、因果、自然、祖霊などの比較軸で見る。直接の系譜を意味しない。" },
    { id: "religion-user-draft", kind: "user", label: "ユーザーの初期整理", description: "会話で提示された理解用の構造。学術的分類としては未検証。" },
  ],
  entities: [
    { id: "nature-veneration", kind: "concept", label: "自然・場所への信仰", aliases: ["自然崇拝"] },
    { id: "ancestor-veneration", kind: "concept", label: "祖先・祖霊信仰", aliases: [] },
    { id: "animism", kind: "concept", label: "アニミズム", aliases: [] },
    { id: "shamanism", kind: "concept", label: "シャーマニズム", aliases: [] },
    { id: "ancient-kami-rites", kind: "tradition", label: "古代の神祭り・祭祀", aliases: ["古代神道"] },
    { id: "shinto", kind: "tradition", label: "神道", aliases: [] },
    { id: "buddhism", kind: "tradition", label: "仏教", aliases: [] },
    { id: "shinbutsu-shugo", kind: "tradition", label: "神仏習合", aliases: [] },
    { id: "shugendo", kind: "tradition", label: "修験道", aliases: [] },
    { id: "ancient-indian-context", kind: "group", label: "古代インドの宗教・思想環境", aliases: [] },
    { id: "hindu-traditions", kind: "tradition", label: "ヒンドゥー教諸伝統", aliases: [] },
    { id: "brahman", kind: "concept", label: "ブラフマン／宇宙原理", aliases: [] },
    { id: "dependent-origination", kind: "concept", label: "縁起・因果・無常", aliases: [] },
    { id: "polytheism", kind: "concept", label: "多神教という分類", aliases: [] },
    { id: "monotheism", kind: "concept", label: "唯一神教という分類", aliases: [] },
    { id: "greco-roman", kind: "tradition", label: "ギリシャ・ローマの宗教伝統", aliases: [] },
    { id: "abrahamic-traditions", kind: "group", label: "アブラハム系宗教", aliases: [] },
    { id: "judaism", kind: "tradition", label: "ユダヤ教", aliases: [] },
    { id: "christianity", kind: "tradition", label: "キリスト教", aliases: [] },
    { id: "islam", kind: "tradition", label: "イスラム教", aliases: [] },
  ],
  assertions: [
    { id: "religion-001", subjectId: "nature-veneration", predicate: "compared_through", objectId: "animism", relationFamily: "conceptual-comparison", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "アニミズムを歴史的祖先ではなく分析概念として扱う。" },
    { id: "religion-002", subjectId: "ancestor-veneration", predicate: "associated_with", objectId: "ancient-kami-rites", relationFamily: "association", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-003", subjectId: "nature-veneration", predicate: "associated_with", objectId: "ancient-kami-rites", relationFamily: "association", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-004", subjectId: "shamanism", predicate: "compared_with", objectId: "ancient-kami-rites", relationFamily: "conceptual-comparison", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "直接の派生関係ではなく、儀礼実践の比較軸。" },
    { id: "religion-005", subjectId: "ancient-kami-rites", predicate: "historical_context_of", objectId: "shinto", relationFamily: "historical-context", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-006", subjectId: "shinto", predicate: "contributes_to", objectId: "shinbutsu-shugo", relationFamily: "syncretism", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-007", subjectId: "buddhism", predicate: "contributes_to", objectId: "shinbutsu-shugo", relationFamily: "syncretism", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-008", subjectId: "shinto", predicate: "historically_interacts_with", objectId: "shugendo", relationFamily: "syncretism", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-009", subjectId: "buddhism", predicate: "historically_interacts_with", objectId: "shugendo", relationFamily: "syncretism", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-010", subjectId: "buddhism", predicate: "emerges_within", objectId: "ancient-indian-context", relationFamily: "historical-context", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "現代のヒンドゥー教から仏教が直接派生した、とは表現しない。" },
    { id: "religion-011", subjectId: "hindu-traditions", predicate: "develops_within", objectId: "ancient-indian-context", relationFamily: "historical-context", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-012", subjectId: "brahman", predicate: "associated_with", objectId: "hindu-traditions", relationFamily: "conceptual-comparison", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-013", subjectId: "dependent-origination", predicate: "associated_with", objectId: "buddhism", relationFamily: "conceptual-comparison", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-014", subjectId: "greco-roman", predicate: "classified_as", objectId: "polytheism", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-015", subjectId: "hindu-traditions", predicate: "partly_compared_as", objectId: "polytheism", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "多様な一神論的・一元論的理解もあるため単純分類しない。" },
    { id: "religion-016", subjectId: "judaism", predicate: "member_of", objectId: "abrahamic-traditions", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-017", subjectId: "christianity", predicate: "member_of", objectId: "abrahamic-traditions", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-018", subjectId: "islam", predicate: "member_of", objectId: "abrahamic-traditions", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "キリスト教からの単純な派生線ではなく、共有する伝承と歴史的接触を別途表す。" },
    { id: "religion-019", subjectId: "judaism", predicate: "classified_as", objectId: "monotheism", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-020", subjectId: "christianity", predicate: "classified_as", objectId: "monotheism", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-021", subjectId: "islam", predicate: "classified_as", objectId: "monotheism", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
  ],
  presets: [
    { id: "religion-history", label: "歴史関係", lensType: "timeline", description: "成立環境、歴史的接触、伝播を表示し、概念的類似とは分離する。", rootEntityIds: ["ancient-kami-rites", "ancient-indian-context", "abrahamic-traditions"], relationFamilies: ["historical-context", "influence"], viewpointIds: ["historical-relations"], expansionDepth: 2 },
    { id: "religion-syncretism", label: "習合関係", lensType: "relationship", description: "神仏習合や修験道など、伝統が接触し再構成された関係を表示する。", rootEntityIds: ["shinbutsu-shugo", "shugendo"], relationFamilies: ["syncretism"], viewpointIds: ["syncretic-relations"], expansionDepth: 2 },
    { id: "religion-concepts", label: "概念比較", lensType: "relationship", description: "多神・唯一神・宇宙原理・自然・祖霊などを比較する。歴史的派生を意味しない。", rootEntityIds: ["polytheism", "monotheism", "brahman", "animism"], relationFamilies: ["classification", "conceptual-comparison", "association"], viewpointIds: ["conceptual-comparison"], expansionDepth: 2 },
  ],
});

export const seedLensKnowledgePacks = [
  japaneseMythologyPack,
  wajindenRoutesPack,
  religionRelationsPack,
];
