import { LensKnowledgePackSchema } from "./schema";

const userExampleSource = {
  id: "user-example-2026-08-31",
  kind: "user-input" as const,
  title: "知識パック構造を検討した会話上の例",
  note: "LENSの初期表示案。外部資料による検証前のため、確定知識として扱わない。",
};

const munakataOfficialSource = {
  id: "munakata-taisha-origin",
  kind: "modern-reference" as const,
  title: "宗像大社 由緒",
  publisher: "宗像大社",
  url: "https://munakata-taisha.or.jp/yuisyo.html",
  retrievedAt: "2026-09-01",
  locator: "由緒「御祭神」および「日本神話と宗像三女神」",
  reviewStatus: "reviewed" as const,
  note: "宗像三女神、三宮、誓約に関する公式由緒。原典の古事記・日本書紀とは分けて参照する。",
};

const usaSyncretismSource = {
  id: "usa-jingu-syncretism",
  kind: "modern-reference" as const,
  title: "宇佐神宮 神仏習合",
  publisher: "宇佐神宮",
  url: "https://www.usajinguu.com/shinbutsu/",
  retrievedAt: "2026-09-01",
  locator: "「神仏習合のはじまり 隼人の乱と放生会」および「弥勒寺」",
  reviewStatus: "reviewed" as const,
  note: "宇佐における放生会、寺院、八幡信仰と仏教の接触を説明する公式解説。",
};

const kunisakiJapanHeritageSource = {
  id: "kunisaki-japan-heritage",
  kind: "modern-reference" as const,
  title: "鬼が仏になった里「くにさき」",
  publisher: "文化庁 日本遺産ポータルサイト",
  url: "https://japan-heritage.bunka.go.jp/ja/stories/story066/",
  retrievedAt: "2026-09-01",
  locator: "STORY「鬼に祈る『くにさき』の僧侶達」",
  reviewStatus: "reviewed" as const,
  note: "国東半島、六郷満山、神仏習合文化の地域的な関係を説明する公的解説。",
};

const usaKunisakiConnectionSource = {
  id: "usa-kunisaki-connection",
  kind: "modern-reference" as const,
  title: "日本遺産くにさきverの宇佐飴の売上の一部は、文化財活用事業に使用されます！",
  publisher: "文化庁 日本遺産ポータルサイト",
  publishedAt: "2021-02-01",
  url: "https://japan-heritage.bunka.go.jp/ja/news/1603/",
  retrievedAt: "2026-09-02",
  locator: "宇佐神宮と国東半島・六郷満山の文化的関係を説明する本文",
  reviewStatus: "reviewed" as const,
  note: "宇佐神宮と六郷満山を直接結ぶ公的解説。宗像との直接的な歴史関係を支持する資料としては使わない。",
};

const ndlYamataiExhibitionSource = {
  id: "ndl-yamatai-exhibition",
  kind: "modern-reference" as const,
  title: "国立国会図書館 第85回常設展示 邪馬台国論争",
  publisher: "国立国会図書館",
  citation: "第85回常設展示「邪馬台国論争」",
  url: "https://dl.ndl.go.jp/view/download/digidepo_999426_po_85.pdf?contentNo=1",
  retrievedAt: "2026-09-01",
  locator: "2頁「争点 邪馬台国の所在論」",
  reviewStatus: "reviewed" as const,
  note: "魏志倭人伝の書誌的位置づけと、九州説・畿内説を含む論争史を確認する入口。原典本文の代替にはしない。",
};

export const japaneseMythologyPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "japanese-mythology",
  version: "0.3.0",
  label: "日本神話・神統譜",
  description:
    "皇統神話の主経路、周辺の神々、祭祀地、古事記・日本書紀の記述差を分離して保持する初期パック。",
  status: "draft",
  releasedAt: "2026-08-31",
  sources: [
    userExampleSource,
    munakataOfficialSource,
    {
      id: "kojiki",
      kind: "classical-text",
      title: "古事記",
      note: "巻・該当箇所・底本は今後のレビューで追加する。",
    },
    {
      id: "nihon-shoki",
      kind: "classical-text",
      title: "日本書紀",
      note: "本文と一書（異伝）を同一視せず、今後個別のAssertionへ分解する。",
    },
  ],
  viewpoints: [
    {
      id: "kojiki-view",
      kind: "source",
      label: "古事記の記述",
      description: "古事記に基づく神話上の関係。",
    },
    {
      id: "nihon-shoki-view",
      kind: "source",
      label: "日本書紀の記述",
      description: "日本書紀本文・一書に基づく関係。詳細な異伝分離は次版で行う。",
    },
    {
      id: "imperial-myth-view",
      kind: "analytical",
      label: "皇統神話の主経路",
      description: "神代から神武天皇へ至る系譜を再認識するための投影。",
    },
    {
      id: "munakata-view",
      kind: "analytical",
      label: "宗像三女神との接続",
      description: "誓約・祭祀地・史料を宗像訪問からたどる投影。",
    },
  ],
  entities: [
    { id: "izanagi", kind: "deity", label: "イザナギ", aliases: ["伊邪那岐命"] },
    { id: "izanami", kind: "deity", label: "イザナミ", aliases: ["伊邪那美命"] },
    { id: "misogi", kind: "event", label: "禊", aliases: [] },
    { id: "amaterasu", kind: "deity", label: "天照大御神", aliases: ["アマテラス"] },
    { id: "tsukuyomi", kind: "deity", label: "月読命", aliases: ["ツクヨミ"] },
    { id: "susanoo", kind: "deity", label: "須佐之男命", aliases: ["スサノオ"] },
    { id: "ukei", kind: "event", label: "誓約（うけい）", aliases: [] },
    { id: "munakata-triad", kind: "group", label: "宗像三女神", aliases: [] },
    { id: "oshihomimi", kind: "deity", label: "天忍穂耳尊", aliases: [] },
    { id: "ninigi", kind: "deity", label: "瓊瓊杵尊", aliases: ["ニニギ"] },
    { id: "tenson-korin", kind: "event", label: "天孫降臨", aliases: [] },
    { id: "konohanasakuya", kind: "deity", label: "木花之佐久夜毘売", aliases: ["コノハナサクヤヒメ"] },
    { id: "hikohohodemi", kind: "deity", label: "彦火火出見尊", aliases: ["山幸彦"] },
    { id: "toyotamahime", kind: "deity", label: "豊玉毘売命", aliases: ["トヨタマヒメ"] },
    { id: "ugayafukiaezu", kind: "deity", label: "鵜葺草葺不合尊", aliases: [] },
    { id: "tamayorihime", kind: "deity", label: "玉依毘売命", aliases: ["タマヨリヒメ"] },
    { id: "jimmu", kind: "person", label: "神武天皇", aliases: ["神倭伊波礼毘古命"] },
    { id: "imperial-line", kind: "group", label: "歴代天皇の継承", aliases: [] },
    { id: "tenmu", kind: "person", label: "天武天皇", aliases: [] },
    { id: "munakata-taisha", kind: "place", label: "宗像大社", aliases: [] },
    { id: "kojiki-text", kind: "text", label: "古事記", aliases: [] },
    { id: "nihon-shoki-text", kind: "text", label: "日本書紀", aliases: [] },
  ],
  assertions: [
    { id: "myth-000", subjectId: "izanagi", predicate: "paired_with", objectId: "izanami", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["kojiki-view", "nihon-shoki-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-001", subjectId: "izanagi", predicate: "performs", objectId: "misogi", relationFamily: "association", nature: "source-statement", viewpointIds: ["kojiki-view"], sourceIds: ["kojiki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-002", subjectId: "misogi", predicate: "gives_birth_to", objectId: "amaterasu", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["kojiki-view"], sourceIds: ["kojiki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-003", subjectId: "misogi", predicate: "gives_birth_to", objectId: "tsukuyomi", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["kojiki-view"], sourceIds: ["kojiki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-004", subjectId: "misogi", predicate: "gives_birth_to", objectId: "susanoo", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["kojiki-view"], sourceIds: ["kojiki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-005", subjectId: "amaterasu", predicate: "participates_in", objectId: "ukei", relationFamily: "association", nature: "source-statement", viewpointIds: ["kojiki-view", "nihon-shoki-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-006", subjectId: "susanoo", predicate: "participates_in", objectId: "ukei", relationFamily: "association", nature: "source-statement", viewpointIds: ["kojiki-view", "nihon-shoki-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-007", subjectId: "ukei", predicate: "gives_birth_to", objectId: "munakata-triad", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["munakata-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft", note: "各神の親子表現・生成物・所持者は史料差を分けて追加する。" },
    { id: "myth-008", subjectId: "amaterasu", predicate: "parent_of", objectId: "oshihomimi", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-009", subjectId: "oshihomimi", predicate: "parent_of", objectId: "ninigi", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-010", subjectId: "ninigi", predicate: "participates_in", objectId: "tenson-korin", relationFamily: "association", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-011", subjectId: "ninigi", predicate: "parent_of", objectId: "hikohohodemi", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft", note: "母神コノハナサクヤヒメとの関係も別Assertionで保持する。" },
    { id: "myth-012", subjectId: "konohanasakuya", predicate: "parent_of", objectId: "hikohohodemi", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-013", subjectId: "hikohohodemi", predicate: "parent_of", objectId: "ugayafukiaezu", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-014", subjectId: "toyotamahime", predicate: "parent_of", objectId: "ugayafukiaezu", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-015", subjectId: "ugayafukiaezu", predicate: "parent_of", objectId: "jimmu", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-016", subjectId: "tamayorihime", predicate: "parent_of", objectId: "jimmu", relationFamily: "genealogy", nature: "source-statement", viewpointIds: ["imperial-myth-view"], sourceIds: ["kojiki", "nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-017", subjectId: "jimmu", predicate: "anchors", objectId: "imperial-line", relationFamily: "succession", nature: "interpretive-model", viewpointIds: ["imperial-myth-view"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "神話的系譜と歴史上の皇位継承を同じ線にしないための境界ノード。" },
    { id: "myth-018", subjectId: "tenmu", predicate: "member_of", objectId: "imperial-line", relationFamily: "succession", nature: "user-model", viewpointIds: ["imperial-myth-view"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-019", subjectId: "munakata-triad", predicate: "enshrined_at", objectId: "munakata-taisha", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["munakata-view"], sourceIds: ["munakata-taisha-origin"], confidence: "high", reviewStatus: "reviewed", note: "三女神を祀る三宮の総称を、LENS上では宗像大社という集約地点へ接続する。" },
    { id: "myth-020", subjectId: "munakata-triad", predicate: "attested_in", objectId: "kojiki-text", relationFamily: "textual-attestation", nature: "source-statement", viewpointIds: ["kojiki-view"], sourceIds: ["kojiki"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "myth-021", subjectId: "munakata-triad", predicate: "attested_in", objectId: "nihon-shoki-text", relationFamily: "textual-attestation", nature: "source-statement", viewpointIds: ["nihon-shoki-view"], sourceIds: ["nihon-shoki"], confidence: "not-rated", reviewStatus: "draft" },
  ],
  presets: [
    { id: "imperial-mainline", label: "皇統神話の主経路", lensType: "genealogy", description: "アマテラスから神武天皇までを主線とし、配偶神・出来事・史料差を周辺展開する。", rootEntityIds: ["amaterasu"], relationFamilies: ["genealogy", "succession", "association"], viewpointIds: ["imperial-myth-view"], expansionDepth: 3 },
    { id: "munakata-connections", label: "宗像三女神の周辺", lensType: "genealogy", description: "誓約、アマテラス、スサノオ、祭祀地、史料を宗像訪問から再認識する。", rootEntityIds: ["munakata-triad", "munakata-taisha"], relationFamilies: ["genealogy", "association", "enshrinement", "textual-attestation"], viewpointIds: ["munakata-view", "kojiki-view", "nihon-shoki-view"], expansionDepth: 2 },
  ],
});

export const wajindenRoutesPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "wajinden-routes",
  version: "0.2.0",
  label: "魏志倭人伝の行程と比定説",
  description: "原文上の国の順序と、現代地名への比定、邪馬台国九州説・畿内説を別の関係として保持する。",
  status: "draft",
  releasedAt: "2026-08-31",
  sources: [
    userExampleSource,
    ndlYamataiExhibitionSource,
    { id: "gishi-wajinden", kind: "classical-text", title: "三国志 魏書 東夷伝 倭人条", note: "底本・該当箇所・原文引用は今後のレビューで追加する。" },
    { id: "itoshima-mikumo", kind: "modern-reference", title: "三雲南小路遺跡", publisher: "糸島市", url: "https://www.city.itoshima.lg.jp/s033/010/020/010/110/110/mikumo-iseki.html", retrievedAt: "2026-09-04", locator: "伊都国王墓としての解説、伊都国歴史博物館での展示", reviewStatus: "reviewed" },
    { id: "itoshima-hirabaru", kind: "modern-reference", title: "平原遺跡", publisher: "糸島市", url: "https://www.city.itoshima.lg.jp/s033/010/020/010/110/010/hirabaru-iseki.html", retrievedAt: "2026-09-04", locator: "1号墓を伊都国王墓とする解説", reviewStatus: "reviewed" },
    { id: "itoshima-museum", kind: "modern-reference", title: "伊都国歴史博物館の概要", publisher: "糸島市", url: "https://www.city.itoshima.lg.jp/m043/010/040/040/010/20190911144351.html", retrievedAt: "2026-09-04", locator: "平原遺跡出土品と常設展示", reviewStatus: "reviewed" },
    { id: "kasuga-nakoku-park", kind: "modern-reference", title: "春日市奴国の丘歴史公園", publisher: "春日市", url: "https://www.city.kasuga.fukuoka.jp/miryoku/history/historymuseum/1002240/1002243.html", retrievedAt: "2026-09-04", locator: "奴国中心地、須玖岡本遺跡、公園整備の解説", reviewStatus: "reviewed" },
    { id: "kasuga-nakoku-exhibition", kind: "modern-reference", title: "考古資料展示室", publisher: "春日市", url: "https://www.city.kasuga.fukuoka.jp/miryoku/history/historymuseum/1009433/1009437.html", retrievedAt: "2026-09-09", locator: "福岡平野を奴国の範囲、春日市の須玖岡本遺跡周辺を中心地とする解説", reviewStatus: "reviewed" },
    { id: "yamakawa-toma-kotobank", kind: "modern-reference", title: "山川 日本史小辞典 改訂新版『投馬国』", publisher: "山川出版社（コトバンク掲載）", url: "https://kotobank.jp/word/%E6%8A%95%E9%A6%AC%E5%9B%BD-104202", retrievedAt: "2026-09-09", locator: "九州説・大和説における投馬国の代表的比定地", reviewStatus: "reviewed" },
    { id: "itoshima-mikumo-ihara", kind: "modern-reference", title: "伊都国の王都『三雲・井原遺跡』が国史跡に指定されました。", publisher: "糸島市", url: "https://www.city.itoshima.lg.jp/s033/010/020/010/170/20171129102855.html", retrievedAt: "2026-09-04", locator: "調査の成果と価値、伊都国の中心的拠点集落・王都という位置付け", reviewStatus: "reviewed" },
    { id: "umi-koshoji-kofun", kind: "modern-reference", title: "光正寺古墳", publisher: "宇美町", url: "https://www.town.umi.lg.jp/site/spot/kanko131.html", retrievedAt: "2026-09-04", locator: "築造年代と不弥国王墓候補の解説", reviewStatus: "reviewed" },
  ],
  viewpoints: [
    { id: "wajinden-text-order", kind: "source", label: "倭人条の記述順", description: "原文に現れる国・行程記述の順序。現代地名への比定とは分離する。" },
    { id: "common-identifications", kind: "hypothesis", label: "主要な現代地名比定", description: "対海国・一大国・末盧国などの代表的比定候補。すべて検証対象として保持する。" },
    { id: "northern-kyushu-hypothesis", kind: "hypothesis", label: "邪馬台国九州説", description: "邪馬台国を北部九州を中心とする地域へ比定する説群。単一説として固定しない。" },
    { id: "kinai-hypothesis", kind: "hypothesis", label: "邪馬台国畿内説", description: "邪馬台国を奈良盆地周辺へ比定する説群。行程解釈の違いを保持する。" },
    { id: "wajinden-political-structure", kind: "source", label: "倭人条の政治・社会記述", description: "卑弥呼の共立、魏との外交、一大率、狗奴国との対立など、倭人条に記された政治関係。所在地比定とは分離する。" },
    { id: "municipal-archaeology", kind: "analytical", label: "自治体の考古学的解説", description: "自治体が公開する遺跡・博物館解説から、訪問地点と伊都国・奴国の考古学的文脈を読む。邪馬台国所在地説とは分離する。" },
    { id: "fumi-royal-tomb-hypothesis", kind: "hypothesis", label: "不弥国王墓の比定候補", description: "光正寺古墳を不弥国王墓候補とする解釈。宇美・糟屋説と嘉穂説など、不弥国所在地の競合を確定しない。" },
    { id: "toma-location-hypotheses", kind: "hypothesis", label: "投馬国の比定候補", description: "筑後・日向・備後・出雲などに分かれる所在地説。候補の存在を示し、単一地点や行程を確定しない。" },
  ],
  entities: [
    { id: "guya-korea", kind: "polity", label: "狗邪韓国", aliases: [] },
    { id: "tsushima-state", kind: "polity", label: "対海国", aliases: ["対馬国"] },
    { id: "iki-state", kind: "polity", label: "一大国", aliases: ["一支国"] },
    { id: "matsuro-state", kind: "polity", label: "末盧国", aliases: [] },
    { id: "ito-state", kind: "polity", label: "伊都国", aliases: [] },
    { id: "na-state", kind: "polity", label: "奴国", aliases: [] },
    { id: "fumi-state", kind: "polity", label: "不弥国", aliases: [] },
    { id: "toma-state", kind: "polity", label: "投馬国", aliases: [] },
    { id: "yamatai-state", kind: "polity", label: "邪馬台国", aliases: ["邪馬壹国"] },
    { id: "himiko", kind: "person", label: "卑弥呼", aliases: [] },
    { id: "nashime", kind: "person", label: "難升米", aliases: ["難升米ら"] },
    { id: "wei", kind: "polity", label: "魏", aliases: ["魏国"] },
    { id: "wa-polities", kind: "group", label: "倭の諸国", aliases: ["倭国"] },
    { id: "ittaisotsu", kind: "group", label: "一大率", aliases: ["一大卒"] },
    { id: "kunu-state", kind: "polity", label: "狗奴国", aliases: [] },
    { id: "gimhae", kind: "place", label: "金海周辺", aliases: ["釜山西方"], coordinates: { latitude: 35.23, longitude: 128.88 } },
    { id: "tsushima", kind: "place", label: "対馬", aliases: [], coordinates: { latitude: 34.2, longitude: 129.29 } },
    { id: "iki", kind: "place", label: "壱岐", aliases: [], coordinates: { latitude: 33.75, longitude: 129.69 } },
    { id: "karatsu", kind: "place", label: "唐津周辺", aliases: [], coordinates: { latitude: 33.45, longitude: 129.97 } },
    { id: "itoshima", kind: "place", label: "糸島周辺", aliases: [], coordinates: { latitude: 33.56, longitude: 130.2 } },
    { id: "hakata-plain", kind: "place", label: "福岡・博多平野周辺", aliases: [], coordinates: { latitude: 33.59, longitude: 130.4 } },
    { id: "kasuga-sugu-core", kind: "place", label: "春日市・須玖遺跡群周辺", aliases: ["春日市", "須玖岡本遺跡周辺", "春日丘陵周辺"], coordinates: { latitude: 33.537733, longitude: 130.449405 } },
    { id: "umi", kind: "place", label: "宇美周辺", aliases: ["宇美町"], coordinates: { latitude: 33.57, longitude: 130.51 } },
    { id: "iizuka", kind: "place", label: "飯塚周辺", aliases: [], coordinates: { latitude: 33.65, longitude: 130.69 } },
    { id: "northern-kyushu", kind: "place", label: "北部九州の候補地域", aliases: ["邪馬台国九州説候補地"], coordinates: { latitude: 33.3, longitude: 130.55 } },
    { id: "nara-basin", kind: "place", label: "奈良盆地周辺", aliases: [], coordinates: { latitude: 34.68, longitude: 135.8 } },
    { id: "toma-chikugo", kind: "place", label: "筑後・八女周辺", aliases: ["筑後上妻・下妻"], coordinates: { latitude: 33.21, longitude: 130.56 } },
    { id: "toma-hyuga", kind: "place", label: "日向・都萬神社周辺", aliases: ["日向児湯郡", "宮崎県西都市"], coordinates: { latitude: 32.11, longitude: 131.4 } },
    { id: "toma-tomonoura", kind: "place", label: "備後・鞆周辺", aliases: ["鞆津", "鞆の浦"], coordinates: { latitude: 34.38, longitude: 133.38 } },
    { id: "toma-izumo", kind: "place", label: "出雲周辺", aliases: ["出雲国"], coordinates: { latitude: 35.37, longitude: 132.75 } },
    { id: "ito-history-museum", kind: "place", label: "伊都国歴史博物館", aliases: ["糸島市立伊都国歴史博物館"], coordinates: { latitude: 33.536327, longitude: 130.251445 } },
    { id: "mikumo-minamishoji-site", kind: "place", label: "三雲南小路遺跡", aliases: [], coordinates: { latitude: 33.536668, longitude: 130.24155 } },
    { id: "hirabaru-site", kind: "place", label: "平原遺跡", aliases: [], coordinates: { latitude: 33.5423172, longitude: 130.2284282 } },
    { id: "sugu-okamoto-site", kind: "place", label: "須玖岡本遺跡", aliases: ["須玖岡本遺跡群"], coordinates: { latitude: 33.537733, longitude: 130.449405 } },
    { id: "nakoku-hill-park", kind: "place", label: "奴国の丘歴史公園", aliases: ["春日市奴国の丘歴史公園"], coordinates: { latitude: 33.538049, longitude: 130.451086 } },
    { id: "mikumo-ihara-site", kind: "place", label: "三雲・井原遺跡", aliases: [], coordinates: { latitude: 33.5366, longitude: 130.2368 } },
    { id: "koshoji-kofun", kind: "place", label: "光正寺古墳", aliases: ["光正寺"], coordinates: { latitude: 33.577858, longitude: 130.4999756 } },
  ],
  assertions: [
    { id: "route-001", subjectId: "guya-korea", predicate: "followed_by", objectId: "tsushima-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 1, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-002", subjectId: "tsushima-state", predicate: "followed_by", objectId: "iki-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 2, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-003", subjectId: "iki-state", predicate: "followed_by", objectId: "matsuro-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 3, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-004", subjectId: "matsuro-state", predicate: "followed_by", objectId: "ito-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 4, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-005", subjectId: "ito-state", predicate: "followed_by", objectId: "na-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 5, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-006", subjectId: "na-state", predicate: "followed_by", objectId: "fumi-state", relationFamily: "route", nature: "source-statement", viewpointIds: ["wajinden-text-order"], sourceIds: ["gishi-wajinden"], sequence: 6, confidence: "not-rated", reviewStatus: "draft" },
    { id: "route-007", subjectId: "tsushima-state", predicate: "identified_with", objectId: "tsushima", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "tsushima-identification", confidence: "high", reviewStatus: "draft" },
    { id: "route-008", subjectId: "iki-state", predicate: "identified_with", objectId: "iki", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "iki-identification", confidence: "high", reviewStatus: "draft" },
    { id: "route-009", subjectId: "matsuro-state", predicate: "identified_with", objectId: "karatsu", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "matsuro-identification", confidence: "high", reviewStatus: "draft" },
    { id: "route-010", subjectId: "ito-state", predicate: "identified_with", objectId: "itoshima", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "ito-identification", confidence: "high", reviewStatus: "draft" },
    { id: "route-011", subjectId: "na-state", predicate: "identified_with", objectId: "hakata-plain", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "na-identification", confidence: "medium", reviewStatus: "draft" },
    { id: "route-012", subjectId: "fumi-state", predicate: "identified_with", objectId: "umi", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications", "fumi-royal-tomb-hypothesis"], sourceIds: ["umi-koshoji-kofun"], hypothesisGroupId: "fumi-identification", confidence: "disputed", reviewStatus: "reviewed", note: "宇美町が紹介する宇美・糟屋説。嘉穂地域説との競合を保ち、宇美町への比定を確定しない。" },
    { id: "route-013", subjectId: "fumi-state", predicate: "identified_with", objectId: "iizuka", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "fumi-identification", confidence: "disputed", reviewStatus: "draft" },
    { id: "route-014", subjectId: "yamatai-state", predicate: "identified_with", objectId: "northern-kyushu", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["northern-kyushu-hypothesis"], sourceIds: ["ndl-yamatai-exhibition"], hypothesisGroupId: "yamatai-location", confidence: "disputed", reviewStatus: "reviewed", note: "九州説の存在を確認済み。邪馬台国の所在地を九州と確定したという意味ではない。" },
    { id: "route-015", subjectId: "yamatai-state", predicate: "identified_with", objectId: "nara-basin", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["kinai-hypothesis"], sourceIds: ["ndl-yamatai-exhibition"], hypothesisGroupId: "yamatai-location", confidence: "disputed", reviewStatus: "reviewed", note: "畿内・大和説の存在を確認済み。邪馬台国の所在地を奈良盆地と確定したという意味ではない。" },
    { id: "route-016", subjectId: "fumi-state", predicate: "route_model_continues_to", objectId: "northern-kyushu", relationFamily: "route", nature: "interpretive-model", viewpointIds: ["northern-kyushu-hypothesis"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "yamatai-route", confidence: "disputed", reviewStatus: "draft" },
    { id: "route-017", subjectId: "fumi-state", predicate: "route_model_continues_to", objectId: "nara-basin", relationFamily: "route", nature: "interpretive-model", viewpointIds: ["kinai-hypothesis"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "yamatai-route", confidence: "disputed", reviewStatus: "draft" },
    { id: "route-018", subjectId: "guya-korea", predicate: "identified_with", objectId: "gimhae", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["common-identifications"], sourceIds: ["user-example-2026-08-31"], hypothesisGroupId: "guya-identification", confidence: "medium", reviewStatus: "draft" },
    { id: "route-019", subjectId: "na-state", predicate: "center_proposed_at", objectId: "kasuga-sugu-core", relationFamily: "identification", nature: "reviewed-reference", viewpointIds: ["municipal-archaeology"], sourceIds: ["kasuga-nakoku-exhibition"], hypothesisGroupId: "na-center-identification", confidence: "high", reviewStatus: "reviewed", note: "福岡平野一帯という奴国の範囲比定と、春日市・須玖遺跡群周辺という中心地推定を分けて保持する。" },
    { id: "route-020", subjectId: "toma-state", predicate: "identified_with", objectId: "toma-chikugo", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["toma-location-hypotheses"], sourceIds: ["yamakawa-toma-kotobank"], hypothesisGroupId: "toma-location", confidence: "disputed", reviewStatus: "reviewed", note: "代表的候補の一つ。投馬国を筑後・八女周辺と確定するものではない。" },
    { id: "route-021", subjectId: "toma-state", predicate: "identified_with", objectId: "toma-hyuga", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["toma-location-hypotheses"], sourceIds: ["yamakawa-toma-kotobank"], hypothesisGroupId: "toma-location", confidence: "disputed", reviewStatus: "reviewed", note: "代表的候補の一つ。投馬国を日向・都萬神社周辺と確定するものではない。" },
    { id: "route-022", subjectId: "toma-state", predicate: "identified_with", objectId: "toma-tomonoura", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["toma-location-hypotheses"], sourceIds: ["yamakawa-toma-kotobank"], hypothesisGroupId: "toma-location", confidence: "disputed", reviewStatus: "reviewed", note: "代表的候補の一つ。投馬国を備後・鞆周辺と確定するものではない。" },
    { id: "route-023", subjectId: "toma-state", predicate: "identified_with", objectId: "toma-izumo", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["toma-location-hypotheses"], sourceIds: ["yamakawa-toma-kotobank"], hypothesisGroupId: "toma-location", confidence: "disputed", reviewStatus: "reviewed", note: "代表的候補の一つ。投馬国を出雲周辺と確定するものではない。" },
    { id: "politics-001", subjectId: "wa-polities", predicate: "established_as_ruler", objectId: "himiko", relationFamily: "historical-context", nature: "source-statement", viewpointIds: ["wajinden-political-structure"], sourceIds: ["gishi-wajinden"], confidence: "not-rated", reviewStatus: "draft", note: "倭国の争乱後に卑弥呼を共立したという史料記述。政治制度の詳細な復元とは分ける。" },
    { id: "politics-002", subjectId: "himiko", predicate: "ruled", objectId: "yamatai-state", relationFamily: "historical-context", nature: "source-statement", viewpointIds: ["wajinden-political-structure"], sourceIds: ["gishi-wajinden"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "politics-003", subjectId: "himiko", predicate: "dispatched", objectId: "nashime", relationFamily: "association", nature: "source-statement", viewpointIds: ["wajinden-political-structure"], sourceIds: ["gishi-wajinden"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "politics-004", subjectId: "nashime", predicate: "visited_as_envoy", objectId: "wei", relationFamily: "historical-context", nature: "source-statement", viewpointIds: ["wajinden-political-structure"], sourceIds: ["gishi-wajinden"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "politics-005", subjectId: "wei", predicate: "conferred_title_on", objectId: "himiko", relationFamily: "association", nature: "source-statement", viewpointIds: ["wajinden-political-structure"], sourceIds: ["gishi-wajinden"], confidence: "not-rated", reviewStatus: "draft", note: "親魏倭王の称号授与に関する史料記述。外交関係の評価は別の解釈レイヤーで扱う。" },
    { id: "politics-006", subjectId: "ittaisotsu", predicate: "stationed_in", objectId: "ito-state", relationFamily: "historical-context", nature: "source-statement", viewpointIds: ["wajinden-political-structure"], sourceIds: ["gishi-wajinden"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "politics-007", subjectId: "ittaisotsu", predicate: "oversaw", objectId: "wa-polities", relationFamily: "association", nature: "source-statement", viewpointIds: ["wajinden-political-structure"], sourceIds: ["gishi-wajinden"], confidence: "not-rated", reviewStatus: "draft", note: "一大率の機能を示す史料記述。支配範囲や制度的位置づけの復元は確定しない。" },
    { id: "politics-008", subjectId: "yamatai-state", predicate: "opposed", objectId: "kunu-state", relationFamily: "historical-context", nature: "source-statement", viewpointIds: ["wajinden-political-structure"], sourceIds: ["gishi-wajinden"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "archaeology-001", subjectId: "mikumo-minamishoji-site", predicate: "interpreted_as_royal_tomb_of", objectId: "ito-state", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["municipal-archaeology"], sourceIds: ["itoshima-mikumo"], confidence: "high", reviewStatus: "reviewed", note: "糸島市の解説による伊都国王墓としての解釈。邪馬台国所在地説の根拠とは区別する。" },
    { id: "archaeology-002", subjectId: "hirabaru-site", predicate: "interpreted_as_royal_tomb_of", objectId: "ito-state", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["municipal-archaeology"], sourceIds: ["itoshima-hirabaru"], confidence: "high", reviewStatus: "reviewed" },
    { id: "archaeology-003", subjectId: "ito-history-museum", predicate: "exhibits_material_from", objectId: "hirabaru-site", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["municipal-archaeology"], sourceIds: ["itoshima-museum"], confidence: "high", reviewStatus: "reviewed" },
    { id: "archaeology-004", subjectId: "ito-history-museum", predicate: "exhibits_material_from", objectId: "mikumo-minamishoji-site", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["municipal-archaeology"], sourceIds: ["itoshima-mikumo"], confidence: "high", reviewStatus: "reviewed" },
    { id: "archaeology-005", subjectId: "sugu-okamoto-site", predicate: "interpreted_in_context_of", objectId: "na-state", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["municipal-archaeology"], sourceIds: ["kasuga-nakoku-park"], confidence: "high", reviewStatus: "reviewed", note: "春日市を奴国の中心地とする自治体解説の文脈。邪馬台国所在地説とは分離する。" },
    { id: "archaeology-006", subjectId: "nakoku-hill-park", predicate: "preserves_part_of", objectId: "sugu-okamoto-site", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["municipal-archaeology"], sourceIds: ["kasuga-nakoku-park"], confidence: "high", reviewStatus: "reviewed" },
    { id: "archaeology-007", subjectId: "mikumo-ihara-site", predicate: "interpreted_as_capital_of", objectId: "ito-state", relationFamily: "historical-context", nature: "reviewed-reference", viewpointIds: ["municipal-archaeology"], sourceIds: ["itoshima-mikumo-ihara"], confidence: "high", reviewStatus: "reviewed", note: "糸島市による中心的拠点集落・王都という位置付け。" },
    { id: "archaeology-008", subjectId: "koshoji-kofun", predicate: "proposed_as_royal_tomb_of", objectId: "fumi-state", relationFamily: "identification", nature: "scholarly-hypothesis", viewpointIds: ["fumi-royal-tomb-hypothesis"], sourceIds: ["umi-koshoji-kofun"], hypothesisGroupId: "fumi-identification", confidence: "disputed", reviewStatus: "reviewed", note: "宇美町ページが紹介する比定候補の存在をReviewedとする。王墓であること自体の確定ではない。" },
  ],
  presets: [
    { id: "wajinden-source-route", label: "倭人条の記述順", lensType: "route", description: "現代比定を混ぜず、原文上の国の順序を表示する。投馬国以降の起点・連続関係は解釈差があるため確定線にしない。", rootEntityIds: ["guya-korea", "toma-state", "yamatai-state"], relationFamilies: ["route"], viewpointIds: ["wajinden-text-order"], expansionDepth: 8 },
    { id: "yamatai-hypotheses", label: "九州説と畿内説", lensType: "route", description: "同じ史料経路に競合する比定説を重ね、共通部分と分岐を表示する。", rootEntityIds: ["fumi-state", "yamatai-state"], relationFamilies: ["route", "identification"], viewpointIds: ["northern-kyushu-hypothesis", "kinai-hypothesis"], hypothesisGroupIds: ["yamatai-location", "yamatai-route"], expansionDepth: 2 },
    { id: "wajinden-politics", label: "卑弥呼をめぐる政治構造", lensType: "relationship", description: "卑弥呼の共立、邪馬台国、魏との外交、伊都国の一大率、狗奴国との対立を、所在地説から切り離して見直す。", rootEntityIds: ["himiko", "yamatai-state", "ito-state"], relationFamilies: ["historical-context", "association"], viewpointIds: ["wajinden-political-structure"], expansionDepth: 4 },
    {
      id: "wajinden-comparison",
      label: "倭人伝ルートと比定説",
      lensType: "route",
      description: "原文上の記述順、主要な現代地名比定、九州説と畿内説の分岐を一つの画面へ投影する。",
      rootEntityIds: ["guya-korea", "tsushima-state", "iki-state", "matsuro-state", "ito-state", "na-state", "fumi-state", "toma-state", "yamatai-state"],
      relationFamilies: ["route", "identification", "historical-context", "association"],
      viewpointIds: ["wajinden-text-order", "common-identifications", "northern-kyushu-hypothesis", "kinai-hypothesis", "municipal-archaeology", "fumi-royal-tomb-hypothesis", "toma-location-hypotheses"],
      hypothesisGroupIds: ["yamatai-location", "yamatai-route", "toma-location"],
      expansionDepth: 12,
      mapConnections: [
        {
          id: "toma-location-candidates",
          label: "投馬国の位置候補",
          description: "筑後・八女、日向・都萬神社、備後・鞆、出雲という代表的な比定候補です。候補間を結ぶ経路ではないため、地図には点だけを表示します。",
          displayMode: "points",
          contextEntityIds: ["toma-state"],
          placeEntityIds: ["toma-chikugo", "toma-hyuga", "toma-tomonoura", "toma-izumo"],
          pointFocusEntityIds: { "toma-chikugo": "toma-chikugo", "toma-hyuga": "toma-hyuga", "toma-tomonoura": "toma-tomonoura", "toma-izumo": "toma-izumo" },
          assertionIds: ["route-020", "route-021", "route-022", "route-023"],
          appearance: { color: "#d5b46d", legendLabel: "投馬国候補" },
        },
        {
          id: "ito-archaeology-visits",
          label: "伊都国の王墓と博物館",
          description: "三雲南小路遺跡・平原遺跡を伊都国王墓として読む自治体解説と、出土資料を展示する伊都国歴史博物館の関係です。邪馬台国九州説の確定ではありません。",
          contextEntityIds: ["ito-state"],
          placeEntityIds: ["ito-history-museum", "mikumo-minamishoji-site", "mikumo-ihara-site", "hirabaru-site"],
          pointFocusEntityIds: { "ito-history-museum": "ito-history-museum", "mikumo-minamishoji-site": "mikumo-minamishoji-site", "mikumo-ihara-site": "mikumo-ihara-site", "hirabaru-site": "hirabaru-site" },
          assertionIds: ["archaeology-001", "archaeology-002", "archaeology-003", "archaeology-004", "archaeology-007"],
          appearance: { color: "#c89b5f", legendLabel: "伊都国の考古学" },
        },
        {
          id: "nakoku-archaeology-visits",
          label: "奴国の中心遺跡",
          description: "須玖岡本遺跡と、その一部を整備した奴国の丘歴史公園を、奴国中心地の考古学的文脈で結びます。",
          contextEntityIds: ["na-state"],
          placeEntityIds: ["sugu-okamoto-site", "nakoku-hill-park"],
          pointFocusEntityIds: { "sugu-okamoto-site": "sugu-okamoto-site", "nakoku-hill-park": "nakoku-hill-park" },
          assertionIds: ["archaeology-005", "archaeology-006"],
          appearance: { color: "#76b8c4", legendLabel: "奴国の考古学" },
        },
        {
          id: "fumi-koshoji-hypothesis",
          label: "光正寺古墳と不弥国説",
          description: "3世紀後半の光正寺古墳を不弥国王墓候補とする解釈です。不弥国や邪馬台国の所在地を確定する線ではありません。",
          contextEntityIds: ["fumi-state"],
          placeEntityIds: ["umi", "koshoji-kofun"],
          pointFocusEntityIds: { "umi": "fumi-state", "koshoji-kofun": "koshoji-kofun" },
          assertionIds: ["route-012", "archaeology-008"],
          appearance: { color: "#d58b74", dashArray: [5, 7], legendLabel: "不弥国王墓候補" },
        },
        {
          id: "wajinden-source-route",
          label: "魏志倭人伝の記述順",
          description: "狗邪韓国から不弥国まで、史料本文に現れる順序を現代の比定候補へ重ねた線です。奴国は広域比定ではなく、中心地候補の春日市・須玖遺跡群周辺を代表位置にしています。",
          contextEntityIds: ["guya-korea", "tsushima-state", "iki-state", "matsuro-state", "ito-state", "na-state", "fumi-state"],
          placeEntityIds: ["gimhae", "tsushima", "iki", "karatsu", "itoshima", "kasuga-sugu-core", "umi"],
          pointFocusEntityIds: { gimhae: "guya-korea", tsushima: "tsushima-state", iki: "iki-state", karatsu: "matsuro-state", itoshima: "ito-state", "kasuga-sugu-core": "na-state", umi: "fumi-state" },
          assertionIds: ["route-001", "route-002", "route-003", "route-004", "route-005", "route-006", "route-007", "route-008", "route-009", "route-010", "route-012", "route-018", "route-019"],
          appearance: { color: "#68c7bd", legendLabel: "史料順" },
        },
        {
          id: "wajinden-kyushu-hypothesis",
          label: "邪馬台国 九州説",
          description: "不弥国以降を北部九州へ続ける解釈モデルです。所在地の確定ではなく競合仮説として表示しています。",
          contextEntityIds: ["fumi-state", "yamatai-state"],
          placeEntityIds: ["umi", "northern-kyushu"],
          pointFocusEntityIds: { umi: "fumi-state", "northern-kyushu": "northern-kyushu" },
          assertionIds: ["route-012", "route-014", "route-016"],
          appearance: { color: "#75d4ba", dashArray: [8, 8], legendLabel: "九州説" },
        },
        {
          id: "wajinden-kinai-hypothesis",
          label: "邪馬台国 畿内説",
          description: "不弥国以降を奈良盆地方面へ続ける解釈モデルです。所在地の確定ではなく競合仮説として表示しています。",
          contextEntityIds: ["fumi-state", "yamatai-state"],
          placeEntityIds: ["umi", "nara-basin"],
          pointFocusEntityIds: { umi: "fumi-state", "nara-basin": "nara-basin" },
          assertionIds: ["route-012", "route-015", "route-017"],
          appearance: { color: "#d5b46d", dashArray: [8, 8], legendLabel: "畿内説" },
        },
      ],
    },
  ],
});

export const religionRelationsPack = LensKnowledgePackSchema.parse({
  schemaVersion: "0.1.0",
  id: "religion-relations",
  version: "0.2.0",
  label: "宗教の歴史関係・習合・概念比較",
  description: "宗教を単一の進化系統樹にせず、歴史的接触、習合、分析上の分類、概念比較を別の関係として保持する。",
  status: "draft",
  releasedAt: "2026-08-31",
  sources: [
    userExampleSource,
    munakataOfficialSource,
    usaSyncretismSource,
    kunisakiJapanHeritageSource,
    usaKunisakiConnectionSource,
    { id: "fukuoka-takasu-sazare", kind: "modern-reference", title: "髙祖神社（糸島市）", publisher: "福岡県観光連盟", url: "https://www.crossroadfukuoka.jp/spot/12547", retrievedAt: "2026-09-04", locator: "高祖神社と細石神社の神輿往来の伝承", reviewStatus: "reviewed" },
    { id: "kasuga-okamotoyama", kind: "modern-reference", title: "奴国かわらばん 第七号", publisher: "春日市", url: "https://www.city.kasuga.fukuoka.jp/_res/projects/default_project/_page_/001/009/436/kawara07.pdf", retrievedAt: "2026-09-04", locator: "熊野神社から南西側の岡本山地区と発掘調査", reviewStatus: "reviewed" },
    { id: "chikushino-kayu-uranai", kind: "modern-reference", title: "筑紫神社粥占行事付粥鉢一口", publisher: "筑紫野市", url: "https://www.city.chikushino.fukuoka.jp/soshiki/38/1888.html", retrievedAt: "2026-09-04", locator: "筑紫神社の粥占行事", reviewStatus: "reviewed" },
  ],
  viewpoints: [
    { id: "historical-relations", kind: "analytical", label: "歴史関係", description: "成立環境、伝播、接触、影響を時間的な関係として見る。" },
    { id: "syncretic-relations", kind: "analytical", label: "習合関係", description: "異なる伝統が併存・再解釈・混合した関係を見る。" },
    { id: "conceptual-comparison", kind: "analytical", label: "概念比較", description: "神、宇宙原理、因果、自然、祖霊などの比較軸で見る。直接の系譜を意味しない。" },
    { id: "regional-sacred-comparison", kind: "user", label: "祭祀空間比較", description: "宗像・宇佐・国東を、直接の系譜ではなく訪問から生まれた比較対象として並べる。" },
    { id: "religion-user-draft", kind: "user", label: "ユーザーの初期整理", description: "会話で提示された理解用の構造。学術的分類としては未検証。" },
    { id: "local-shrine-context", kind: "source", label: "地域神社の歴史・祭礼・立地", description: "神社間の伝承、遺跡との地理的重なり、現在まで続く祭礼を区別して読む。弥生祭祀からの連続性は自動的に仮定しない。" },
  ],
  entities: [
    { id: "nature-veneration", kind: "concept", label: "自然・場所への信仰", aliases: ["自然崇拝"] },
    { id: "ancestor-veneration", kind: "concept", label: "祖先・祖霊信仰", aliases: [] },
    { id: "animism", kind: "concept", label: "アニミズム", aliases: [] },
    { id: "shamanism", kind: "concept", label: "シャーマニズム", aliases: [] },
    { id: "ancient-kami-rites", kind: "tradition", label: "古代の神祭り・祭祀", aliases: ["古代神道"] },
    { id: "munakata-triad", kind: "deity", label: "宗像三女神", aliases: [] },
    { id: "munakata-taisha", kind: "place", label: "宗像大社", aliases: [] },
    { id: "hachiman-belief", kind: "tradition", label: "八幡信仰", aliases: [] },
    { id: "usa-jingu", kind: "place", label: "宇佐神宮", aliases: [] },
    { id: "kunisaki-peninsula", kind: "place", label: "国東半島", aliases: [] },
    { id: "rokugo-manzan", kind: "group", label: "六郷満山", aliases: ["六郷満山寺院群"] },
    { id: "regional-sacred-landscapes", kind: "concept", label: "三地域の祭祀空間", aliases: [] },
    { id: "shinto", kind: "tradition", label: "神道", aliases: [] },
    { id: "buddhism", kind: "tradition", label: "仏教", aliases: [] },
    { id: "shinbutsu-shugo", kind: "tradition", label: "神仏習合", aliases: [] },
    { id: "shugendo", kind: "tradition", label: "修験道", aliases: [] },
    { id: "ancient-indian-context", kind: "group", label: "古代インドの宗教・思想環境", aliases: [] },
    { id: "hindu-traditions", kind: "tradition", label: "ヒンドゥー教諸伝統", aliases: [] },
    { id: "brahman", kind: "concept", label: "ブラフマン／宇宙原理", aliases: [] },
    { id: "dependent-origination", kind: "concept", label: "縁起・因果・無常", aliases: [] },
    { id: "polytheism", kind: "concept", label: "多神教という分類", aliases: [] },
    { id: "monotheism", kind: "concept", label: "唯一神教という分類", aliases: [] },
    { id: "greco-roman", kind: "tradition", label: "ギリシャ・ローマの宗教伝統", aliases: [] },
    { id: "abrahamic-traditions", kind: "group", label: "アブラハム系宗教", aliases: [] },
    { id: "judaism", kind: "tradition", label: "ユダヤ教", aliases: [] },
    { id: "christianity", kind: "tradition", label: "キリスト教", aliases: [] },
    { id: "islam", kind: "tradition", label: "イスラム教", aliases: [] },
    { id: "takasu-shrine", kind: "place", label: "高祖神社", aliases: ["髙祖神社"], coordinates: { latitude: 33.5447583, longitude: 130.2603861 } },
    { id: "sazareishi-shrine", kind: "place", label: "細石神社", aliases: [], coordinates: { latitude: 33.536993, longitude: 130.242402 } },
    { id: "okamoto-kumano-shrine", kind: "place", label: "熊野神社", aliases: ["岡本熊野神社"], coordinates: { latitude: 33.5376, longitude: 130.4487 } },
    { id: "religion-sugu-okamoto-site", kind: "place", label: "須玖岡本遺跡", aliases: ["須玖岡本遺跡群"], coordinates: { latitude: 33.537733, longitude: 130.449405 } },
    { id: "chikushi-shrine", kind: "place", label: "筑紫神社", aliases: [], coordinates: { latitude: 33.4570984, longitude: 130.5428982 } },
    { id: "chikushi-kayu-ritual", kind: "event", label: "筑紫神社の粥占", aliases: ["粥占行事"] },
  ],
  assertions: [
    { id: "religion-001", subjectId: "nature-veneration", predicate: "compared_through", objectId: "animism", relationFamily: "conceptual-comparison", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "アニミズムを歴史的祖先ではなく分析概念として扱う。" },
    { id: "religion-002", subjectId: "ancestor-veneration", predicate: "associated_with", objectId: "ancient-kami-rites", relationFamily: "association", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-003", subjectId: "nature-veneration", predicate: "associated_with", objectId: "ancient-kami-rites", relationFamily: "association", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-004", subjectId: "shamanism", predicate: "compared_with", objectId: "ancient-kami-rites", relationFamily: "conceptual-comparison", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "直接の派生関係ではなく、儀礼実践の比較軸。" },
    { id: "religion-005", subjectId: "ancient-kami-rites", predicate: "historical_context_of", objectId: "shinto", relationFamily: "historical-context", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-006", subjectId: "shinto", predicate: "contributes_to", objectId: "shinbutsu-shugo", relationFamily: "syncretism", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-007", subjectId: "buddhism", predicate: "contributes_to", objectId: "shinbutsu-shugo", relationFamily: "syncretism", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-008", subjectId: "shinto", predicate: "historically_interacts_with", objectId: "shugendo", relationFamily: "syncretism", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-009", subjectId: "buddhism", predicate: "historically_interacts_with", objectId: "shugendo", relationFamily: "syncretism", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-022", subjectId: "munakata-triad", predicate: "enshrined_at", objectId: "munakata-taisha", relationFamily: "enshrinement", nature: "reviewed-reference", viewpointIds: ["syncretic-relations", "regional-sacred-comparison"], sourceIds: ["munakata-taisha-origin"], confidence: "high", reviewStatus: "reviewed", note: "三宮を宗像大社という集約地点として表示する。" },
    { id: "religion-023", subjectId: "hachiman-belief", predicate: "enshrined_at", objectId: "usa-jingu", relationFamily: "enshrinement", nature: "user-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-024", subjectId: "hachiman-belief", predicate: "contributes_to", objectId: "shinbutsu-shugo", relationFamily: "syncretism", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31", "usa-jingu-syncretism"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-025", subjectId: "usa-jingu", predicate: "associated_with", objectId: "shinbutsu-shugo", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["syncretic-relations", "regional-sacred-comparison"], sourceIds: ["usa-jingu-syncretism"], confidence: "high", reviewStatus: "reviewed" },
    { id: "religion-026", subjectId: "shugendo", predicate: "associated_with", objectId: "rokugo-manzan", relationFamily: "association", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-027", subjectId: "buddhism", predicate: "contributes_to", objectId: "rokugo-manzan", relationFamily: "syncretism", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31", "kunisaki-japan-heritage"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-028", subjectId: "hachiman-belief", predicate: "contributes_to", objectId: "rokugo-manzan", relationFamily: "syncretism", nature: "interpretive-model", viewpointIds: ["syncretic-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-029", subjectId: "rokugo-manzan", predicate: "associated_with", objectId: "kunisaki-peninsula", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["syncretic-relations", "regional-sacred-comparison"], sourceIds: ["kunisaki-japan-heritage"], confidence: "high", reviewStatus: "reviewed" },
    { id: "religion-030", subjectId: "usa-jingu", predicate: "culturally_connected_with", objectId: "rokugo-manzan", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["syncretic-relations", "regional-sacred-comparison"], sourceIds: ["usa-kunisaki-connection"], confidence: "high", reviewStatus: "reviewed", note: "文化庁日本遺産ポータルが明示する文化的関係。宗像を含む三地域全体の直接関係へは拡張しない。" },
    { id: "religion-031", subjectId: "regional-sacred-landscapes", predicate: "compares", objectId: "munakata-taisha", relationFamily: "conceptual-comparison", nature: "user-model", viewpointIds: ["regional-sacred-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "ユーザーの訪問を横断する比較線であり、三地域間の直接的な歴史関係を意味しない。" },
    { id: "religion-032", subjectId: "regional-sacred-landscapes", predicate: "compares", objectId: "usa-jingu", relationFamily: "conceptual-comparison", nature: "user-model", viewpointIds: ["regional-sacred-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "ユーザーの訪問を横断する比較線であり、三地域間の直接的な歴史関係を意味しない。" },
    { id: "religion-033", subjectId: "regional-sacred-landscapes", predicate: "compares", objectId: "kunisaki-peninsula", relationFamily: "conceptual-comparison", nature: "user-model", viewpointIds: ["regional-sacred-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "ユーザーの訪問を横断する比較線であり、三地域間の直接的な歴史関係を意味しない。" },
    { id: "religion-010", subjectId: "buddhism", predicate: "emerges_within", objectId: "ancient-indian-context", relationFamily: "historical-context", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "現代のヒンドゥー教から仏教が直接派生した、とは表現しない。" },
    { id: "religion-011", subjectId: "hindu-traditions", predicate: "develops_within", objectId: "ancient-indian-context", relationFamily: "historical-context", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-012", subjectId: "brahman", predicate: "associated_with", objectId: "hindu-traditions", relationFamily: "conceptual-comparison", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-013", subjectId: "dependent-origination", predicate: "associated_with", objectId: "buddhism", relationFamily: "conceptual-comparison", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-014", subjectId: "greco-roman", predicate: "classified_as", objectId: "polytheism", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-015", subjectId: "hindu-traditions", predicate: "partly_compared_as", objectId: "polytheism", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "多様な一神論的・一元論的理解もあるため単純分類しない。" },
    { id: "religion-016", subjectId: "judaism", predicate: "member_of", objectId: "abrahamic-traditions", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-017", subjectId: "christianity", predicate: "member_of", objectId: "abrahamic-traditions", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-018", subjectId: "islam", predicate: "member_of", objectId: "abrahamic-traditions", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["historical-relations"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft", note: "キリスト教からの単純な派生線ではなく、共有する伝承と歴史的接触を別途表す。" },
    { id: "religion-019", subjectId: "judaism", predicate: "classified_as", objectId: "monotheism", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-020", subjectId: "christianity", predicate: "classified_as", objectId: "monotheism", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-021", subjectId: "islam", predicate: "classified_as", objectId: "monotheism", relationFamily: "classification", nature: "interpretive-model", viewpointIds: ["conceptual-comparison"], sourceIds: ["user-example-2026-08-31"], confidence: "not-rated", reviewStatus: "draft" },
    { id: "religion-034", subjectId: "takasu-shrine", predicate: "has_tradition_of_mikoshi_exchange_with", objectId: "sazareishi-shrine", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["local-shrine-context"], sourceIds: ["fukuoka-takasu-sazare"], confidence: "medium", reviewStatus: "reviewed", note: "神輿往来の伝承が紹介されていることを確認。古代以来の連続性を確定しない。" },
    { id: "religion-035", subjectId: "okamoto-kumano-shrine", predicate: "located_in_archaeological_area_of", objectId: "religion-sugu-okamoto-site", relationFamily: "association", nature: "reviewed-reference", viewpointIds: ["local-shrine-context"], sourceIds: ["kasuga-okamotoyama"], confidence: "high", reviewStatus: "reviewed", note: "岡本山地区における地理的・調査上の重なり。弥生祭祀と現在の神社の信仰継続を意味しない。" },
    { id: "religion-036", subjectId: "chikushi-shrine", predicate: "hosts", objectId: "chikushi-kayu-ritual", relationFamily: "ritual", nature: "reviewed-reference", viewpointIds: ["local-shrine-context"], sourceIds: ["chikushino-kayu-uranai"], confidence: "high", reviewStatus: "reviewed" },
  ],
  presets: [
    { id: "religion-history", label: "歴史関係", lensType: "timeline", description: "成立環境、歴史的接触、伝播を表示し、概念的類似とは分離する。", rootEntityIds: ["ancient-kami-rites", "ancient-indian-context", "abrahamic-traditions"], relationFamilies: ["historical-context", "influence", "classification"], viewpointIds: ["historical-relations"], expansionDepth: 2 },
    { id: "religion-syncretism", label: "習合関係", lensType: "relationship", description: "神仏習合や修験道など、伝統が接触し再構成された関係を表示する。", rootEntityIds: ["munakata-taisha", "usa-jingu", "shinbutsu-shugo", "shugendo", "rokugo-manzan"], relationFamilies: ["syncretism", "enshrinement", "association"], viewpointIds: ["syncretic-relations"], expansionDepth: 2 },
    { id: "religion-concepts", label: "概念比較", lensType: "relationship", description: "多神・唯一神・宇宙原理・自然・祖霊などを比較する。歴史的派生を意味しない。", rootEntityIds: ["polytheism", "monotheism", "brahman", "animism"], relationFamilies: ["classification", "conceptual-comparison", "association"], viewpointIds: ["conceptual-comparison"], expansionDepth: 2 },
    { id: "regional-sacred-comparison", label: "祭祀空間比較", lensType: "relationship", description: "宗像・宇佐・国東を訪問から生まれた比較対象として並べ、確認済みの地域固有関係を周囲に重ねる。比較線は直接の歴史関係を意味しない。", rootEntityIds: ["regional-sacred-landscapes"], relationFamilies: ["conceptual-comparison", "enshrinement", "association"], viewpointIds: ["regional-sacred-comparison"], expansionDepth: 3 },
    {
      id: "local-shrine-connections",
      label: "地域神社",
      lensType: "relationship",
      description: "邪馬台国関連探索で訪れた神社を、伝承・遺跡との立地・祭礼に分けて読み直す。古代祭祀からの連続性は旅行記上の問いとして残す。",
      rootEntityIds: ["takasu-shrine", "sazareishi-shrine", "okamoto-kumano-shrine", "chikushi-shrine"],
      relationFamilies: ["association", "ritual"],
      viewpointIds: ["local-shrine-context"],
      expansionDepth: 2,
      mapConnections: [
        { id: "takasu-sazare-tradition", label: "高祖神社と細石神社", description: "両社の間に神輿の往来があったという伝承を示します。古代からの継続を確定する線ではありません。", placeEntityIds: ["takasu-shrine", "sazareishi-shrine"], pointFocusEntityIds: { "takasu-shrine": "takasu-shrine", "sazareishi-shrine": "sazareishi-shrine" }, assertionIds: ["religion-034"], appearance: { color: "#b794d4", dashArray: [6, 6], legendLabel: "神社間伝承" } },
        { id: "kumano-sugu-overlap", label: "熊野神社と須玖岡本遺跡", description: "熊野神社が須玖岡本遺跡の岡本山地区の発掘・整備範囲に位置することを示します。信仰の連続性を意味しません。", placeEntityIds: ["okamoto-kumano-shrine", "religion-sugu-okamoto-site"], pointFocusEntityIds: { "okamoto-kumano-shrine": "okamoto-kumano-shrine", "religion-sugu-okamoto-site": "religion-sugu-okamoto-site" }, assertionIds: ["religion-035"], appearance: { color: "#8db8a4", dashArray: [3, 6], legendLabel: "遺跡との立地" } },
      ],
    },
  ],
});

export const seedLensKnowledgePacks = [
  japaneseMythologyPack,
  wajindenRoutesPack,
  religionRelationsPack,
];
